# -*- coding: utf-8 -*-
# Hebrew strings for the Symbigram language add-on.
#
# Source text -> Hebrew. Anything not listed here stays English, which is the intended fallback:
# when the application gains new strings this file can lag behind without breaking anything.
# Rebuild the pack with build.cmd in this folder after changing it.
#
# Moved out of tools/translate.py when Hebrew became an add-on, so this is now the only copy.
TABLE = {
'version %1': 'גרסה %1',
'A Telegram client for Symbian Anna/Belle, ported from Lumigram/LumigramPlus for Windows Phone 8.1. It speaks MTProto 2.0 directly to Telegram - no bridge, no proxy; the encryption key is made on the phone.': 'לקוח טלגרם ל-Symbian Anna/Belle, מבוסס על Lumigram/LumigramPlus ל-Windows Phone 8.1. הוא מדבר MTProto 2.0 ישירות מול טלגרם — ללא גשר וללא פרוקסי; מפתח ההצפנה נוצר בטלפון.',
'Sign-in is by QR code only (scan from a signed-in Telegram, plus the two-step password if set). Text messages, photos and files (view, save and send), groups and channels.': 'הכניסה היא בעזרת קוד QR בלבד (סריקה מטלגרם שכבר מחוברים בו, בתוספת סיסמת האימות הדו-שלבי אם הוגדרה). הודעות טקסט, תמונות וקבצים (צפייה, שמירה ושליחה), קבוצות וערוצים.',
'Log': 'יומן',
'Copy log': 'העתקת היומן',
'Not connected.': 'לא מחובר.',
'Connecting...': 'מתחבר...',
'Connecting and creating the encryption key...': 'מתחבר ויוצר את מפתח ההצפנה...',
'Checking the password (this takes a few seconds)...': 'בודק את הסיסמה (זה אורך כמה שניות)...',
'This account has two-step verification. Enter the password.': 'לחשבון זה יש אימות דו-שלבי. הזינו את הסיסמה.',
'Requesting a sign-in code...': 'מבקש קוד כניסה...',
'Waiting for the code to be scanned...': 'ממתין לסריקת הקוד...',
'Signing in...': 'מתחבר...',
'Connection lost: %1. Reconnecting...': 'החיבור אבד: %1. מתחבר מחדש...',
'Connection failed: %1. Retrying...': 'החיבור נכשל: %1. מנסה שוב...',
'Enter the password.': 'הזינו את הסיסמה.',
'Copied.': 'הועתק.',
'Load older messages': 'טעינת הודעות ישנות יותר',
'Reload': 'רענון',
'Unmute': 'ביטול השתקה',
'Mute': 'השתקה',
'Mark as read': 'סימון כנקרא',
'Copy text': 'העתקת הטקסט',
'Reply': 'תגובה',
'Replying to': 'בתגובה ל',
'Edit': 'עריכה',
'Editing message': 'עריכת הודעה',
'edit the text, then tap Save': 'ערכו את הטקסט, ואז הקישו על שמירה',
'Save': 'שמירה',
'Could not edit the message: %1': 'לא ניתן היה לערוך את ההודעה: %1',
'Retry': 'ניסיון חוזר',
'Delete for me': 'מחיקה אצלי',
'Delete for everyone': 'מחיקה אצל כולם',
'connecting...': 'מתחבר...',
'offline': 'לא מחובר',
'online': 'מחובר',
'Older messages': 'הודעות ישנות יותר',
'Could not load the messages: %1': 'לא ניתן היה לטעון את ההודעות: %1',
'No messages yet.': 'אין הודעות עדיין.',
'channel - only its admins can post': 'ערוץ — רק מנהליו יכולים לפרסם',
'message': 'הודעה',
'Send': 'שליחה',
'Yesterday': 'אתמול',
'%1 is typing...': '%1 מקליד...',
'typing...': 'מקליד...',
'You: %1': 'אתם: %1',
'Connect': 'התחברות',
'Disconnect': 'ניתוק',
'Settings': 'הגדרות',
'About': 'אודות',
'Sign out': 'התנתקות',
'Exit': 'יציאה',
'Sign out? The session will be ended on Telegram and removed from this phone.': 'להתנתק? ההפעלה תסתיים בטלגרם ותוסר מטלפון זה.',
'Cancel': 'ביטול',
'New chat': "צ'אט חדש",
'Find': 'חיפוש',
"@username, phone number, t.me link, or a contact's name": '@שם_משתמש, מספר טלפון, קישור t.me, או שם של איש קשר',
'@username or +phone': '@שם_משתמש או +טלפון',
'Clear history': 'ניקוי ההיסטוריה',
'Delete all messages of "%1" on Telegram (for you)?': 'למחוק את כל ההודעות של «%1» בטלגרם (אצלכם)?',
'Delete': 'מחיקה',
'loading...': 'טוען...',
'Older chats': "צ'אטים ישנים יותר",
'Loading chats...': "טוען צ'אטים...",
'No chats yet. Tap + to find someone.': "אין צ'אטים עדיין. הקישו על + כדי למצוא מישהו.",
'Offline. Use the menu to connect.': 'לא מחובר. השתמשו בתפריט כדי להתחבר.',
'Telegram for Symbian': 'טלגרם ל-Symbian',
'No connection. Tap the refresh button to try again.': 'אין חיבור. הקישו על כפתור הרענון כדי לנסות שוב.',
'The code renews in %1 s': "הקוד יתחדש בעוד %1 שנ'",
'Open Telegram on a phone or PC where you are signed in: Settings > Devices > Link Desktop Device, and scan this code.': 'פתחו את טלגרם בטלפון או במחשב שבו אתם מחוברים: הגדרות > מכשירים > קישור מכשיר שולחני, וסרקו קוד זה.',
'Two-step verification password': 'סיסמת אימות דו-שלבי',
'hint: %1': 'רמז: %1',
'password': 'סיסמה',
'show password': 'הצגת הסיסמה',
'checking...': 'בודק...',
'sign in': 'כניסה',
"Symbigram talks MTProto 2.0 straight to Telegram's servers: the encryption key is made on this phone and never leaves it. The session shows up under Devices in Telegram, where it can be ended at any time.": 'Symbigram מדבר MTProto 2.0 ישירות מול השרתים של טלגרם: מפתח ההצפנה נוצר בטלפון זה ולעולם אינו עוזב אותו. ההפעלה מופיעה תחת «מכשירים» בטלגרם, שם ניתן לסיים אותה בכל עת.',
'Forwarded from %1': 'הועבר מ-%1',
'edited': 'נערך',
'Today': 'היום',
'reply': 'תגובה',
'You': 'אתם',
'last seen at %1': 'נראה לאחרונה ב-%1',
'last seen yesterday at %1': 'נראה לאחרונה אתמול ב-%1',
'last seen %1': 'נראה לאחרונה %1',
'last seen recently': 'נראה לאחרונה לפני זמן קצר',
'last seen within a week': 'נראה לאחרונה בשבוע האחרון',
'last seen within a month': 'נראה לאחרונה בחודש האחרון',
'last seen a long time ago': 'נראה לאחרונה לפני זמן רב',
'bot': 'בוט',
'Saved Messages': 'הודעות שמורות',
'channel, %1 subscribers': 'ערוץ, %1 מנויים',
'channel': 'ערוץ',
'%1 members': '%1 חברים',
'group': 'קבוצה',
'The message was not sent: %1': 'ההודעה לא נשלחה: %1',
'key exchange failed: %1': 'החלפת המפתחות נכשלה: %1',
'no response from the server': 'אין תגובה מהשרת',
'connection closed': 'החיבור נסגר',
'connection timed out': 'תם הזמן הקצוב לחיבור',
'Symbigram: new message': 'Symbigram: הודעה חדשה',
'Symbigram: %1 new messages': 'Symbigram: %1 הודעות חדשות',
'App language': 'שפת היישום',
'System default': 'ברירת המחדל של המערכת',
'Notifications': 'התראות',
'Popup for new messages': 'חלון קופץ להודעות חדשות',
'Vibrate': 'רטט',
'Groups and channels': 'קבוצות וערוצים',
'For messages that arrive while another application is in front: the "new messages" dialog, the popup and the vibration. Chats muted in Telegram stay quiet. Symbigram stays connected in the background either way.': "עבור הודעות שמגיעות כאשר יישום אחר נמצא בחזית: חלון «הודעות חדשות», החלון הקופץ והרטט. צ'אטים שהושתקו בטלגרם נשארים שקטים. Symbigram נשאר מחובר ברקע בכל מקרה.",
'Connect on start': 'התחברות בעת ההפעלה',
'Takes effect after the app is restarted.': 'ייכנס לתוקף לאחר הפעלה מחדש של היישום.',
'Signed out.': 'התנתקתם.',
'Enter a username, a phone number or a name.': 'הזינו שם משתמש, מספר טלפון או שם.',
'This account has no password set.': 'לחשבון זה לא הוגדרה סיסמה.',
'Unsupported password method.': 'שיטת סיסמה לא נתמכת.',
'Nobody found.': 'לא נמצא אף אחד.',
'The session was ended (%1). Please sign in again.': 'ההפעלה הסתיימה (%1). אנא היכנסו שוב.',
'Wrong password.': 'סיסמה שגויה.',
'Too many attempts. Wait %1 seconds.': 'יותר מדי ניסיונות. המתינו %1 שניות.',
'Could not load the chat list: %1': "לא ניתן היה לטעון את רשימת הצ'אטים: %1",
'user %1': 'משתמש %1',
'chat %1': "צ'אט %1",
'deleted account': 'חשבון שנמחק',
'video': 'וידאו',
'photo': 'תמונה',
'location %1, %2': 'מיקום %1, %2',
'location': 'מיקום',
'location: %1': 'מיקום: %1',
'contact: %1 %2 %3': 'איש קשר: %1 %2 %3',
'poll: %1': 'סקר: %1',
'dice: %1': 'קובייה: %1',
'game': 'משחק',
'invoice': 'חשבונית',
'story': 'סטורי',
'file': 'קובץ',
'sticker': 'מדבקה',
'sticker %1': 'מדבקה %1',
'voice message %1': 'הודעה קולית %1',
'voice message': 'הודעה קולית',
'video message %1': 'הודעת וידאו %1',
'video message': 'הודעת וידאו',
'GIF': 'GIF',
'video %1': 'וידאו %1',
'audio %1': 'שמע %1',
'audio': 'שמע',
'image': 'תמונה',
'%1 MB': '%1 MB',
'%1 KB': '%1 KB',
'%1 B': '%1 B',
'file: %1 (%2)': 'קובץ: %1 (%2)',
'unsupported attachment': 'קובץ מצורף לא נתמך',
'attachment': 'קובץ מצורף',
'created the group "%1"': 'יצר את הקבוצה «%1»',
'created the channel "%1"': 'יצר את הערוץ «%1»',
'added %1': 'הוסיף את %1',
'removed %1': 'הסיר את %1',
'joined by invite link': 'הצטרף באמצעות קישור הזמנה',
'pinned a message': 'נעץ הודעה',
'joined Telegram': 'הצטרף לטלגרם',
'cleared the history': 'ניקה את ההיסטוריה',
'service message': 'הודעת שירות',
'empty message': 'הודעה ריקה',
'Folders': 'תיקיות',
'Folder': 'תיקייה',
'All chats': "כל הצ'אטים",
'Archive': 'ארכיון',
'tap to switch folder': 'הקישו כדי להחליף תיקייה',
'The archive is empty.': 'הארכיון ריק.',
'No chats in this folder.': "אין צ'אטים בתיקייה זו.",
'Keep a log': 'שמירת יומן',
'Off by default. Turn it on only to collect a diagnostic log (shown on the About page) when something goes wrong.': 'כבוי כברירת מחדל. הפעילו רק כדי לאסוף יומן אבחון (מוצג בעמוד «אודות») כשמשהו משתבש.',
'Logging is off. Turn on "Keep a log" in Settings to collect one.': 'רישום היומן כבוי. הפעילו «שמירת יומן» בהגדרות כדי לאסוף אותו.',
'Images (*.jpg *.jpeg *.png *.gif *.bmp)': 'תמונות (*.jpg *.jpeg *.png *.gif *.bmp)',
'All files (*)': 'כל הקבצים (*)',
'Choose an image': 'בחירת תמונה',
'Send image': 'שליחת תמונה',
'Send file': 'שליחת קובץ',
'Caption (optional)': 'כיתוב (רשות)',
'add a caption': 'הוספת כיתוב',
'Choose a file': 'בחירת קובץ',
'Sending the image...': 'שולח את התמונה...',
'Sending the file...': 'שולח את הקובץ...',
'Image': 'תמונה',
'File': 'קובץ',
'Save to phone': 'שמירה בטלפון',
'Open': 'פתיחה',
'Close': 'סגירה',
'Tap to load': 'הקישו כדי לטעון',
'Failed - tap to retry': 'נכשל — הקישו כדי לנסות שוב',
'Voice message': 'הודעה קולית',
'Video': 'וידאו',
'tap to open': 'הקישו כדי לפתוח',
'downloading %1%': 'מוריד %1%',
'tap to download': 'הקישו כדי להוריד',
'Saved to %1': 'נשמר ב-%1',
'Could not save the file.': 'לא ניתן היה לשמור את הקובץ.',
'the server rejected a part of the file': 'השרת דחה חלק מהקובץ',
'the file is served from a CDN, which is not supported': 'הקובץ מוגש מ-CDN, שאינו נתמך',
'unexpected reply': 'תגובה בלתי צפויה',
'could not write the file': 'לא ניתן היה לכתוב את הקובץ',
'could not create the file': 'לא ניתן היה ליצור את הקובץ',
'the file is empty': 'הקובץ ריק',
'could not read the file': 'לא ניתן היה לקרוא את הקובץ',
'the file is too large': 'הקובץ גדול מדי',
'Start secret chat': "התחלת צ'אט סודי",
'Verify encryption key': 'אימות מפתח ההצפנה',
'Self-destruct timer': 'טיימר השמדה עצמית',
'Delete secret chat': "מחיקת צ'אט סודי",
'End this secret chat? Its messages, which live only on this device, will be removed here.': "לסיים צ'אט סודי זה? הודעותיו, השמורות רק במכשיר זה, יוסרו כאן.",
'Encryption key': 'מפתח הצפנה',
'If this key matches on both phones, no one is intercepting the chat. Compare it with %1 in person or over a trusted channel.': "אם מפתח זה תואם בשני הטלפונים, אף אחד אינו מיירט את הצ'אט. השוו אותו עם %1 באופן אישי או דרך ערוץ מהימן.",
'%1 wants to start an end-to-end encrypted chat.': "%1 רוצה להתחיל צ'אט מוצפן מקצה לקצה.",
'Waiting for the other side to come online and accept...': 'ממתין שהצד השני יתחבר ויקבל...',
'Decline': 'דחייה',
'Cancel request': 'ביטול הבקשה',
'encrypted message': 'הודעה מוצפנת',
'secret chat': "צ'אט סודי",
'wants to start a secret chat': "רוצה להתחיל צ'אט סודי",
'waiting to be accepted...': 'ממתין לאישור...',
'end-to-end encrypted': 'מוצפן מקצה לקצה',
'end-to-end encrypted, self-destruct %1s': "מוצפן מקצה לקצה, השמדה עצמית %1 שנ'",
'Secret chats can only be opened with a person.': "ניתן לפתוח צ'אטים סודיים רק עם אדם.",
'The secret chat is not ready.': "הצ'אט הסודי אינו מוכן.",
'Secret chats can only be started with a person.': "ניתן להתחיל צ'אטים סודיים רק עם אדם.",
'Starting a secret chat...': "מתחיל צ'אט סודי...",
'Someone wants to start a secret chat.': "מישהו רוצה להתחיל צ'אט סודי.",
'%1 wants to start a secret chat.': "%1 רוצה להתחיל צ'אט סודי.",
'Secret chat is ready.': "הצ'אט הסודי מוכן.",
'Secret chat': "צ'אט סודי",
'Encrypted message': 'הודעה מוצפנת',
'Could not start the secret chat: %1': "לא ניתן היה להתחיל את הצ'אט הסודי: %1",
'Could not accept the secret chat: %1': "לא ניתן היה לקבל את הצ'אט הסודי: %1",
'Accept': 'קבלה',
'Off': 'כבוי',
'5 seconds': '5 שניות',
'30 seconds': '30 שניות',
'1 minute': 'דקה אחת',
'1 hour': 'שעה אחת',
'1 day': 'יום אחד',
'1 week': 'שבוע אחד',
'Saved': 'נשמר',
'File saved to: %1': 'הקובץ נשמר ב-%1',
'Could not save the file to %1': 'לא ניתן היה לשמור את הקובץ ב-%1',
'Could not open the file.': 'לא ניתן היה לפתוח את הקובץ.',
'Phone memory': 'זיכרון הטלפון',
'Mass memory': 'אחסון המוני',
'Memory card': 'כרטיס זיכרון',
'Save downloads to': 'שמירת הורדות אל',
'Clear cache': 'ניקוי המטמון',
'Clear': 'נקה',
'Downloaded media held on the phone: %1': 'מדיה שהורדה ונשמרת בטלפון: %1',
"The app's private store of downloaded photos, avatars and files (separate from the folder above). Clearing it just re-downloads on demand.": 'האחסון הפרטי של היישום לתמונות, לתמונות פרופיל ולקבצים שהורדו (נפרד מהתיקייה שלמעלה). ניקויו רק גורם להורדה מחדש לפי הצורך.',
'Delete the %1 of downloaded media held on the phone? It will be fetched again when needed.': 'למחוק את %1 של המדיה שהורדה ונשמרת בטלפון? היא תורד שוב בעת הצורך.',
'Cache cleared (%1 freed).': 'המטמון נוקה (%1 פונו).',
'Choose folder...': 'בחירת תיקייה...',
'Choose download folder': 'בחירת תיקיית הורדות',
'SOCKS5 proxy': 'פרוקסי SOCKS5',
'Proxy server': 'שרת פרוקסי',
'not set': 'לא הוגדר',
'Route the connection through a SOCKS5 proxy. Changing it reconnects.': 'ניתוב החיבור דרך פרוקסי SOCKS5. שינוי גורם להתחברות מחדש.',
'Server': 'שרת',
'host or IP': 'מארח או IP',
'Port': 'יציאה',
'Username (optional)': 'שם משתמש (רשות)',
'Password (optional)': 'סיסמה (רשות)',
'Reconnect': 'התחברות מחדש',
'Enable': 'הפעלה',
'Set up proxy': 'הגדרת פרוקסי',
'Cannot record a voice message here.': 'לא ניתן להקליט כאן הודעה קולית.',
'Sending the voice message...': 'שולח את ההודעה הקולית...',
'the microphone is unavailable (%1)': 'המיקרופון אינו זמין (%1)',
'could not open the microphone (%1)': 'לא ניתן היה לפתוח את המיקרופון (%1)',
'could not start recording (%1)': 'לא ניתן היה להתחיל בהקלטה (%1)',
'the recording was too short': 'ההקלטה הייתה קצרה מדי',
'could not encode the recording': 'לא ניתן היה לקודד את ההקלטה',
'could not save the recording': 'לא ניתן היה לשמור את ההקלטה',
'could not read the recording': 'לא ניתן היה לקרוא את ההקלטה',
'Archive chat': "העברת צ'אט לארכיון",
'Unarchive chat': "הוצאת צ'אט מהארכיון",
'Move to folder': 'העברה לתיקייה',
'All chats (no folder)': "כל הצ'אטים (ללא תיקייה)",
'Sign in with QR code': 'כניסה עם קוד QR',
'Sign in with phone number': 'כניסה עם מספר טלפון',
'Use QR code instead': 'שימוש בקוד QR במקום',
'Phone number': 'מספר טלפון',
'Include the country code. Telegram will send a login code to this number.': 'כללו את קידומת המדינה. טלגרם ישלח קוד כניסה למספר זה.',
'requesting...': 'מבקש...',
'send code': 'שליחת קוד',
'Enter the code sent to %1': 'הזינו את הקוד שנשלח אל %1',
'code': 'קוד',
'signing in...': 'מתחבר...',
'Resend code': 'שליחת קוד מחדש',
'Change number': 'שינוי מספר',
'Enter your phone number.': 'הזינו את מספר הטלפון שלכם.',
'Enter the code.': 'הזינו את הקוד.',
'Enter the code Telegram sent to %1.': 'הזינו את הקוד שטלגרם שלח אל %1.',
'Requesting a code...': 'מבקש קוד...',
'Enter your phone number, with the country code, to get a code.': 'הזינו את מספר הטלפון שלכם, עם קידומת המדינה, כדי לקבל קוד.',
'Enter a valid phone number, with the country code.': 'הזינו מספר טלפון תקין, עם קידומת המדינה.',
"No Telegram account uses this number. Sign-up isn't supported here.": 'אין חשבון טלגרם שמשתמש במספר זה. הרשמה אינה נתמכת כאן.',
'That phone number is not valid.': 'מספר הטלפון הזה אינו תקין.',
'That phone number is banned from Telegram.': 'מספר הטלפון הזה חסום בטלגרם.',
'Too many codes requested for this number. Try again later.': 'התבקשו יותר מדי קודים למספר זה. נסו שוב מאוחר יותר.',
'Too many attempts. Try again later.': 'יותר מדי ניסיונות. נסו שוב מאוחר יותר.',
"This build's Telegram API key was rejected.": 'מפתח ה-API של טלגרם בגרסה זו נדחה.',
'Wrong code. Check it and try again.': 'קוד שגוי. בדקו אותו ונסו שוב.',
'The code expired. Request a new one.': 'הקוד פג. בקשו קוד חדש.',
'Delete chat': "מחיקת צ'אט",
'Myself': 'אצלי',
'All': 'אצל כולם',
'Delete for all': 'מחיקה אצל כולם',
'Delete the chat "%1"? "All" also removes it for the other side.': "למחוק את הצ'אט «%1»? «אצל כולם» מוחק אותו גם אצל הצד השני.",
'Could not change the folder: %1': 'לא ניתן היה לשנות את התיקייה: %1',
'That folder must keep at least one chat, so the chat stays in it too.': "בתיקייה זו חייב להישאר לפחות צ'אט אחד, ולכן הצ'אט נשאר גם בה.",
'That folder no longer exists.': 'התיקייה הזו כבר אינה קיימת.',
'the proxy refused our authentication method': 'הפרוקסי דחה את שיטת האימות שלנו',
'proxy authentication failed - check the username and password': 'אימות הפרוקסי נכשל — בדקו את שם המשתמש והסיסמה',
'the proxy sent a malformed reply': 'הפרוקסי שלח תגובה פגומה',
'the proxy could not reach the server (%1)': 'הפרוקסי לא הצליח להגיע לשרת (%1)',
'playing... tap to stop': 'מנגן... הקישו כדי לעצור',
'loading %1%': 'טוען %1%',
'tap to play': 'הקישו כדי לנגן',
'tap to play in player': 'הקישו כדי לנגן בנגן',
'buffering %1%... opening player': 'ממלא מאגר %1%... פותח את הנגן',
'Could not play this audio: %1': 'לא ניתן היה לנגן שמע זה: %1',
'could not open the voice file': 'לא ניתן היה לפתוח את קובץ השמע',
'could not decode the voice message': 'לא ניתן היה לפענח את ההודעה הקולית',
'audio is unavailable (%1)': 'השמע אינו זמין (%1)',
'could not open audio (%1)': 'לא ניתן היה לפתוח את השמע (%1)',
'could not prepare playback': 'לא ניתן היה להכין את הנגינה',
'could not start playback (%1)': 'לא ניתן היה להתחיל בנגינה (%1)',
'could not play (%1)': 'לא ניתן היה לנגן (%1)',
'recording is only available on the phone': 'הקלטה זמינה רק בטלפון',
'Proxy: %1': 'פרוקסי: %1',
'on': 'פועל',
'No connection through the proxy. Check the proxy or tap Reconnect.': 'אין חיבור דרך הפרוקסי. בדקו את הפרוקסי או הקישו על התחברות מחדש.',
'No connection. Tap Reconnect, or set up a proxy if Telegram is blocked.': 'אין חיבור. הקישו על התחברות מחדש, או הגדירו פרוקסי אם טלגרם חסום.',
'Saved photos and files go here. Pick a drive, or "Choose folder..." for any folder.': 'תמונות וקבצים שנשמרו יגיעו לכאן. בחרו כונן, או «בחירת תיקייה...» לכל תיקייה שהיא.',
'Saved photos and files go to a "Symbigram" folder on this drive.': 'תמונות וקבצים שנשמרו מגיעים לתיקיית «Symbigram» בכונן זה.',
'End the secret chat with "%1"? Its messages live only on this device and will be removed here.': "לסיים את הצ'אט הסודי עם «%1»? הודעותיו שמורות רק במכשיר זה ויוסרו כאן.",
'%1 wants to start a secret chat': "%1 רוצה להתחיל צ'אט סודי",
}
