# -*- coding: utf-8 -*-
# Turkish strings for the Symbigram language add-on.
#
# Source text -> Turkish. Anything not listed here stays English, which is the intended
# fallback: when the application gains new strings this file can lag behind without breaking
# anything. Rebuild the pack with addons/turkish/build.py after changing it.
TR = {
"version %1": "sürüm %1",
"A Telegram client for Symbian Anna/Belle, ported from Lumigram/LumigramPlus for Windows Phone 8.1. It speaks MTProto 2.0 directly to Telegram - no bridge, no proxy; the encryption key is made on the phone.": "Symbian Anna/Belle için, Windows Phone 8.1'deki Lumigram/LumigramPlus'tan uyarlanmış bir Telegram istemcisi. Telegram ile doğrudan MTProto 2.0 konuşur - köprü yok, vekil sunucu yok; şifreleme anahtarı telefonda oluşturulur.",
"Sign-in is by QR code only (scan from a signed-in Telegram, plus the two-step password if set). Text messages, photos and files (view, save and send), groups and channels.": "Giriş yalnızca QR kodla yapılır (giriş yapılmış bir Telegram'dan taratın, ayarlıysa iki adımlı parolayla birlikte). Metin iletileri, fotoğraflar ve dosyalar (görüntüleme, kaydetme ve gönderme), gruplar ve kanallar.",
"Log": "Günlük",
"Copy log": "Günlüğü kopyala",
"%1 MB": "%1 MB",
"%1 KB": "%1 KB",
"%1 B": "%1 B",
"Cache cleared (%1 freed).": "Önbellek temizlendi (%1 boşaltıldı).",
"Not connected.": "Bağlı değil.",
"Connecting...": "Bağlanıyor...",
"Connecting and creating the encryption key...": "Bağlanılıyor ve şifreleme anahtarı oluşturuluyor...",
"Checking the password (this takes a few seconds)...": "Parola denetleniyor (birkaç saniye sürer)...",
"This account has two-step verification. Enter the password.": "Bu hesapta iki adımlı doğrulama var. Parolayı girin.",
"Signing in...": "Giriş yapılıyor...",
"Enter the code Telegram sent to %1.": "Telegram'ın %1 numarasına gönderdiği kodu girin.",
"Requesting a code...": "Kod isteniyor...",
"Enter your phone number, with the country code, to get a code.": "Kod almak için telefon numaranızı ülke koduyla girin.",
"Requesting a sign-in code...": "Giriş kodu isteniyor...",
"Waiting for the code to be scanned...": "Kodun taranması bekleniyor...",
"Low": "Düşük",
"Medium": "Orta",
"Loud": "Yüksek",
"Short (0.4 s)": "Kısa (0,4 sn)",
"1 second": "1 saniye",
"2 seconds": "2 saniye",
"3 seconds": "3 saniye",
"5 seconds": "5 saniye",
"Off": "Kapalı",
"First message only": "Yalnızca ilk ileti",
"Every message": "Her ileti",
"Extra small": "Çok küçük",
"Small": "Küçük",
"Large": "Büyük",
"Extra large": "Çok büyük",
"Thumbnail": "Küçük resim",
"Full": "Tam",
"Phone memory": "Telefon belleği",
"Mass memory": "Yığın bellek",
"Memory card": "Hafıza kartı",
"Choose download folder": "İndirme klasörünü seçin",
"Cannot record a voice message here.": "Burada sesli ileti kaydedilemez.",
"Sending the voice message...": "Sesli ileti gönderiliyor...",
"Connection lost: %1. Reconnecting...": "Bağlantı koptu: %1. Yeniden bağlanılıyor...",
"Connection failed: %1. Retrying...": "Bağlantı başarısız: %1. Yeniden deneniyor...",
"Enter the password.": "Parolayı girin.",
"Enter your phone number.": "Telefon numaranızı girin.",
"Enter the code.": "Kodu girin.",
"Added to Contacts.": "Rehbere eklendi.",
"%1 added to Contacts.": "%1 rehbere eklendi.",
"That chat is not in your list.": "Bu sohbet listenizde yok.",
"Opening @%1...": "@%1 açılıyor...",
"Secret chats can only be started with a person.": "Gizli sohbet yalnızca bir kişiyle başlatılabilir.",
"Starting a secret chat...": "Gizli sohbet başlatılıyor...",
"Someone wants to start a secret chat.": "Biri gizli sohbet başlatmak istiyor.",
"%1 wants to start a secret chat.": "%1 gizli sohbet başlatmak istiyor.",
"Secret chat": "Gizli sohbet",
"%1 wants to start a secret chat": "%1 gizli sohbet başlatmak istiyor",
"Secret chat is ready.": "Gizli sohbet hazır.",
"Encrypted message": "Şifreli ileti",
"Images (*.jpg *.jpeg *.png *.gif *.bmp)": "Resimler (*.jpg *.jpeg *.png *.gif *.bmp)",
"All files (*)": "Tüm dosyalar (*)",
"Choose an image": "Bir resim seçin",
"Choose a file": "Bir dosya seçin",
"Sending the image...": "Resim gönderiliyor...",
"Sending the file...": "Dosya gönderiliyor...",
"Copied.": "Kopyalandı.",
"Skip to bottom": "En alta git",
"Load older messages": "Daha eski iletileri yükle",
"Reload": "Yenile",
"Unmute": "Sesi aç",
"Mute": "Sessize al",
"Mark as read": "Okundu işaretle",
"Add to local contacts": "Rehbere ekle",
"Start secret chat": "Gizli sohbet başlat",
"Verify encryption key": "Şifreleme anahtarını doğrula",
"Self-destruct timer": "Kendini imha süresi",
"Delete secret chat": "Gizli sohbeti sil",
"Forwarded to %1": "%1 kişisine iletildi",
"React": "Tepki ver",
"Cancel": "İptal",
"Forward to": "Şuraya ilet",
"search chats and people": "sohbet ve kişi ara",
"not in your chats": "sohbetlerinizde yok",
"Saved": "Kaydedildi",
"File saved to: %1": "Dosya şuraya kaydedildi: %1",
"OK": "Tamam",
"Delete": "Sil",
"30 seconds": "30 saniye",
"1 minute": "1 dakika",
"1 hour": "1 saat",
"1 day": "1 gün",
"1 week": "1 hafta",
"Encryption key": "Şifreleme anahtarı",
"Close": "Kapat",
"Image": "Resim",
"File": "Dosya",
"Reply": "Yanıtla",
"Forward": "İlet",
"Edit": "Düzenle",
"Save to phone": "Telefona kaydet",
"Open": "Aç",
"Copy link": "Bağlantıyı kopyala",
"Copy text": "Metni kopyala",
"Retry": "Yeniden dene",
"Delete for me": "Bende sil",
"Delete for everyone": "Herkesten sil",
"connecting...": "bağlanıyor...",
"offline": "çevrimdışı",
"online": "çevrimiçi",
"%1 wants to start an end-to-end encrypted chat.": "%1 uçtan uca şifreli bir sohbet başlatmak istiyor.",
"Waiting for the other side to come online and accept...": "Karşı tarafın çevrimiçi olup kabul etmesi bekleniyor...",
"Accept": "Kabul et",
"Decline": "Reddet",
"Cancel request": "İsteği iptal et",
"Older messages": "Daha eski iletiler",
"Could not load the messages: %1": "İletiler yüklenemedi: %1",
"No messages yet.": "Henüz ileti yok.",
"Editing message": "İleti düzenleniyor",
"Replying to": "Yanıtlanan",
"edit the text, then tap Save": "metni düzenleyip Kaydet'e dokunun",
"channel - only its admins can post": "kanal - yalnızca yöneticileri gönderebilir",
"add a caption": "açıklama ekleyin",
"encrypted message": "şifreli ileti",
"message": "ileti",
"Save": "Kaydet",
"Send": "Gönder",
"All chats": "Tüm sohbetler",
"Archive": "Arşiv",
"Yesterday": "Dün",
"%1 is typing...": "%1 yazıyor...",
"typing...": "yazıyor...",
"You: %1": "Siz: %1",
"wants to start a secret chat": "gizli sohbet başlatmak istiyor",
"waiting to be accepted...": "kabul edilmesi bekleniyor...",
"secret chat": "gizli sohbet",
"Folders": "Klasörler",
"Connect": "Bağlan",
"Disconnect": "Bağlantıyı kes",
"Settings": "Ayarlar",
"About": "Hakkında",
"Sign out": "Oturumu kapat",
"Exit": "Çıkış",
"Sign out? The session will be ended on Telegram and removed from this phone.": "Oturum kapatılsın mı? Oturum Telegram'da sonlandırılacak ve bu telefondan kaldırılacak.",
"New chat": "Yeni sohbet",
"Find": "Bul",
"@username or +phone": "@kullanıcıadı veya +telefon",
"Clear history": "Geçmişi temizle",
"Mute all topics": "Tüm konuları sessize al",
"Unmute all topics": "Tüm konuların sesini aç",
"Block user": "Kullanıcıyı engelle",
"Mark all as read": "Tümünü okundu işaretle",
"Unarchive chat": "Sohbeti arşivden çıkar",
"Archive chat": "Sohbeti arşivle",
"Move to folder": "Klasöre taşı",
"Delete chat": "Sohbeti sil",
"Myself": "Bende",
"All": "Herkeste",
"All chats (no folder)": "Tüm sohbetler (klasörsüz)",
"tap to switch folder": "klasör değiştirmek için dokunun",
"loading...": "yükleniyor...",
"Older chats": "Daha eski sohbetler",
"Offline. Use the menu to connect.": "Çevrimdışı. Bağlanmak için menüyü kullanın.",
"Loading chats...": "Sohbetler yükleniyor...",
"The archive is empty.": "Arşiv boş.",
"No chats in this folder.": "Bu klasörde sohbet yok.",
"No chats yet. Tap + to find someone.": "Henüz sohbet yok. Birini bulmak için + düğmesine dokunun.",
"Contacts": "Rehber",
"reading the phonebook...": "rehber okunuyor...",
"%1 numbers": "%1 numara",
"search contacts": "kişi ara",
"No contacts found.": "Kişi bulunamadı.",
"Sign in with QR code": "QR kodla giriş yap",
"Sign in with phone number": "Telefon numarasıyla giriş yap",
"SOCKS5 proxy": "SOCKS5 vekil sunucu",
"Reconnect": "Yeniden bağlan",
"Enable": "Etkinleştir",
"Server": "Sunucu",
"host or IP": "adres veya IP",
"Port": "Bağlantı noktası",
"Username (optional)": "Kullanıcı adı (isteğe bağlı)",
"Password (optional)": "Parola (isteğe bağlı)",
"Telegram for Symbian": "Symbian için Telegram",
"No connection through the proxy. Check the proxy or tap Reconnect.": "Vekil sunucu üzerinden bağlantı yok. Vekil sunucuyu denetleyin veya Yeniden bağlan'a dokunun.",
"No connection. Tap Reconnect, or set up a proxy if Telegram is blocked.": "Bağlantı yok. Yeniden bağlan'a dokunun veya Telegram engelliyse vekil sunucu ayarlayın.",
"Proxy: %1": "Vekil sunucu: %1",
"on": "açık",
"Set up proxy": "Vekil sunucu ayarla",
"The code renews in %1 s": "Kod %1 sn içinde yenilenir",
"Open Telegram on a phone or PC where you are signed in: Settings > Devices > Link Desktop Device, and scan this code.": "Giriş yaptığınız bir telefonda veya bilgisayarda Telegram'ı açın: Ayarlar > Cihazlar > Masaüstü Cihaz Bağla ve bu kodu taratın.",
"Phone number": "Telefon numarası",
"+1 555 123 4567": "+90 555 123 45 67",
"Include the country code. Telegram will send a login code to this number.": "Ülke kodunu ekleyin. Telegram bu numaraya bir giriş kodu gönderecek.",
"requesting...": "isteniyor...",
"send code": "kod gönder",
"Use QR code instead": "Bunun yerine QR kod kullan",
"Enter the code sent to %1": "%1 numarasına gönderilen kodu girin",
"code": "kod",
"signing in...": "giriş yapılıyor...",
"sign in": "giriş yap",
"Resend code": "Kodu yeniden gönder",
"Change number": "Numarayı değiştir",
"Two-step verification password": "İki adımlı doğrulama parolası",
"hint: %1": "ipucu: %1",
"password": "parola",
"show password": "parolayı göster",
"checking...": "denetleniyor...",
"Symbigram talks MTProto 2.0 straight to Telegram's servers: the encryption key is made on this phone and never leaves it. The session shows up under Devices in Telegram, where it can be ended at any time.": "Symbigram, Telegram sunucularıyla doğrudan MTProto 2.0 konuşur: şifreleme anahtarı bu telefonda oluşturulur ve telefondan asla çıkmaz. Oturum, Telegram'da Cihazlar altında görünür ve istediğiniz zaman sonlandırılabilir.",
"Forwarded from %1": "%1 kişisinden iletildi",
"Tap to load": "Yüklemek için dokunun",
"Failed - tap to retry": "Başarısız - yeniden denemek için dokunun",
"Voice message": "Sesli ileti",
"Video": "Video",
"playing... tap to stop": "çalıyor... durdurmak için dokunun",
"loading %1%": "yükleniyor %1%",
"tap to play": "çalmak için dokunun",
"buffering %1%... opening player": "arabelleğe alınıyor %1%... oynatıcı açılıyor",
"tap to play in player": "oynatıcıda çalmak için dokunun",
"tap to open": "açmak için dokunun",
"downloading %1%": "indiriliyor %1%",
"tap to download": "indirmek için dokunun",
"GIF file": "GIF dosyası",
"not supported": "desteklenmiyor",
"edited": "düzenlendi",
"Today": "Bugün",
"Can't forward to a secret chat.": "Gizli sohbete iletilemez.",
"Could not save the file to %1": "Dosya %1 konumuna kaydedilemedi",
"Could not open the file.": "Dosya açılamadı.",
"Could not play this audio: %1": "Bu ses çalınamadı: %1",
"last seen at %1": "son görülme %1",
"last seen yesterday at %1": "son görülme dün %1",
"last seen %1": "son görülme %1",
"last seen recently": "son görülme yakın zamanda",
"last seen within a week": "son görülme bir hafta içinde",
"last seen within a month": "son görülme bir ay içinde",
"last seen a long time ago": "son görülme uzun zaman önce",
"end-to-end encrypted, self-destruct %1s": "uçtan uca şifreli, kendini imha %1sn",
"end-to-end encrypted": "uçtan uca şifreli",
"bot": "bot",
"Saved Messages": "Kaydedilenler",
"channel, %1 subscribers": "kanal, %1 abone",
"channel": "kanal",
"%1 members": "%1 üye",
"group": "grup",
"reply": "yanıt",
"You": "Siz",
"photo": "fotoğraf",
"The message was not sent: %1": "İleti gönderilemedi: %1",
"key exchange failed: %1": "anahtar değişimi başarısız: %1",
"no response from the server": "sunucudan yanıt yok",
"the proxy refused our authentication method": "vekil sunucu kimlik doğrulama yöntemimizi reddetti",
"proxy authentication failed - check the username and password": "vekil sunucu kimlik doğrulaması başarısız - kullanıcı adını ve parolayı denetleyin",
"the proxy sent a malformed reply": "vekil sunucu bozuk bir yanıt gönderdi",
"the proxy could not reach the server (%1)": "vekil sunucu sunucuya ulaşamadı (%1)",
"connection closed": "bağlantı kapandı",
"connection timed out": "bağlantı zaman aşımına uğradı",
"New contact": "Yeni kişi",
"First name": "Ad",
"Last name": "Soyad",
"Phone (optional)": "Telefon (isteğe bağlı)",
"Web address": "Web adresi",
"Keeping the t.me web address lets Symbigram open this chat from Contacts even without a phone number. Any other details can be added afterwards in the phone's Contacts application.": "t.me web adresini saklamak, Symbigram'ın bu sohbeti telefon numarası olmadan da Rehber'den açmasını sağlar. Diğer ayrıntılar daha sonra telefonun Rehber uygulamasında eklenebilir.",
"Popup for new messages": "Yeni iletiler için açılır pencere",
"Sound": "Ses",
"Vibration": "Titreşim",
"Sound volume": "Ses düzeyi",
"Vibration length": "Titreşim süresi",
"Notifications": "Bildirimler",
"Groups and channels": "Gruplar ve kanallar",
"Also alert for messages in groups and channels. Chats muted in Telegram stay quiet. Symbigram stays connected in the background either way.": "Gruplardaki ve kanallardaki iletiler için de uyar. Telegram'da sessize alınan sohbetler sessiz kalır. Symbigram her durumda arka planda bağlı kalır.",
"Symbigram: new message": "Symbigram: yeni ileti",
"Symbigram: %1 new messages": "Symbigram: %1 yeni ileti",
"Nothing to save.": "Kaydedilecek bir şey yok.",
"Could not open the phonebook (%1).": "Rehber açılamadı (%1).",
"Could not save the contact (%1).": "Kişi kaydedilemedi (%1).",
"The phone's address book is only available on the device.": "Telefon rehberi yalnızca cihazda kullanılabilir.",
"Could not read the phonebook (%1).": "Rehber okunamadı (%1).",
"No contacts with a phone number.": "Telefon numarası olan kişi yok.",
"Clear cache": "Önbelleği temizle",
"Delete the %1 of downloaded media held on the phone? It will be fetched again when needed.": "Telefonda tutulan %1 indirilmiş medya silinsin mi? Gerektiğinde yeniden indirilecek.",
"Clear": "Temizle",
"App language": "Uygulama dili",
"System default": "Sistem varsayılanı",
"Save downloads to": "İndirilenleri şuraya kaydet",
"Choose folder...": "Klasör seç...",
"Image preview": "Resim önizlemesi",
"Font size": "Yazı tipi boyutu",
"Popup: %1, Sound: %2, Vibration: %3": "Açılır pencere: %1, Ses: %2, Titreşim: %3",
"Popup, sound and vibration for messages that arrive while another application is in front.": "Başka bir uygulama öndeyken gelen iletiler için açılır pencere, ses ve titreşim.",
"Connect on start": "Açılışta bağlan",
"Proxy server": "Vekil sunucu",
"not set": "ayarlanmadı",
"Route the connection through a SOCKS5 proxy. Changing it reconnects.": "Bağlantıyı bir SOCKS5 vekil sunucu üzerinden geçirin. Değiştirmek yeniden bağlanmaya yol açar.",
"The size of the message text in chats. Small is the original size.": "Sohbetlerdeki ileti metninin boyutu. Küçük, özgün boyuttur.",
"Thumbnail shows a small blurred preview until you tap a photo to load it (saves data). Full loads photo previews automatically. Neither changes what Save downloads.": "Küçük resim, siz bir fotoğrafa dokunup yükleyene kadar küçük ve bulanık bir önizleme gösterir (veri tasarrufu sağlar). Tam, fotoğraf önizlemelerini otomatik yükler. Hiçbiri Kaydet'in ne indirdiğini değiştirmez.",
"Downloaded media held on the phone: %1": "Telefonda tutulan indirilmiş medya: %1",
"The app's private store of downloaded photos, avatars and files (separate from the folder above). Clearing it just re-downloads on demand.": "Uygulamanın indirilen fotoğraflar, profil resimleri ve dosyalar için özel deposu (yukarıdaki klasörden ayrıdır). Temizlemek, gerektiğinde yeniden indirilmesine yol açar.",
"Keep a log": "Günlük tut",
"Off by default. Turn it on only to collect a diagnostic log (shown on the About page) when something goes wrong.": "Varsayılan olarak kapalı. Yalnızca bir şeyler ters gittiğinde tanılama günlüğü toplamak için açın (Hakkında sayfasında gösterilir).",
"Takes effect after the app is restarted.": "Uygulama yeniden başlatıldığında etkili olur.",
"Signed out.": "Oturum kapatıldı.",
"Enter a valid phone number, with the country code.": "Ülke koduyla geçerli bir telefon numarası girin.",
"Enter a username, a phone number or a name.": "Bir kullanıcı adı, telefon numarası veya ad girin.",
"That folder no longer exists.": "Bu klasör artık yok.",
"This account has no password set.": "Bu hesapta parola ayarlanmamış.",
"Unsupported password method.": "Desteklenmeyen parola yöntemi.",
"No Telegram account uses this number. Sign-up isn't supported here.": "Bu numarayı kullanan bir Telegram hesabı yok. Burada kayıt desteklenmiyor.",
"User blocked.": "Kullanıcı engellendi.",
"the server rejected a part of the file": "sunucu dosyanın bir parçasını reddetti",
"the file is served from a CDN, which is not supported": "dosya desteklenmeyen bir CDN üzerinden sunuluyor",
"unexpected reply": "beklenmeyen yanıt",
"could not write the file": "dosya yazılamadı",
"Nobody found.": "Kimse bulunamadı.",
"The session was ended (%1). Please sign in again.": "Oturum sonlandırıldı (%1). Lütfen yeniden giriş yapın.",
"Wrong password.": "Yanlış parola.",
"Too many attempts. Wait %1 seconds.": "Çok fazla deneme. %1 saniye bekleyin.",
"That phone number is not valid.": "Bu telefon numarası geçerli değil.",
"That phone number is banned from Telegram.": "Bu telefon numarası Telegram'da yasaklı.",
"Too many codes requested for this number. Try again later.": "Bu numara için çok fazla kod istendi. Daha sonra yeniden deneyin.",
"Too many attempts. Try again later.": "Çok fazla deneme. Daha sonra yeniden deneyin.",
"This build's Telegram API key was rejected.": "Bu sürümün Telegram API anahtarı reddedildi.",
"Wrong code. Check it and try again.": "Yanlış kod. Denetleyip yeniden deneyin.",
"The code expired. Request a new one.": "Kodun süresi doldu. Yenisini isteyin.",
"Could not load the chat list: %1": "Sohbet listesi yüklenemedi: %1",
"Could not start the secret chat: %1": "Gizli sohbet başlatılamadı: %1",
"Could not accept the secret chat: %1": "Gizli sohbet kabul edilemedi: %1",
"Could not edit the message: %1": "İleti düzenlenemedi: %1",
"Could not forward the message: %1": "İleti iletilemedi: %1",
"That reaction is not allowed in this chat.": "Bu sohbette bu tepkiye izin verilmiyor.",
"Could not react: %1": "Tepki verilemedi: %1",
"Could not block the user: %1": "Kullanıcı engellenemedi: %1",
"That folder must keep at least one chat, so the chat stays in it too.": "Bu klasörde en az bir sohbet kalmalı, bu yüzden sohbet klasörde de kalır.",
"Could not change the folder: %1": "Klasör değiştirilemedi: %1",
"could not create the file": "dosya oluşturulamadı",
"the file is empty": "dosya boş",
"could not read the file": "dosya okunamadı",
"the file is too large": "dosya çok büyük",
"could not read the recording": "kayıt okunamadı",
"Secret chats can only be opened with a person.": "Gizli sohbet yalnızca bir kişiyle açılabilir.",
"The secret chat is not ready.": "Gizli sohbet hazır değil.",
"user %1": "kullanıcı %1",
"chat %1": "sohbet %1",
"deleted account": "silinmiş hesap",
"video": "video",
"location %1, %2": "konum %1, %2",
"location": "konum",
"location: %1": "konum: %1",
"contact: %1 %2 %3": "kişi: %1 %2 %3",
"poll: %1": "anket: %1",
"dice: %1": "zar: %1",
"game": "oyun",
"invoice": "fatura",
"story": "hikâye",
"file": "dosya",
"sticker": "çıkartma",
"sticker %1": "çıkartma %1",
"voice message %1": "sesli ileti %1",
"voice message": "sesli ileti",
"video message %1": "video ileti %1",
"video message": "video ileti",
"GIF": "GIF",
"video %1": "video %1",
"audio %1": "ses %1",
"audio": "ses",
"image": "resim",
"file: %1 (%2)": "dosya: %1 (%2)",
"unsupported attachment": "desteklenmeyen ek",
"attachment": "ek",
"added %1": "%1 eklendi",
"removed %1": "%1 çıkarıldı",
"joined by invite link": "davet bağlantısıyla katıldı",
"pinned a message": "bir iletiyi sabitledi",
"joined Telegram": "Telegram'a katıldı",
"cleared the history": "geçmişi temizledi",
"service message": "hizmet iletisi",
"empty message": "boş ileti",
"Folder": "Klasör",
"No topics.": "Konu yok.",
"Reload topics": "Konuları yenile",
"Unmute topic": "Konunun sesini aç",
"Mute topic": "Konuyu sessize al",
"loading topics...": "konular yükleniyor...",
"%1 topics": "%1 konu",
"[closed] ": "[kapalı] ",
"could not open the voice file": "ses dosyası açılamadı",
"could not decode the voice message": "sesli ileti çözülemedi",
"audio is unavailable (%1)": "ses kullanılamıyor (%1)",
"could not open audio (%1)": "ses açılamadı (%1)",
"could not prepare playback": "oynatma hazırlanamadı",
"could not start playback (%1)": "oynatma başlatılamadı (%1)",
"could not play (%1)": "çalınamadı (%1)",
"the microphone is unavailable (%1)": "mikrofon kullanılamıyor (%1)",
"could not open the microphone (%1)": "mikrofon açılamadı (%1)",
"recording is only available on the phone": "kayıt yalnızca telefonda kullanılabilir",
"the recording was too short": "kayıt çok kısaydı",
"could not encode the recording": "kayıt kodlanamadı",
"could not save the recording": "kayıt kaydedilemedi",
"could not start recording (%1)": "kayıt başlatılamadı (%1)",
"Logging is off. Turn on \"Keep a log\" in Settings to collect one.": "Günlük kapalı. Toplamak için Ayarlar'da \"Günlük tut\" seçeneğini açın.",
"End this secret chat? Its messages, which live only on this device, will be removed here.": "Bu gizli sohbet sonlandırılsın mı? Yalnızca bu cihazda bulunan iletileri buradan kaldırılacak.",
"If this key matches on both phones, no one is intercepting the chat. Compare it with %1 in person or over a trusted channel.": "Bu anahtar iki telefonda da aynıysa sohbeti kimse dinlemiyordur. %1 ile yüz yüze veya güvendiğiniz bir kanaldan karşılaştırın.",
"@username, phone number, t.me link, or a contact's name": "@kullanıcıadı, telefon numarası, t.me bağlantısı veya bir kişinin adı",
"Delete all messages of \"%1\" on Telegram (for you)?": "\"%1\" sohbetinin tüm iletileri Telegram'da (sizin için) silinsin mi?",
"Delete the chat \"%1\"? \"All\" also removes it for the other side.": "\"%1\" sohbeti silinsin mi? \"Herkeste\" seçeneği karşı taraftan da siler.",
"End the secret chat with \"%1\"? Its messages live only on this device and will be removed here.": "\"%1\" ile gizli sohbet sonlandırılsın mı? İletileri yalnızca bu cihazda bulunur ve buradan kaldırılır.",
"For messages that arrive while another application is in front. Each channel: Off, only the first new message, or every message. At Low volume the sound is the system popup tone, so it needs a popup to show; Medium and Loud play their own tone either way.": "Başka bir uygulama öndeyken gelen iletiler için. Her kanal: Kapalı, yalnızca ilk yeni ileti veya her ileti. Düşük ses düzeyinde ses, sistemin açılır pencere tonudur ve duyulması için açılır pencerenin görünmesi gerekir; Orta ve Yüksek her durumda kendi tonunu çalar.",
"Saved photos and files go here. Pick a drive, or \"Choose folder...\" for any folder.": "Kaydedilen fotoğraflar ve dosyalar buraya gider. Bir sürücü seçin veya herhangi bir klasör için \"Klasör seç...\" kullanın.",
"created the group \"%1\"": "\"%1\" grubunu oluşturdu",
"created the channel \"%1\"": "\"%1\" kanalını oluşturdu",
}
