# -*- coding: utf-8 -*-
# Vietnamese strings for the Symbigram language add-on.
#
# Source text -> Vietnamese. Anything not listed here stays English, which is the intended fallback:
# when the application gains new strings this file can lag behind without breaking anything.
# Rebuild the pack with build.cmd in this folder after changing it.
#
# Moved out of tools/translate.py when Vietnamese became an add-on, so this is now the only copy.
TABLE = {
'version %1': 'phiên bản %1',
'A Telegram client for Symbian Anna/Belle, ported from Lumigram/LumigramPlus for Windows Phone 8.1. It speaks MTProto 2.0 directly to Telegram - no bridge, no proxy; the encryption key is made on the phone.': 'Một ứng dụng Telegram cho Symbian Anna/Belle, được chuyển từ Lumigram/LumigramPlus cho Windows Phone 8.1. Nó giao tiếp MTProto 2.0 trực tiếp với Telegram — không cầu nối, không proxy; khóa mã hóa được tạo trên điện thoại.',
'Sign-in is by QR code only (scan from a signed-in Telegram, plus the two-step password if set). Text messages, photos and files (view, save and send), groups and channels.': 'Chỉ đăng nhập bằng mã QR (quét từ một Telegram đã đăng nhập, kèm mật khẩu hai bước nếu có). Tin nhắn văn bản, ảnh và tệp (xem, lưu và gửi), nhóm và kênh.',
'Log': 'Nhật ký',
'Copy log': 'Sao chép nhật ký',
'Not connected.': 'Chưa kết nối.',
'Connecting...': 'Đang kết nối...',
'Connecting and creating the encryption key...': 'Đang kết nối và tạo khóa mã hóa...',
'Checking the password (this takes a few seconds)...': 'Đang kiểm tra mật khẩu (mất vài giây)...',
'This account has two-step verification. Enter the password.': 'Tài khoản này có xác minh hai bước. Nhập mật khẩu.',
'Requesting a sign-in code...': 'Đang yêu cầu mã đăng nhập...',
'Waiting for the code to be scanned...': 'Đang chờ mã được quét...',
'Signing in...': 'Đang đăng nhập...',
'Connection lost: %1. Reconnecting...': 'Mất kết nối: %1. Đang kết nối lại...',
'Connection failed: %1. Retrying...': 'Kết nối thất bại: %1. Đang thử lại...',
'Enter the password.': 'Nhập mật khẩu.',
'Copied.': 'Đã sao chép.',
'Load older messages': 'Tải tin nhắn cũ hơn',
'Reload': 'Tải lại',
'Unmute': 'Bật tiếng',
'Mute': 'Tắt tiếng',
'Mark as read': 'Đánh dấu đã đọc',
'Copy text': 'Sao chép văn bản',
'Reply': 'Trả lời',
'Replying to': 'Đang trả lời',
'Edit': 'Sửa',
'Editing message': 'Đang sửa tin nhắn',
'edit the text, then tap Save': 'sửa văn bản, rồi nhấn Lưu',
'Save': 'Lưu',
'Could not edit the message: %1': 'Không thể sửa tin nhắn: %1',
'Retry': 'Thử lại',
'Delete for me': 'Xóa ở phía tôi',
'Delete for everyone': 'Xóa ở mọi phía',
'connecting...': 'đang kết nối...',
'offline': 'ngoại tuyến',
'online': 'trực tuyến',
'Older messages': 'Tin nhắn cũ hơn',
'Could not load the messages: %1': 'Không thể tải tin nhắn: %1',
'No messages yet.': 'Chưa có tin nhắn.',
'channel - only its admins can post': 'kênh — chỉ quản trị viên mới đăng được',
'message': 'tin nhắn',
'Send': 'Gửi',
'Yesterday': 'Hôm qua',
'%1 is typing...': '%1 đang nhập...',
'typing...': 'đang nhập...',
'You: %1': 'Bạn: %1',
'Connect': 'Kết nối',
'Disconnect': 'Ngắt kết nối',
'Settings': 'Cài đặt',
'About': 'Giới thiệu',
'Sign out': 'Đăng xuất',
'Exit': 'Thoát',
'Sign out? The session will be ended on Telegram and removed from this phone.': 'Đăng xuất? Phiên sẽ bị kết thúc trên Telegram và xóa khỏi điện thoại này.',
'Cancel': 'Hủy',
'New chat': 'Trò chuyện mới',
'Find': 'Tìm',
"@username, phone number, t.me link, or a contact's name": '@tên_người_dùng, số điện thoại, liên kết t.me, hoặc tên một liên hệ',
'@username or +phone': '@tên_người_dùng hoặc +số',
'Clear history': 'Xóa lịch sử',
'Delete all messages of "%1" on Telegram (for you)?': 'Xóa tất cả tin nhắn của «%1» trên Telegram (ở phía bạn)?',
'Delete': 'Xóa',
'loading...': 'đang tải...',
'Older chats': 'Trò chuyện cũ hơn',
'Loading chats...': 'Đang tải các cuộc trò chuyện...',
'No chats yet. Tap + to find someone.': 'Chưa có cuộc trò chuyện nào. Nhấn + để tìm ai đó.',
'Offline. Use the menu to connect.': 'Ngoại tuyến. Dùng menu để kết nối.',
'Telegram for Symbian': 'Telegram cho Symbian',
'No connection. Tap the refresh button to try again.': 'Không có kết nối. Nhấn nút làm mới để thử lại.',
'The code renews in %1 s': 'Mã sẽ làm mới sau %1 giây',
'Open Telegram on a phone or PC where you are signed in: Settings > Devices > Link Desktop Device, and scan this code.': 'Mở Telegram trên điện thoại hoặc PC nơi bạn đã đăng nhập: Cài đặt > Thiết bị > Liên kết thiết bị máy tính, và quét mã này.',
'Two-step verification password': 'Mật khẩu xác minh hai bước',
'hint: %1': 'gợi ý: %1',
'password': 'mật khẩu',
'show password': 'hiện mật khẩu',
'checking...': 'đang kiểm tra...',
'sign in': 'đăng nhập',
"Symbigram talks MTProto 2.0 straight to Telegram's servers: the encryption key is made on this phone and never leaves it. The session shows up under Devices in Telegram, where it can be ended at any time.": 'Symbigram giao tiếp MTProto 2.0 trực tiếp với máy chủ của Telegram: khóa mã hóa được tạo trên điện thoại này và không bao giờ rời khỏi nó. Phiên hiển thị trong mục Thiết bị trên Telegram, nơi có thể kết thúc bất cứ lúc nào.',
'Forwarded from %1': 'Chuyển tiếp từ %1',
'edited': 'đã sửa',
'Today': 'Hôm nay',
'reply': 'trả lời',
'You': 'Bạn',
'last seen at %1': 'hoạt động lần cuối lúc %1',
'last seen yesterday at %1': 'hoạt động lần cuối hôm qua lúc %1',
'last seen %1': 'hoạt động lần cuối %1',
'last seen recently': 'hoạt động gần đây',
'last seen within a week': 'hoạt động trong tuần qua',
'last seen within a month': 'hoạt động trong tháng qua',
'last seen a long time ago': 'hoạt động đã lâu',
'bot': 'bot',
'Saved Messages': 'Tin nhắn đã lưu',
'channel, %1 subscribers': 'kênh, %1 người đăng ký',
'channel': 'kênh',
'%1 members': '%1 thành viên',
'group': 'nhóm',
'The message was not sent: %1': 'Tin nhắn chưa được gửi: %1',
'key exchange failed: %1': 'trao đổi khóa thất bại: %1',
'no response from the server': 'máy chủ không phản hồi',
'connection closed': 'kết nối đã đóng',
'connection timed out': 'kết nối quá thời gian chờ',
'Symbigram: new message': 'Symbigram: tin nhắn mới',
'Symbigram: %1 new messages': 'Symbigram: %1 tin nhắn mới',
'App language': 'Ngôn ngữ ứng dụng',
'System default': 'Theo hệ thống',
'Notifications': 'Thông báo',
'Popup for new messages': 'Cửa sổ bật lên cho tin nhắn mới',
'Vibrate': 'Rung',
'Groups and channels': 'Nhóm và kênh',
'For messages that arrive while another application is in front: the "new messages" dialog, the popup and the vibration. Chats muted in Telegram stay quiet. Symbigram stays connected in the background either way.': 'Đối với tin nhắn đến khi một ứng dụng khác đang hiển thị: hộp thoại «tin nhắn mới», cửa sổ bật lên và rung. Các cuộc trò chuyện đã tắt tiếng trong Telegram vẫn im lặng. Dù thế nào Symbigram vẫn giữ kết nối ở chế độ nền.',
'Connect on start': 'Kết nối khi khởi động',
'Takes effect after the app is restarted.': 'Có hiệu lực sau khi khởi động lại ứng dụng.',
'Signed out.': 'Đã đăng xuất.',
'Enter a username, a phone number or a name.': 'Nhập tên người dùng, số điện thoại hoặc tên.',
'This account has no password set.': 'Tài khoản này chưa đặt mật khẩu.',
'Unsupported password method.': 'Phương thức mật khẩu không được hỗ trợ.',
'Nobody found.': 'Không tìm thấy ai.',
'The session was ended (%1). Please sign in again.': 'Phiên đã kết thúc (%1). Vui lòng đăng nhập lại.',
'Wrong password.': 'Sai mật khẩu.',
'Too many attempts. Wait %1 seconds.': 'Quá nhiều lần thử. Chờ %1 giây.',
'Could not load the chat list: %1': 'Không thể tải danh sách trò chuyện: %1',
'user %1': 'người dùng %1',
'chat %1': 'cuộc trò chuyện %1',
'deleted account': 'tài khoản đã xóa',
'video': 'video',
'photo': 'ảnh',
'location %1, %2': 'vị trí %1, %2',
'location': 'vị trí',
'location: %1': 'vị trí: %1',
'contact: %1 %2 %3': 'liên hệ: %1 %2 %3',
'poll: %1': 'khảo sát: %1',
'dice: %1': 'xúc xắc: %1',
'game': 'trò chơi',
'invoice': 'hóa đơn',
'story': 'tin',
'file': 'tệp',
'sticker': 'nhãn dán',
'sticker %1': 'nhãn dán %1',
'voice message %1': 'tin nhắn thoại %1',
'voice message': 'tin nhắn thoại',
'video message %1': 'tin nhắn video %1',
'video message': 'tin nhắn video',
'GIF': 'GIF',
'video %1': 'video %1',
'audio %1': 'âm thanh %1',
'audio': 'âm thanh',
'image': 'hình ảnh',
'%1 MB': '%1 MB',
'%1 KB': '%1 KB',
'%1 B': '%1 B',
'file: %1 (%2)': 'tệp: %1 (%2)',
'unsupported attachment': 'tệp đính kèm không được hỗ trợ',
'attachment': 'tệp đính kèm',
'created the group "%1"': 'đã tạo nhóm «%1»',
'created the channel "%1"': 'đã tạo kênh «%1»',
'added %1': 'đã thêm %1',
'removed %1': 'đã xóa %1',
'joined by invite link': 'đã tham gia qua liên kết mời',
'pinned a message': 'đã ghim một tin nhắn',
'joined Telegram': 'đã tham gia Telegram',
'cleared the history': 'đã xóa lịch sử',
'service message': 'tin nhắn dịch vụ',
'empty message': 'tin nhắn trống',
'Folders': 'Thư mục',
'Folder': 'Thư mục',
'All chats': 'Tất cả trò chuyện',
'Archive': 'Lưu trữ',
'tap to switch folder': 'nhấn để chuyển thư mục',
'The archive is empty.': 'Kho lưu trữ trống.',
'No chats in this folder.': 'Không có cuộc trò chuyện nào trong thư mục này.',
'Keep a log': 'Ghi nhật ký',
'Off by default. Turn it on only to collect a diagnostic log (shown on the About page) when something goes wrong.': 'Mặc định tắt. Chỉ bật để thu thập nhật ký chẩn đoán (hiển thị ở trang «Giới thiệu») khi có sự cố.',
'Logging is off. Turn on "Keep a log" in Settings to collect one.': 'Ghi nhật ký đang tắt. Bật «Ghi nhật ký» trong Cài đặt để thu thập.',
'Images (*.jpg *.jpeg *.png *.gif *.bmp)': 'Hình ảnh (*.jpg *.jpeg *.png *.gif *.bmp)',
'All files (*)': 'Tất cả tệp (*)',
'Choose an image': 'Chọn một hình ảnh',
'Send image': 'Gửi hình ảnh',
'Send file': 'Gửi tệp',
'Caption (optional)': 'Chú thích (tùy chọn)',
'add a caption': 'thêm chú thích',
'Choose a file': 'Chọn một tệp',
'Sending the image...': 'Đang gửi hình ảnh...',
'Sending the file...': 'Đang gửi tệp...',
'Image': 'Hình ảnh',
'File': 'Tệp',
'Save to phone': 'Lưu vào điện thoại',
'Open': 'Mở',
'Close': 'Đóng',
'Tap to load': 'Nhấn để tải',
'Failed - tap to retry': 'Thất bại — nhấn để thử lại',
'Voice message': 'Tin nhắn thoại',
'Video': 'Video',
'tap to open': 'nhấn để mở',
'downloading %1%': 'đang tải %1%',
'tap to download': 'nhấn để tải xuống',
'Saved to %1': 'Đã lưu vào %1',
'Could not save the file.': 'Không thể lưu tệp.',
'the server rejected a part of the file': 'máy chủ đã từ chối một phần của tệp',
'the file is served from a CDN, which is not supported': 'tệp được phục vụ từ CDN, điều này không được hỗ trợ',
'unexpected reply': 'phản hồi không mong đợi',
'could not write the file': 'không thể ghi tệp',
'could not create the file': 'không thể tạo tệp',
'the file is empty': 'tệp trống',
'could not read the file': 'không thể đọc tệp',
'the file is too large': 'tệp quá lớn',
'Start secret chat': 'Bắt đầu trò chuyện bí mật',
'Verify encryption key': 'Xác minh khóa mã hóa',
'Self-destruct timer': 'Hẹn giờ tự hủy',
'Delete secret chat': 'Xóa trò chuyện bí mật',
'End this secret chat? Its messages, which live only on this device, will be removed here.': 'Kết thúc trò chuyện bí mật này? Các tin nhắn của nó, chỉ tồn tại trên thiết bị này, sẽ bị xóa tại đây.',
'Encryption key': 'Khóa mã hóa',
'If this key matches on both phones, no one is intercepting the chat. Compare it with %1 in person or over a trusted channel.': 'Nếu khóa này khớp trên cả hai điện thoại, không ai đang chặn cuộc trò chuyện. So sánh nó với %1 trực tiếp hoặc qua một kênh đáng tin cậy.',
'%1 wants to start an end-to-end encrypted chat.': '%1 muốn bắt đầu một cuộc trò chuyện mã hóa đầu cuối.',
'Waiting for the other side to come online and accept...': 'Đang chờ phía bên kia trực tuyến và chấp nhận...',
'Decline': 'Từ chối',
'Cancel request': 'Hủy yêu cầu',
'encrypted message': 'tin nhắn được mã hóa',
'secret chat': 'trò chuyện bí mật',
'wants to start a secret chat': 'muốn bắt đầu trò chuyện bí mật',
'waiting to be accepted...': 'đang chờ được chấp nhận...',
'end-to-end encrypted': 'mã hóa đầu cuối',
'end-to-end encrypted, self-destruct %1s': 'mã hóa đầu cuối, tự hủy %1 giây',
'Secret chats can only be opened with a person.': 'Chỉ có thể mở trò chuyện bí mật với một người.',
'The secret chat is not ready.': 'Trò chuyện bí mật chưa sẵn sàng.',
'Secret chats can only be started with a person.': 'Chỉ có thể bắt đầu trò chuyện bí mật với một người.',
'Starting a secret chat...': 'Đang bắt đầu trò chuyện bí mật...',
'Someone wants to start a secret chat.': 'Ai đó muốn bắt đầu trò chuyện bí mật.',
'%1 wants to start a secret chat.': '%1 muốn bắt đầu trò chuyện bí mật.',
'Secret chat is ready.': 'Trò chuyện bí mật đã sẵn sàng.',
'Secret chat': 'Trò chuyện bí mật',
'Encrypted message': 'Tin nhắn được mã hóa',
'Could not start the secret chat: %1': 'Không thể bắt đầu trò chuyện bí mật: %1',
'Could not accept the secret chat: %1': 'Không thể chấp nhận trò chuyện bí mật: %1',
'Accept': 'Chấp nhận',
'Off': 'Tắt',
'5 seconds': '5 giây',
'30 seconds': '30 giây',
'1 minute': '1 phút',
'1 hour': '1 giờ',
'1 day': '1 ngày',
'1 week': '1 tuần',
'Saved': 'Đã lưu',
'File saved to: %1': 'Đã lưu tệp vào: %1',
'Could not save the file to %1': 'Không thể lưu tệp vào %1',
'Could not open the file.': 'Không thể mở tệp.',
'Phone memory': 'Bộ nhớ điện thoại',
'Mass memory': 'Bộ nhớ lớn',
'Memory card': 'Thẻ nhớ',
'Save downloads to': 'Lưu tải xuống vào',
'Clear cache': 'Xóa bộ nhớ đệm',
'Clear': 'Xóa',
'Downloaded media held on the phone: %1': 'Nội dung đã tải lưu trên điện thoại: %1',
"The app's private store of downloaded photos, avatars and files (separate from the folder above). Clearing it just re-downloads on demand.": 'Kho lưu trữ riêng của ứng dụng chứa ảnh, ảnh đại diện và tệp đã tải (tách biệt với thư mục ở trên). Xóa nó chỉ khiến chúng được tải lại khi cần.',
'Delete the %1 of downloaded media held on the phone? It will be fetched again when needed.': 'Xóa %1 nội dung đã tải lưu trên điện thoại? Nó sẽ được tải lại khi cần.',
'Cache cleared (%1 freed).': 'Đã xóa bộ nhớ đệm (giải phóng %1).',
'Choose folder...': 'Chọn thư mục...',
'Choose download folder': 'Chọn thư mục tải xuống',
'SOCKS5 proxy': 'Proxy SOCKS5',
'Proxy server': 'Máy chủ proxy',
'not set': 'chưa đặt',
'Route the connection through a SOCKS5 proxy. Changing it reconnects.': 'Định tuyến kết nối qua proxy SOCKS5. Thay đổi sẽ kết nối lại.',
'Server': 'Máy chủ',
'host or IP': 'máy chủ hoặc IP',
'Port': 'Cổng',
'Username (optional)': 'Tên người dùng (tùy chọn)',
'Password (optional)': 'Mật khẩu (tùy chọn)',
'Reconnect': 'Kết nối lại',
'Enable': 'Bật',
'Set up proxy': 'Thiết lập proxy',
'Cannot record a voice message here.': 'Không thể ghi âm tin nhắn thoại ở đây.',
'Sending the voice message...': 'Đang gửi tin nhắn thoại...',
'the microphone is unavailable (%1)': 'micrô không khả dụng (%1)',
'could not open the microphone (%1)': 'không thể mở micrô (%1)',
'could not start recording (%1)': 'không thể bắt đầu ghi âm (%1)',
'the recording was too short': 'bản ghi quá ngắn',
'could not encode the recording': 'không thể mã hóa bản ghi',
'could not save the recording': 'không thể lưu bản ghi',
'could not read the recording': 'không thể đọc bản ghi',
'Archive chat': 'Lưu trữ cuộc trò chuyện',
'Unarchive chat': 'Bỏ lưu trữ cuộc trò chuyện',
'Move to folder': 'Chuyển đến thư mục',
'All chats (no folder)': 'Tất cả trò chuyện (không thư mục)',
'Sign in with QR code': 'Đăng nhập bằng mã QR',
'Sign in with phone number': 'Đăng nhập bằng số điện thoại',
'Use QR code instead': 'Dùng mã QR thay thế',
'Phone number': 'Số điện thoại',
'Include the country code. Telegram will send a login code to this number.': 'Bao gồm mã quốc gia. Telegram sẽ gửi mã đăng nhập đến số này.',
'requesting...': 'đang yêu cầu...',
'send code': 'gửi mã',
'Enter the code sent to %1': 'Nhập mã đã gửi đến %1',
'code': 'mã',
'signing in...': 'đang đăng nhập...',
'Resend code': 'Gửi lại mã',
'Change number': 'Đổi số',
'Enter your phone number.': 'Nhập số điện thoại của bạn.',
'Enter the code.': 'Nhập mã.',
'Enter the code Telegram sent to %1.': 'Nhập mã mà Telegram đã gửi đến %1.',
'Requesting a code...': 'Đang yêu cầu mã...',
'Enter your phone number, with the country code, to get a code.': 'Nhập số điện thoại của bạn, kèm mã quốc gia, để nhận mã.',
'Enter a valid phone number, with the country code.': 'Nhập một số điện thoại hợp lệ, kèm mã quốc gia.',
"No Telegram account uses this number. Sign-up isn't supported here.": 'Không có tài khoản Telegram nào dùng số này. Đăng ký không được hỗ trợ ở đây.',
'That phone number is not valid.': 'Số điện thoại đó không hợp lệ.',
'That phone number is banned from Telegram.': 'Số điện thoại đó bị cấm khỏi Telegram.',
'Too many codes requested for this number. Try again later.': 'Đã yêu cầu quá nhiều mã cho số này. Thử lại sau.',
'Too many attempts. Try again later.': 'Quá nhiều lần thử. Thử lại sau.',
"This build's Telegram API key was rejected.": 'Khóa API Telegram của bản dựng này bị từ chối.',
'Wrong code. Check it and try again.': 'Sai mã. Kiểm tra và thử lại.',
'The code expired. Request a new one.': 'Mã đã hết hạn. Yêu cầu mã mới.',
'Delete chat': 'Xóa cuộc trò chuyện',
'Myself': 'Chính tôi',
'All': 'Tất cả',
'Delete for all': 'Xóa ở mọi phía',
'Delete the chat "%1"? "All" also removes it for the other side.': 'Xóa cuộc trò chuyện «%1»? «Tất cả» cũng xóa nó ở phía bên kia.',
'Could not change the folder: %1': 'Không thể đổi thư mục: %1',
'That folder must keep at least one chat, so the chat stays in it too.': 'Thư mục đó phải giữ ít nhất một cuộc trò chuyện, nên cuộc trò chuyện vẫn ở trong đó.',
'That folder no longer exists.': 'Thư mục đó không còn tồn tại.',
'the proxy refused our authentication method': 'proxy đã từ chối phương thức xác thực của chúng tôi',
'proxy authentication failed - check the username and password': 'xác thực proxy thất bại — kiểm tra tên người dùng và mật khẩu',
'the proxy sent a malformed reply': 'proxy đã gửi phản hồi không hợp lệ',
'the proxy could not reach the server (%1)': 'proxy không thể kết nối đến máy chủ (%1)',
'playing... tap to stop': 'đang phát... nhấn để dừng',
'loading %1%': 'đang tải %1%',
'tap to play': 'nhấn để phát',
'tap to play in player': 'nhấn để phát trong trình phát',
'buffering %1%... opening player': 'đang đệm %1%... đang mở trình phát',
'Could not play this audio: %1': 'Không thể phát âm thanh này: %1',
'could not open the voice file': 'không thể mở tệp thoại',
'could not decode the voice message': 'không thể giải mã tin nhắn thoại',
'audio is unavailable (%1)': 'âm thanh không khả dụng (%1)',
'could not open audio (%1)': 'không thể mở âm thanh (%1)',
'could not prepare playback': 'không thể chuẩn bị phát',
'could not start playback (%1)': 'không thể bắt đầu phát (%1)',
'could not play (%1)': 'không thể phát (%1)',
'recording is only available on the phone': 'ghi âm chỉ khả dụng trên điện thoại',
'Proxy: %1': 'Proxy: %1',
'on': 'bật',
'No connection through the proxy. Check the proxy or tap Reconnect.': 'Không có kết nối qua proxy. Kiểm tra proxy hoặc nhấn Kết nối lại.',
'No connection. Tap Reconnect, or set up a proxy if Telegram is blocked.': 'Không có kết nối. Nhấn Kết nối lại, hoặc thiết lập proxy nếu Telegram bị chặn.',
'Saved photos and files go here. Pick a drive, or "Choose folder..." for any folder.': 'Ảnh và tệp đã lưu sẽ vào đây. Chọn một ổ đĩa, hoặc «Chọn thư mục...» cho thư mục bất kỳ.',
'Saved photos and files go to a "Symbigram" folder on this drive.': 'Ảnh và tệp đã lưu sẽ vào thư mục «Symbigram» trên ổ đĩa này.',
'End the secret chat with "%1"? Its messages live only on this device and will be removed here.': 'Kết thúc trò chuyện bí mật với «%1»? Các tin nhắn của nó chỉ tồn tại trên thiết bị này và sẽ bị xóa tại đây.',
'%1 wants to start a secret chat': '%1 muốn bắt đầu trò chuyện bí mật',
}
