// Generated by tools/generate-schema.py from Telegram's TL schema.
// Layer 73. 86 constructors.
//
// Do not edit. Re-run the generator against a newer schema instead.
// The encoding is documented in the generator and in tlobject.cpp.
#include "tlobject.h"

// "<ctor-hex>:<field-spec>" entries, semicolon separated.
const char *const TlSchema::secretPackedTable =
    "020df5d0:offset=i,length=i;051448e5:duration=i;089f5c4a:;0c4f40be:random_ids=vl;0e17e23c:type=s;0ef02ce6:flags=#,duration=i,w=i,h=i;11b58939:;15590068:file_name=s;16bf744e:;176f8ba1:;1be31789:random_b"
    "ytes=b,layer=i,in_seq_no=i,out_seq_no=i,message=o;1f814f1f:random_id=l,random_bytes=b,message=s,media=o;204d3878:random_id=l,ttl=i,message=s,media=o;28a20571:offset=i,length=i;32798a8c:thumb=b,thumb_w"
    "=i,thumb_h=i,w=i,h=i,size=i,key=b,iv=b;32ca960f:offset=i,length=i;352dca58:offset=i,length=i,user_id=i;35480a59:lat=d,long=d;36b091de:flags=#,random_id=l,ttl=i,message=s,media=0.9?o,entities=0.7?vo,vi"
    "a_bot_name=0.11?s,reply_to_random_id=0.3?l;3a556302:alt=s,stickerset=o;3fedd339:;4c4e743f:offset=i,length=i;4cee6ef3:thumb=b,thumb_w=i,thumb_h=i,duration=i,w=i,h=i,size=i,key=b,iv=b;511110b0:start_seq"
    "_no=i,end_seq_no=i;524a415d:thumb=b,thumb_w=i,thumb_h=i,duration=i,mime_type=s,w=i,h=i,size=i,key=b,iv=b;53d69076:dc_id=i,volume_id=l,local_id=i,secret=l;57e0a9cb:duration=i,mime_type=s,size=i,key=b,i"
    "v=b;588a0a97:phone_number=s,first_name=s,last_name=s,user_id=i;5910cccb:duration=i,w=i,h=i;6080758f:duration=i,size=i,key=b,iv=b;628cbc6f:;64e475c2:offset=i,length=i;65614304:random_ids=vl;6719e45c:;6"
    "abd9782:thumb=b,thumb_w=i,thumb_h=i,mime_type=s,size=l,key=b,iv=b,attributes=vo,caption=s;6c37c15c:w=i,h=i;6cef8ac7:offset=i,length=i;6ed02538:offset=i,length=i;6f635b0d:offset=i,length=i;6fe1735b:exc"
    "hange_id=l,g_b=b,key_fingerprint=l;73164160:random_id=l,action=o;73924be0:offset=i,length=i,language=s;761e6af4:offset=i,length=i;76a6d327:offset=i,length=i,url=s;77bfb61b:type=s,location=o,w=i,h=i,si"
    "ze=i;7afe8ae2:thumb=b,thumb_w=i,thumb_h=i,mime_type=s,size=i,key=b,iv=b,attributes=vo,caption=s;7c596b46:volume_id=l,local_id=i,secret=l;826f8b60:offset=i,length=i;861cc8a0:short_name=s;88f27fbc:;8a0d"
    "f56f:lat=d,long=d,title=s,address=s,provider=s,venue_id=s;8ac1f475:random_ids=vl;8faee98e:;91cc4674:flags=#,random_id=l,ttl=i,message=s,media=0.9?o,entities=0.7?vo,via_bot_name=0.11?s,reply_to_random_"
    "id=0.3?l,grouped_id=0.17?l;92042ff7:;970c8c0e:thumb=b,thumb_w=i,thumb_h=i,duration=i,mime_type=s,w=i,h=i,size=i,key=b,iv=b,caption=s;9852f9c6:flags=#,duration=i,title=0.0?s,performer=0.1?s,waveform=0."
    "2?b;990a3c1a:;9b69e34b:offset=i,length=i;9c4e7e8b:offset=i,length=i;a1733aec:ttl_seconds=i;a187d66f:;a82fdd63:;aa48327d:random_id=l,random_bytes=b,action=o;b095434b:thumb=b,thumb_w=i,thumb_h=i,file_na"
    "me=s,mime_type=s,size=i,key=b,iv=b;bb718624:;bb92ba95:offset=i,length=i;bd610bc9:offset=i,length=i;bf0693d4:offset=i,length=i;c8cf05f8:offset=i,length=i,document_id=l;ccb27641:action=o;d52f73f7:;dd05e"
    "c6b:exchange_id=l;ded218e0:duration=i,title=s,performer=s;e50511d8:url=s;e6ac8a6f:;e9a734fa:type=s,location=o,w=i,h=i,bytes=b;ec2e0b9b:exchange_id=l,key_fingerprint=l;f1fa8d78:thumb=b,thumb_w=i,thumb_"
    "h=i,w=i,h=i,size=i,key=b,iv=b,caption=s;f3048883:layer=i;f3c9611b:exchange_id=l,g_a=b;fa04579d:offset=i,length=i;fa95b0dd:id=l,access_hash=l,date=i,mime_type=s,size=i,thumb=o,dc_id=i,attributes=vo;fb0"
    "a5727:;fd5ec8f5:;ffb62b95:";

const int TlSchema::secretPackedLength = 3026;
