#!/usr/bin/env python3
"""
Generates src/core/tlschema_data.cpp from Telegram's TL schema (telegram_api.tl).

Why generate: message#7600b9d3 alone has ~35 optional fields pulling in a dozen further
types. Hand-writing parsers for that tree is most of a client, and every transcribed field
is a chance to misread a value as something else. The schema is the authority, so the
parser comes from the schema.

What is emitted is not parser code but a compact *field table*: one entry per constructor,
describing its fields in order. A small interpreter in tlobject.cpp walks that table.

Field encoding, comma separated:

    #          a flags word (int32) - referenced by later conditions
    i l d      int32, int64, double
    s b        string, bytes
    I J        int128 (16 raw bytes), int256 (32 raw bytes)
    o          a boxed object: read a constructor id, then recurse
    v<spec>    a boxed vector of <spec>
    V<spec>    a bare vector (no constructor id) of <spec>
    N.B?<spec> present only if bit B of flags word N is set

Each field is written as `name=spec`, so callers look fields up by name rather than by
position. Fields of type `true` carry no data at all and are omitted entirely.

Usage:
    python generate-schema.py <path-to-telegram_api.tl> <output.cpp> [layer]

The same encoding as LumigramPlus (Tools/generate-schema.py), so the two clients read the
same table.
"""

import re
import sys

PRIMITIVES = {
    'int': 'i',
    'long': 'l',
    'double': 'd',
    'string': 's',
    'bytes': 'b',
    'int128': 'I',
    'int256': 'J',
    '#': '#',
}


def encode_type(t):
    t = t.strip()
    if t in PRIMITIVES:
        return PRIMITIVES[t]
    m = re.match(r'^Vector<(.+)>$', t)
    if m:
        return 'v' + encode_type(m.group(1))
    m = re.match(r'^vector<(.+)>$', t)
    if m:
        return 'V' + encode_type(m.group(1))
    if t.startswith('%'):
        return 'o'
    if t.startswith('!') or t == 'X':
        return 'o'
    return 'o'


def parse_line(line, flag_words):
    line = line.strip()
    if not line or line.startswith('//') or line.startswith('---'):
        return None
    if not line.endswith(';'):
        return None
    line = line[:-1]
    if '=' not in line:
        return None
    head, result = line.rsplit('=', 1)
    head = head.strip()
    m = re.match(r'^([A-Za-z0-9_.]+)#([0-9a-fA-F]+)\s*(.*)$', head)
    if not m:
        return None
    name, ctor_hex, rest = m.group(1), m.group(2), m.group(3)
    ctor = int(ctor_hex, 16)
    rest = re.sub(r'\{[^}]*\}', ' ', rest)
    fields = []
    flag_words.clear()
    for arg in rest.split():
        if ':' not in arg:
            continue
        fname, ftype = arg.split(':', 1)
        if ftype == '#':
            flag_words.append(fname)
            fields.append(fname + '=#')
            continue
        cond = ''
        m2 = re.match(r'^([A-Za-z0-9_]+)\.(\d+)\?(.+)$', ftype)
        if m2:
            word, bit, ftype = m2.group(1), int(m2.group(2)), m2.group(3)
            if word not in flag_words:
                return None
            cond = '%d.%d?' % (flag_words.index(word), bit)
        if ftype == 'true':
            continue
        fields.append(fname + '=' + cond + encode_type(ftype))
    return ctor, name, ','.join(fields)


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    schema_path, out_path = sys.argv[1], sys.argv[2]
    layer = sys.argv[3] if len(sys.argv) > 3 else '0'

    entries = {}
    skipped = 0
    flag_words = []
    with open(schema_path, 'r', encoding='utf-8') as f:
        for line in f:
            parsed = parse_line(line, flag_words)
            if parsed is None:
                if line.strip() and not line.strip().startswith('//') \
                        and not line.strip().startswith('---'):
                    skipped += 1
                continue
            ctor, name, spec = parsed
            entries[ctor] = spec

    packed = ';'.join('%08x:%s' % (c, entries[c]) for c in sorted(entries))
    chunks = [packed[i:i + 200] for i in range(0, len(packed), 200)]

    with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write('// Generated by tools/generate-schema.py from Telegram\'s TL schema.\n')
        f.write('// Layer %s. %d constructors.\n' % (layer, len(entries)))
        f.write('//\n')
        f.write('// Do not edit. Re-run the generator against a newer schema instead.\n')
        f.write('// The encoding is documented in the generator and in tlobject.cpp.\n')
        f.write('#include "tlobject.h"\n\n')
        f.write('const int TlSchema::Layer = %s;\n\n' % layer)
        f.write('// "<ctor-hex>:<field-spec>" entries, semicolon separated.\n')
        f.write('const char *const TlSchema::packedTable =\n')
        for i, c in enumerate(chunks):
            esc = c.replace('\\', '\\\\').replace('"', '\\"')
            sep = '' if i < len(chunks) - 1 else ';'
            f.write('    "%s"%s\n' % (esc, sep))
        f.write('\nconst int TlSchema::packedLength = %d;\n' % len(packed))

    print('%d constructors written to %s' % (len(entries), out_path))
    if skipped:
        print('%d schema lines not parsed (comments/blank/unsupported)' % skipped)
    return 0


if __name__ == '__main__':
    sys.exit(main())
