#!/usr/bin/env python3
# Fills translations/symbigram_<lang>.ts from the tables below (source text -> translation).
# Strings not in a table stay untranslated (English) and are listed. Languages: ru, uk.
#
#   lupdate -extensions qml,cpp,h -no-obsolete src qml -ts translations/symbigram_ru.ts translations/symbigram_uk.ts
#   python tools/translate.py
#   lrelease translations/symbigram_ru.ts translations/symbigram_uk.ts
import os
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

RU = {
    "version %1": "версия %1",
    "A Telegram client for Symbian Anna/Belle, ported from Lumigram/LumigramPlus for Windows Phone 8.1. It speaks MTProto 2.0 directly to Telegram - no bridge, no proxy; the encryption key is made on the phone.":
        "Telegram-клиент для Symbian Anna/Belle, перенесённый с Lumigram/LumigramPlus для Windows Phone 8.1. Говорит с Telegram напрямую по MTProto 2.0 — без моста и прокси; ключ шифрования создаётся на телефоне.",
    "Sign-in is by QR code only (scan from a signed-in Telegram, plus the two-step password if set). Text messages, photos and files (view, save and send), groups and channels.":
        "Вход только по QR-коду (сканируется из Telegram, где вы уже вошли; плюс пароль двухэтапной проверки, если он есть). Текстовые сообщения, фото и файлы (просмотр, сохранение и отправка), группы и каналы.",
    "Log": "Журнал",
    "Copy log": "Скопировать журнал",
    "Not connected.": "Нет соединения.",
    "Connecting...": "Подключение...",
    "Connecting and creating the encryption key...": "Подключение и создание ключа шифрования...",
    "Checking the password (this takes a few seconds)...": "Проверка пароля (это займёт несколько секунд)...",
    "This account has two-step verification. Enter the password.": "У этого аккаунта включена двухэтапная проверка. Введите пароль.",
    "Requesting a sign-in code...": "Запрос кода для входа...",
    "Waiting for the code to be scanned...": "Ожидание сканирования кода...",
    "Signing in...": "Вход...",
    "Connection lost: %1. Reconnecting...": "Соединение потеряно: %1. Переподключение...",
    "Connection failed: %1. Retrying...": "Не удалось подключиться: %1. Повтор...",
    "Enter the password.": "Введите пароль.",
    "Copied.": "Скопировано.",
    "Load older messages": "Загрузить более старые сообщения",
    "Reload": "Обновить",
    "Unmute": "Включить уведомления",
    "Mute": "Отключить уведомления",
    "Mark as read": "Отметить прочитанным",
    "Copy text": "Скопировать текст",
    "Reply": "Ответить",
    "Replying to": "Ответ на",
    "Retry": "Повторить",
    "Delete for me": "Удалить у себя",
    "Delete for everyone": "Удалить у всех",
    "connecting...": "подключение...",
    "offline": "не в сети",
    "online": "в сети",
    "Older messages": "Более старые сообщения",
    "Could not load the messages: %1": "Не удалось загрузить сообщения: %1",
    "No messages yet.": "Сообщений пока нет.",
    "channel - only its admins can post": "канал — писать могут только его администраторы",
    "message": "сообщение",
    "Send": "Отправить",
    "Yesterday": "Вчера",
    "%1 is typing...": "%1 печатает...",
    "typing...": "печатает...",
    "You: %1": "Вы: %1",
    "Connect": "Подключиться",
    "Disconnect": "Отключиться",
    "Settings": "Настройки",
    "About": "О программе",
    "Sign out": "Выход из аккаунта",
    "Exit": "Выход из приложения",
    "Sign out? The session will be ended on Telegram and removed from this phone.": "Выйти из аккаунта? Сеанс будет завершён в Telegram и удалён с этого телефона.",
    "Cancel": "Отмена",
    "New chat": "Новый чат",
    "Find": "Найти",
    "@username, phone number, t.me link, or a contact's name": "@username, номер телефона, ссылка t.me или имя контакта",
    "@username or +phone": "@username или +телефон",
    "Clear history": "Очистить историю",
    "Delete all messages of \"%1\" on Telegram (for you)?": "Удалить все сообщения чата «%1» в Telegram (у себя)?",
    "Delete": "Удалить",
    "loading...": "загрузка...",
    "Older chats": "Более старые чаты",
    "Loading chats...": "Загрузка чатов...",
    "No chats yet. Tap + to find someone.": "Чатов пока нет. Нажмите +, чтобы найти собеседника.",
    "Offline. Use the menu to connect.": "Не в сети. Подключитесь через меню.",
    "Telegram for Symbian": "Telegram для Symbian",
    "No connection. Tap the refresh button to try again.": "Нет соединения. Нажмите кнопку обновления, чтобы повторить.",
    "The code renews in %1 s": "Код обновится через %1 с",
    "Open Telegram on a phone or PC where you are signed in: Settings > Devices > Link Desktop Device, and scan this code.":
        "Откройте Telegram на телефоне или ПК, где вы уже вошли: Настройки > Устройства > Подключить устройство, и отсканируйте этот код.",
    "Two-step verification password": "Пароль двухэтапной проверки",
    "hint: %1": "подсказка: %1",
    "password": "пароль",
    "show password": "показать пароль",
    "checking...": "проверка...",
    "sign in": "войти",
    "Symbigram talks MTProto 2.0 straight to Telegram's servers: the encryption key is made on this phone and never leaves it. The session shows up under Devices in Telegram, where it can be ended at any time.":
        "Symbigram говорит с серверами Telegram напрямую по MTProto 2.0: ключ шифрования создаётся на этом телефоне и никогда его не покидает. Сеанс виден в разделе «Устройства» в Telegram, где его можно завершить в любой момент.",
    "Forwarded from %1": "Переслано от %1",
    "edited": "изменено",
    "Today": "Сегодня",
    "reply": "ответ",
    "You": "Вы",
    "last seen at %1": "был(а) в %1",
    "last seen yesterday at %1": "был(а) вчера в %1",
    "last seen %1": "был(а) %1",
    "last seen recently": "был(а) недавно",
    "last seen within a week": "был(а) на этой неделе",
    "last seen within a month": "был(а) в этом месяце",
    "last seen a long time ago": "был(а) давно",
    "bot": "бот",
    "Saved Messages": "Избранное",
    "channel, %1 subscribers": "канал, подписчиков: %1",
    "channel": "канал",
    "%1 members": "участников: %1",
    "group": "группа",
    "The message was not sent: %1": "Сообщение не отправлено: %1",
    "key exchange failed: %1": "обмен ключами не удался: %1",
    "no response from the server": "сервер не отвечает",
    "connection closed": "соединение закрыто",
    "connection timed out": "время ожидания соединения истекло",
    "Symbigram: new message": "Symbigram: новое сообщение",
    "Symbigram: %1 new messages": "Symbigram: новых сообщений: %1",
    "App language": "Язык приложения",
    "System default": "Как в системе",
    "Notifications": "Уведомления",
    "Popup for new messages": "Всплывающее окно о новых сообщениях",
    "Vibrate": "Вибрация",
    "Groups and channels": "Группы и каналы",
    "For messages that arrive while another application is in front: the \"new messages\" dialog, the popup and the vibration. Chats muted in Telegram stay quiet. Symbigram stays connected in the background either way.":
        "Для сообщений, пришедших, пока открыто другое приложение: диалог «новые сообщения», всплывающее окно и вибрация. Чаты, отключённые в Telegram, остаются беззвучными. Symbigram в любом случае остаётся на связи в фоне.",
    "Connect on start": "Подключаться при запуске",
    "Takes effect after the app is restarted.": "Вступает в силу после перезапуска приложения.",
    "Signed out.": "Выход выполнен.",
    "Enter a username, a phone number or a name.": "Введите имя пользователя, номер телефона или имя.",
    "This account has no password set.": "У этого аккаунта нет пароля.",
    "Unsupported password method.": "Неподдерживаемый способ проверки пароля.",
    "Nobody found.": "Никого не найдено.",
    "The session was ended (%1). Please sign in again.": "Сеанс завершён (%1). Войдите снова.",
    "Wrong password.": "Неверный пароль.",
    "Too many attempts. Wait %1 seconds.": "Слишком много попыток. Подождите %1 с.",
    "Could not load the chat list: %1": "Не удалось загрузить список чатов: %1",
    "user %1": "пользователь %1",
    "chat %1": "чат %1",
    "deleted account": "удалённый аккаунт",
    "video": "видео",
    "photo": "фото",
    "location %1, %2": "геопозиция %1, %2",
    "location": "геопозиция",
    "location: %1": "место: %1",
    "contact: %1 %2 %3": "контакт: %1 %2 %3",
    "poll: %1": "опрос: %1",
    "dice: %1": "кубик: %1",
    "game": "игра",
    "invoice": "счёт",
    "story": "история",
    "file": "файл",
    "sticker": "стикер",
    "sticker %1": "стикер %1",
    "voice message %1": "голосовое сообщение %1",
    "voice message": "голосовое сообщение",
    "video message %1": "видеосообщение %1",
    "video message": "видеосообщение",
    "GIF": "GIF",
    "video %1": "видео %1",
    "audio %1": "аудио %1",
    "audio": "аудио",
    "image": "изображение",
    "%1 MB": "%1 МБ",
    "%1 KB": "%1 КБ",
    "%1 B": "%1 Б",
    "file: %1 (%2)": "файл: %1 (%2)",
    "unsupported attachment": "неподдерживаемое вложение",
    "attachment": "вложение",
    "created the group \"%1\"": "создал(а) группу «%1»",
    "created the channel \"%1\"": "создал(а) канал «%1»",
    "added %1": "добавил(а) %1",
    "removed %1": "удалил(а) %1",
    "joined by invite link": "вступил(а) по ссылке-приглашению",
    "pinned a message": "закрепил(а) сообщение",
    "joined Telegram": "присоединился(-ась) к Telegram",
    "cleared the history": "очистил(а) историю",
    "service message": "служебное сообщение",
    "empty message": "пустое сообщение",
    "Folders": "Папки",
    "Folder": "Папка",
    "All chats": "Все чаты",
    "Archive": "Архив",
    "tap to switch folder": "нажмите, чтобы сменить папку",
    "The archive is empty.": "Архив пуст.",
    "No chats in this folder.": "В этой папке нет чатов.",
    "Keep a log": "Вести журнал",
    "Off by default. Turn it on only to collect a diagnostic log (shown on the About page) when something goes wrong.": "По умолчанию выключено. Включайте только для сбора диагностического журнала (виден на странице «О программе»), когда что-то идёт не так.",
    "Logging is off. Turn on \"Keep a log\" in Settings to collect one.": "Журнал выключен. Включите «Вести журнал» в настройках, чтобы собрать его.",
    "Images (*.jpg *.jpeg *.png *.gif *.bmp)": "Изображения (*.jpg *.jpeg *.png *.gif *.bmp)",
    "All files (*)": "Все файлы (*)",
    "Choose an image": "Выберите изображение",
    "Choose a file": "Выберите файл",
    "Sending the image...": "Отправка изображения...",
    "Sending the file...": "Отправка файла...",
    "Image": "Изображение",
    "File": "Файл",
    "Save to phone": "Сохранить в телефон",
    "Open": "Открыть",
    "Save": "Сохранить",
    "Close": "Закрыть",
    "Tap to load": "Нажмите, чтобы загрузить",
    "Failed - tap to retry": "Ошибка — нажмите, чтобы повторить",
    "Voice message": "Голосовое сообщение",
    "Video": "Видео",
    "tap to open": "нажмите, чтобы открыть",
    "downloading %1%": "загрузка %1%",
    "tap to download": "нажмите, чтобы скачать",
    "Saved to %1": "Сохранено в %1",
    "Could not save the file.": "Не удалось сохранить файл.",
    "the server rejected a part of the file": "сервер отклонил часть файла",
    "the file is served from a CDN, which is not supported": "файл раздаётся через CDN, что не поддерживается",
    "unexpected reply": "неожиданный ответ",
    "could not write the file": "не удалось записать файл",
    "could not create the file": "не удалось создать файл",
    "the file is empty": "файл пуст",
    "could not read the file": "не удалось прочитать файл",
    "the file is too large": "файл слишком большой",
    "Start secret chat": "Начать секретный чат",
    "Verify encryption key": "Проверить ключ шифрования",
    "Self-destruct timer": "Таймер самоуничтожения",
    "Delete secret chat": "Удалить секретный чат",
    "End this secret chat? Its messages, which live only on this device, will be removed here.": "Завершить этот секретный чат? Его сообщения, которые хранятся только на этом устройстве, будут удалены здесь.",
    "Encryption key": "Ключ шифрования",
    "If this key matches on both phones, no one is intercepting the chat. Compare it with %1 in person or over a trusted channel.": "Если этот ключ совпадает на обоих телефонах, чат никто не перехватывает. Сравните его с %1 лично или по надёжному каналу.",
    "%1 wants to start an end-to-end encrypted chat.": "%1 хочет начать сквозной зашифрованный чат.",
    "Waiting for the other side to come online and accept...": "Ожидание, пока собеседник выйдет в сеть и примет запрос...",
    "Decline": "Отклонить",
    "Cancel request": "Отменить запрос",
    "encrypted message": "зашифрованное сообщение",
    "secret chat": "секретный чат",
    "wants to start a secret chat": "хочет начать секретный чат",
    "waiting to be accepted...": "ожидает подтверждения...",
    "end-to-end encrypted": "сквозное шифрование",
    "end-to-end encrypted, self-destruct %1s": "сквозное шифрование, самоуничтожение %1с",
    "Secret chats can only be opened with a person.": "Секретные чаты можно открывать только с человеком.",
    "The secret chat is not ready.": "Секретный чат не готов.",
    "Secret chats can only be started with a person.": "Секретные чаты можно начинать только с человеком.",
    "Starting a secret chat...": "Создание секретного чата...",
    "Someone wants to start a secret chat.": "Кто-то хочет начать секретный чат.",
    "%1 wants to start a secret chat.": "%1 хочет начать секретный чат.",
    "Secret chat is ready.": "Секретный чат готов.",
    "Secret chat": "Секретный чат",
    "Encrypted message": "Зашифрованное сообщение",
    "Could not start the secret chat: %1": "Не удалось начать секретный чат: %1",
    "Could not accept the secret chat: %1": "Не удалось принять секретный чат: %1",
    "Accept": "Принять",
    "Off": "Выкл.",
    "5 seconds": "5 секунд",
    "30 seconds": "30 секунд",
    "1 minute": "1 минута",
    "1 hour": "1 час",
    "1 day": "1 день",
    "1 week": "1 неделя",
    "Saved": "Сохранено",
    "File saved to: %1": "Файл сохранён: %1",
    "Could not save the file to %1": "Не удалось сохранить файл в %1",
    "Phone memory": "Память телефона",
    "Mass memory": "Массовая память",
    "Memory card": "Карта памяти",
    "Save downloads to": "Сохранять загрузки в",
    "Choose folder...": "Выбрать папку...",
    "Choose download folder": "Выберите папку загрузок",
    "SOCKS5 proxy": "SOCKS5-прокси",
    "Proxy server": "Сервер прокси",
    "not set": "не задан",
    "Route the connection through a SOCKS5 proxy. Changing it reconnects.": "Направлять соединение через SOCKS5-прокси. Изменение переподключает.",
    "Server": "Сервер",
    "host or IP": "хост или IP",
    "Port": "Порт",
    "Username (optional)": "Имя пользователя (необязательно)",
    "Password (optional)": "Пароль (необязательно)",
    "Reconnect": "Переподключиться",
    "Enable": "Включить",
    "Set up proxy": "Настроить прокси",
    "Cannot record a voice message here.": "Здесь нельзя записать голосовое сообщение.",
    "Sending the voice message...": "Отправка голосового сообщения...",
    "the microphone is unavailable (%1)": "микрофон недоступен (%1)",
    "could not open the microphone (%1)": "не удалось открыть микрофон (%1)",
    "could not start recording (%1)": "не удалось начать запись (%1)",
    "the recording was too short": "запись слишком короткая",
    "could not encode the recording": "не удалось закодировать запись",
    "could not save the recording": "не удалось сохранить запись",
    "could not read the recording": "не удалось прочитать запись",
    "Archive chat": "Архивировать чат",
    "Unarchive chat": "Разархивировать чат",
    "Move to folder": "Переместить в папку",
    "All chats (no folder)": "Все чаты (без папки)",
    "Sign in with QR code": "Войти по QR-коду",
    "Sign in with phone number": "Войти по номеру телефона",
    "Use QR code instead": "Использовать QR-код",
    "Phone number": "Номер телефона",
    "Include the country code. Telegram will send a login code to this number.": "Укажите код страны. Telegram пришлёт на этот номер код для входа.",
    "requesting...": "запрос...",
    "send code": "отправить код",
    "Enter the code sent to %1": "Введите код, отправленный на %1",
    "code": "код",
    "signing in...": "вход...",
    "Resend code": "Отправить код снова",
    "Change number": "Изменить номер",
    "Enter your phone number.": "Введите номер телефона.",
    "Enter the code.": "Введите код.",
    "Enter the code Telegram sent to %1.": "Введите код, который Telegram отправил на %1.",
    "Requesting a code...": "Запрос кода...",
    "Enter your phone number, with the country code, to get a code.": "Введите номер телефона с кодом страны, чтобы получить код.",
    "Enter a valid phone number, with the country code.": "Введите корректный номер телефона с кодом страны.",
    "No Telegram account uses this number. Sign-up isn't supported here.": "К этому номеру не привязан аккаунт Telegram. Регистрация здесь не поддерживается.",
    "That phone number is not valid.": "Этот номер телефона недействителен.",
    "That phone number is banned from Telegram.": "Этот номер заблокирован в Telegram.",
    "Too many codes requested for this number. Try again later.": "Слишком много запросов кода для этого номера. Повторите позже.",
    "Too many attempts. Try again later.": "Слишком много попыток. Повторите позже.",
    "This build's Telegram API key was rejected.": "Ключ API Telegram этой сборки отклонён.",
    "Wrong code. Check it and try again.": "Неверный код. Проверьте и попробуйте снова.",
    "The code expired. Request a new one.": "Код истёк. Запросите новый.",
    "Delete chat": "Удалить чат",
    "Delete for me": "Удалить у меня",
    "Myself": "У меня",
    "All": "У всех",
    "Delete for all": "Удалить у всех",
    "Delete the chat \"%1\"? \"All\" also removes it for the other side.": "Удалить чат «%1»? «У всех» также удалит его у собеседника.",
    "Could not change the folder: %1": "Не удалось изменить папку: %1",
    "That folder must keep at least one chat, so the chat stays in it too.": "В папке должен остаться хотя бы один чат, поэтому чат останется и в ней.",
    "That folder no longer exists.": "Этой папки больше нет.",
    "the proxy refused our authentication method": "прокси отклонил метод аутентификации",
    "proxy authentication failed - check the username and password": "ошибка аутентификации прокси — проверьте имя пользователя и пароль",
    "the proxy sent a malformed reply": "прокси прислал некорректный ответ",
    "the proxy could not reach the server (%1)": "прокси не смог подключиться к серверу (%1)",
    "playing... tap to stop": "воспроизведение... нажмите, чтобы остановить",
    "loading %1%": "загрузка %1%",
    "tap to play": "нажмите, чтобы воспроизвести",
    "could not open the voice file": "не удалось открыть голосовой файл",
    "could not decode the voice message": "не удалось декодировать голосовое сообщение",
    "audio is unavailable (%1)": "аудио недоступно (%1)",
    "could not open audio (%1)": "не удалось открыть аудио (%1)",
    "could not prepare playback": "не удалось подготовить воспроизведение",
    "could not start playback (%1)": "не удалось начать воспроизведение (%1)",
    "could not play (%1)": "не удалось воспроизвести (%1)",
    "recording is only available on the phone": "запись доступна только на телефоне",
    "Proxy: %1": "Прокси: %1",
    "on": "вкл",
    "No connection through the proxy. Check the proxy or tap Reconnect.": "Нет соединения через прокси. Проверьте прокси или нажмите «Переподключиться».",
    "No connection. Tap Reconnect, or set up a proxy if Telegram is blocked.": "Нет соединения. Нажмите «Переподключиться» или настройте прокси, если Telegram заблокирован.",
    "Saved photos and files go here. Pick a drive, or \"Choose folder...\" for any folder.": "Сюда сохраняются фото и файлы. Выберите диск или «Выбрать папку...» для любой папки.",
    "Saved photos and files go to a \"Symbigram\" folder on this drive.": "Сохранённые фото и файлы попадают в папку «Symbigram» на этом диске.",
    "End the secret chat with \"%1\"? Its messages live only on this device and will be removed here.": "Завершить секретный чат с «%1»? Его сообщения хранятся только на этом устройстве и будут удалены здесь.",
    "%1 wants to start a secret chat": "%1 хочет начать секретный чат",
}

UK = {
    "version %1": "версія %1",
    "A Telegram client for Symbian Anna/Belle, ported from Lumigram/LumigramPlus for Windows Phone 8.1. It speaks MTProto 2.0 directly to Telegram - no bridge, no proxy; the encryption key is made on the phone.":
        "Telegram-клієнт для Symbian Anna/Belle, перенесений із Lumigram/LumigramPlus для Windows Phone 8.1. Спілкується з Telegram напряму по MTProto 2.0 — без мосту та проксі; ключ шифрування створюється на телефоні.",
    "Sign-in is by QR code only (scan from a signed-in Telegram, plus the two-step password if set). Text messages, photos and files (view, save and send), groups and channels.":
        "Вхід лише за QR-кодом (сканується з Telegram, де ви вже увійшли; плюс пароль двоетапної перевірки, якщо він є). Текстові повідомлення, фото та файли (перегляд, збереження й надсилання), групи та канали.",
    "Log": "Журнал",
    "Copy log": "Скопіювати журнал",
    "Not connected.": "Немає з'єднання.",
    "Connecting...": "Підключення...",
    "Connecting and creating the encryption key...": "Підключення та створення ключа шифрування...",
    "Checking the password (this takes a few seconds)...": "Перевірка пароля (це займе кілька секунд)...",
    "This account has two-step verification. Enter the password.": "У цього облікового запису ввімкнено двоетапну перевірку. Введіть пароль.",
    "Requesting a sign-in code...": "Запит коду для входу...",
    "Waiting for the code to be scanned...": "Очікування сканування коду...",
    "Signing in...": "Вхід...",
    "Connection lost: %1. Reconnecting...": "З'єднання втрачено: %1. Перепідключення...",
    "Connection failed: %1. Retrying...": "Не вдалося підключитися: %1. Повтор...",
    "Enter the password.": "Введіть пароль.",
    "Copied.": "Скопійовано.",
    "Load older messages": "Завантажити старіші повідомлення",
    "Reload": "Оновити",
    "Unmute": "Увімкнути сповіщення",
    "Mute": "Вимкнути сповіщення",
    "Mark as read": "Позначити прочитаним",
    "Copy text": "Скопіювати текст",
    "Reply": "Відповісти",
    "Replying to": "Відповідь на",
    "Retry": "Повторити",
    "Delete for me": "Видалити в себе",
    "Delete for everyone": "Видалити в усіх",
    "connecting...": "підключення...",
    "offline": "не в мережі",
    "online": "у мережі",
    "Older messages": "Старіші повідомлення",
    "Could not load the messages: %1": "Не вдалося завантажити повідомлення: %1",
    "No messages yet.": "Повідомлень поки немає.",
    "channel - only its admins can post": "канал — писати можуть лише його адміністратори",
    "message": "повідомлення",
    "Send": "Надіслати",
    "Yesterday": "Вчора",
    "%1 is typing...": "%1 друкує...",
    "typing...": "друкує...",
    "You: %1": "Ви: %1",
    "Connect": "Підключитися",
    "Disconnect": "Відключитися",
    "Settings": "Налаштування",
    "About": "Про програму",
    "Sign out": "Вихід з облікового запису",
    "Exit": "Вихід із застосунку",
    "Sign out? The session will be ended on Telegram and removed from this phone.": "Вийти з облікового запису? Сеанс буде завершено в Telegram і видалено з цього телефону.",
    "Cancel": "Скасувати",
    "New chat": "Новий чат",
    "Find": "Знайти",
    "@username, phone number, t.me link, or a contact's name": "@username, номер телефону, посилання t.me або ім'я контакту",
    "@username or +phone": "@username або +телефон",
    "Clear history": "Очистити історію",
    "Delete all messages of \"%1\" on Telegram (for you)?": "Видалити всі повідомлення чату «%1» у Telegram (у себе)?",
    "Delete": "Видалити",
    "loading...": "завантаження...",
    "Older chats": "Старіші чати",
    "Loading chats...": "Завантаження чатів...",
    "No chats yet. Tap + to find someone.": "Чатів поки немає. Натисніть +, щоб знайти співрозмовника.",
    "Offline. Use the menu to connect.": "Не в мережі. Підключіться через меню.",
    "Telegram for Symbian": "Telegram для Symbian",
    "No connection. Tap the refresh button to try again.": "Немає з'єднання. Натисніть кнопку оновлення, щоб повторити.",
    "The code renews in %1 s": "Код оновиться через %1 с",
    "Open Telegram on a phone or PC where you are signed in: Settings > Devices > Link Desktop Device, and scan this code.":
        "Відкрийте Telegram на телефоні або ПК, де ви вже увійшли: Налаштування > Пристрої > Підключити пристрій, і відскануйте цей код.",
    "Two-step verification password": "Пароль двоетапної перевірки",
    "hint: %1": "підказка: %1",
    "password": "пароль",
    "show password": "показати пароль",
    "checking...": "перевірка...",
    "sign in": "увійти",
    "Symbigram talks MTProto 2.0 straight to Telegram's servers: the encryption key is made on this phone and never leaves it. The session shows up under Devices in Telegram, where it can be ended at any time.":
        "Symbigram спілкується із серверами Telegram напряму по MTProto 2.0: ключ шифрування створюється на цьому телефоні й ніколи його не залишає. Сеанс видно в розділі «Пристрої» в Telegram, де його можна завершити будь-коли.",
    "Forwarded from %1": "Переслано від %1",
    "edited": "змінено",
    "Today": "Сьогодні",
    "reply": "відповідь",
    "You": "Ви",
    "last seen at %1": "був(ла) о %1",
    "last seen yesterday at %1": "був(ла) вчора о %1",
    "last seen %1": "був(ла) %1",
    "last seen recently": "був(ла) нещодавно",
    "last seen within a week": "був(ла) цього тижня",
    "last seen within a month": "був(ла) цього місяця",
    "last seen a long time ago": "був(ла) давно",
    "bot": "бот",
    "Saved Messages": "Збережене",
    "channel, %1 subscribers": "канал, підписників: %1",
    "channel": "канал",
    "%1 members": "учасників: %1",
    "group": "група",
    "The message was not sent: %1": "Повідомлення не надіслано: %1",
    "key exchange failed: %1": "обмін ключами не вдався: %1",
    "no response from the server": "сервер не відповідає",
    "connection closed": "з'єднання закрито",
    "connection timed out": "час очікування з'єднання минув",
    "Symbigram: new message": "Symbigram: нове повідомлення",
    "Symbigram: %1 new messages": "Symbigram: нових повідомлень: %1",
    "App language": "Мова програми",
    "System default": "Як у системі",
    "Notifications": "Сповіщення",
    "Popup for new messages": "Спливаюче вікно про нові повідомлення",
    "Vibrate": "Вібрація",
    "Groups and channels": "Групи та канали",
    "For messages that arrive while another application is in front: the \"new messages\" dialog, the popup and the vibration. Chats muted in Telegram stay quiet. Symbigram stays connected in the background either way.":
        "Для повідомлень, що надійшли, поки відкрито іншу програму: діалог «нові повідомлення», спливаюче вікно та вібрація. Чати, вимкнені в Telegram, лишаються беззвучними. Symbigram у будь-якому разі лишається на зв'язку у фоні.",
    "Connect on start": "Підключатися під час запуску",
    "Takes effect after the app is restarted.": "Набуде чинності після перезапуску програми.",
    "Signed out.": "Вихід виконано.",
    "Enter a username, a phone number or a name.": "Введіть ім'я користувача, номер телефону або ім'я.",
    "This account has no password set.": "У цього облікового запису немає пароля.",
    "Unsupported password method.": "Непідтримуваний спосіб перевірки пароля.",
    "Nobody found.": "Нікого не знайдено.",
    "The session was ended (%1). Please sign in again.": "Сеанс завершено (%1). Увійдіть знову.",
    "Wrong password.": "Неправильний пароль.",
    "Too many attempts. Wait %1 seconds.": "Забагато спроб. Зачекайте %1 с.",
    "Could not load the chat list: %1": "Не вдалося завантажити список чатів: %1",
    "user %1": "користувач %1",
    "chat %1": "чат %1",
    "deleted account": "видалений обліковий запис",
    "video": "відео",
    "photo": "фото",
    "location %1, %2": "геопозиція %1, %2",
    "location": "геопозиція",
    "location: %1": "місце: %1",
    "contact: %1 %2 %3": "контакт: %1 %2 %3",
    "poll: %1": "опитування: %1",
    "dice: %1": "кубик: %1",
    "game": "гра",
    "invoice": "рахунок",
    "story": "історія",
    "file": "файл",
    "sticker": "стікер",
    "sticker %1": "стікер %1",
    "voice message %1": "голосове повідомлення %1",
    "voice message": "голосове повідомлення",
    "video message %1": "відеоповідомлення %1",
    "video message": "відеоповідомлення",
    "GIF": "GIF",
    "video %1": "відео %1",
    "audio %1": "аудіо %1",
    "audio": "аудіо",
    "image": "зображення",
    "%1 MB": "%1 МБ",
    "%1 KB": "%1 КБ",
    "%1 B": "%1 Б",
    "file: %1 (%2)": "файл: %1 (%2)",
    "unsupported attachment": "непідтримуване вкладення",
    "attachment": "вкладення",
    "created the group \"%1\"": "створив(ла) групу «%1»",
    "created the channel \"%1\"": "створив(ла) канал «%1»",
    "added %1": "додав(ла) %1",
    "removed %1": "видалив(ла) %1",
    "joined by invite link": "приєднався(-лась) за посиланням-запрошенням",
    "pinned a message": "закріпив(ла) повідомлення",
    "joined Telegram": "приєднався(-лась) до Telegram",
    "cleared the history": "очистив(ла) історію",
    "service message": "службове повідомлення",
    "empty message": "порожнє повідомлення",
    "Folders": "Теки",
    "tap to switch folder": "натисніть, щоб змінити теку",
    "Folder": "Тека",
    "All chats": "Усі чати",
    "Archive": "Архів",
    "tap the menu to change folder": "натисніть меню, щоб змінити теку",
    "The archive is empty.": "Архів порожній.",
    "No chats in this folder.": "У цій теці немає чатів.",
    "Keep a log": "Вести журнал",
    "Off by default. Turn it on only to collect a diagnostic log (shown on the About page) when something goes wrong.": "Типово вимкнено. Вмикайте лише для збору діагностичного журналу (видно на сторінці «Про програму»), коли щось іде не так.",
    "Logging is off. Turn on \"Keep a log\" in Settings to collect one.": "Журнал вимкнено. Увімкніть «Вести журнал» у налаштуваннях, щоб зібрати його.",
    "Images (*.jpg *.jpeg *.png *.gif *.bmp)": "Зображення (*.jpg *.jpeg *.png *.gif *.bmp)",
    "All files (*)": "Усі файли (*)",
    "Choose an image": "Виберіть зображення",
    "Choose a file": "Виберіть файл",
    "Sending the image...": "Надсилання зображення...",
    "Sending the file...": "Надсилання файлу...",
    "Image": "Зображення",
    "File": "Файл",
    "Save to phone": "Зберегти в телефон",
    "Open": "Відкрити",
    "Save": "Зберегти",
    "Close": "Закрити",
    "Tap to load": "Натисніть, щоб завантажити",
    "Failed - tap to retry": "Помилка — натисніть, щоб повторити",
    "Voice message": "Голосове повідомлення",
    "Video": "Відео",
    "tap to open": "натисніть, щоб відкрити",
    "downloading %1%": "завантаження %1%",
    "tap to download": "натисніть, щоб завантажити",
    "Saved to %1": "Збережено в %1",
    "Could not save the file.": "Не вдалося зберегти файл.",
    "the server rejected a part of the file": "сервер відхилив частину файлу",
    "the file is served from a CDN, which is not supported": "файл роздається через CDN, що не підтримується",
    "unexpected reply": "неочікувана відповідь",
    "could not write the file": "не вдалося записати файл",
    "could not create the file": "не вдалося створити файл",
    "the file is empty": "файл порожній",
    "could not read the file": "не вдалося прочитати файл",
    "the file is too large": "файл завеликий",
    "Start secret chat": "Почати секретний чат",
    "Verify encryption key": "Перевірити ключ шифрування",
    "Self-destruct timer": "Таймер самознищення",
    "Delete secret chat": "Видалити секретний чат",
    "End this secret chat? Its messages, which live only on this device, will be removed here.": "Завершити цей секретний чат? Його повідомлення, що зберігаються лише на цьому пристрої, будуть видалені тут.",
    "Encryption key": "Ключ шифрування",
    "If this key matches on both phones, no one is intercepting the chat. Compare it with %1 in person or over a trusted channel.": "Якщо цей ключ збігається на обох телефонах, чат ніхто не перехоплює. Порівняйте його з %1 особисто або надійним каналом.",
    "%1 wants to start an end-to-end encrypted chat.": "%1 хоче почати наскрізно зашифрований чат.",
    "Waiting for the other side to come online and accept...": "Очікування, поки співрозмовник вийде в мережу та прийме запит...",
    "Decline": "Відхилити",
    "Cancel request": "Скасувати запит",
    "encrypted message": "зашифроване повідомлення",
    "secret chat": "секретний чат",
    "wants to start a secret chat": "хоче почати секретний чат",
    "waiting to be accepted...": "очікує підтвердження...",
    "end-to-end encrypted": "наскрізне шифрування",
    "end-to-end encrypted, self-destruct %1s": "наскрізне шифрування, самознищення %1с",
    "Secret chats can only be opened with a person.": "Секретні чати можна відкривати лише з людиною.",
    "The secret chat is not ready.": "Секретний чат не готовий.",
    "Secret chats can only be started with a person.": "Секретні чати можна починати лише з людиною.",
    "Starting a secret chat...": "Створення секретного чату...",
    "Someone wants to start a secret chat.": "Хтось хоче почати секретний чат.",
    "%1 wants to start a secret chat.": "%1 хоче почати секретний чат.",
    "Secret chat is ready.": "Секретний чат готовий.",
    "Secret chat": "Секретний чат",
    "Encrypted message": "Зашифроване повідомлення",
    "Could not start the secret chat: %1": "Не вдалося почати секретний чат: %1",
    "Could not accept the secret chat: %1": "Не вдалося прийняти секретний чат: %1",
    "Accept": "Прийняти",
    "Off": "Вимк.",
    "5 seconds": "5 секунд",
    "30 seconds": "30 секунд",
    "1 minute": "1 хвилина",
    "1 hour": "1 година",
    "1 day": "1 день",
    "1 week": "1 тиждень",
    "Saved": "Збережено",
    "File saved to: %1": "Файл збережено: %1",
    "Could not save the file to %1": "Не вдалося зберегти файл у %1",
    "Phone memory": "Пам'ять телефону",
    "Mass memory": "Масова пам'ять",
    "Memory card": "Картка пам'яті",
    "Save downloads to": "Зберігати завантаження в",
    "Choose folder...": "Вибрати теку...",
    "Choose download folder": "Виберіть теку завантажень",
    "SOCKS5 proxy": "SOCKS5-проксі",
    "Proxy server": "Сервер проксі",
    "not set": "не задано",
    "Route the connection through a SOCKS5 proxy. Changing it reconnects.": "Спрямовувати з'єднання через SOCKS5-проксі. Зміна перепідключає.",
    "Server": "Сервер",
    "host or IP": "хост або IP",
    "Port": "Порт",
    "Username (optional)": "Ім'я користувача (необов'язково)",
    "Password (optional)": "Пароль (необов'язково)",
    "Reconnect": "Перепідключитися",
    "Enable": "Увімкнути",
    "Set up proxy": "Налаштувати проксі",
    "Cannot record a voice message here.": "Тут не можна записати голосове повідомлення.",
    "Sending the voice message...": "Надсилання голосового повідомлення...",
    "the microphone is unavailable (%1)": "мікрофон недоступний (%1)",
    "could not open the microphone (%1)": "не вдалося відкрити мікрофон (%1)",
    "could not start recording (%1)": "не вдалося почати запис (%1)",
    "the recording was too short": "запис занадто короткий",
    "could not encode the recording": "не вдалося закодувати запис",
    "could not save the recording": "не вдалося зберегти запис",
    "could not read the recording": "не вдалося прочитати запис",
    "Archive chat": "Архівувати чат",
    "Unarchive chat": "Розархівувати чат",
    "Move to folder": "Перемістити в теку",
    "All chats (no folder)": "Усі чати (без теки)",
    "Sign in with QR code": "Увійти за QR-кодом",
    "Sign in with phone number": "Увійти за номером телефону",
    "Use QR code instead": "Використати QR-код",
    "Phone number": "Номер телефону",
    "Include the country code. Telegram will send a login code to this number.": "Вкажіть код країни. Telegram надішле на цей номер код для входу.",
    "requesting...": "запит...",
    "send code": "надіслати код",
    "Enter the code sent to %1": "Введіть код, надісланий на %1",
    "code": "код",
    "signing in...": "вхід...",
    "Resend code": "Надіслати код знову",
    "Change number": "Змінити номер",
    "Enter your phone number.": "Введіть номер телефону.",
    "Enter the code.": "Введіть код.",
    "Enter the code Telegram sent to %1.": "Введіть код, який Telegram надіслав на %1.",
    "Requesting a code...": "Запит коду...",
    "Enter your phone number, with the country code, to get a code.": "Введіть номер телефону з кодом країни, щоб отримати код.",
    "Enter a valid phone number, with the country code.": "Введіть коректний номер телефону з кодом країни.",
    "No Telegram account uses this number. Sign-up isn't supported here.": "До цього номера не прив'язано акаунт Telegram. Реєстрація тут не підтримується.",
    "That phone number is not valid.": "Цей номер телефону недійсний.",
    "That phone number is banned from Telegram.": "Цей номер заблоковано в Telegram.",
    "Too many codes requested for this number. Try again later.": "Забагато запитів коду для цього номера. Спробуйте пізніше.",
    "Too many attempts. Try again later.": "Забагато спроб. Спробуйте пізніше.",
    "This build's Telegram API key was rejected.": "Ключ API Telegram цієї збірки відхилено.",
    "Wrong code. Check it and try again.": "Невірний код. Перевірте та спробуйте знову.",
    "The code expired. Request a new one.": "Код застарів. Запросіть новий.",
    "Delete chat": "Видалити чат",
    "Delete for me": "Видалити в мене",
    "Myself": "У мене",
    "All": "У всіх",
    "Delete for all": "Видалити в усіх",
    "Delete the chat \"%1\"? \"All\" also removes it for the other side.": "Видалити чат «%1»? «У всіх» також видалить його у співрозмовника.",
    "Could not change the folder: %1": "Не вдалося змінити теку: %1",
    "That folder must keep at least one chat, so the chat stays in it too.": "У теці має лишатися хоча б один чат, тож чат залишиться і в ній.",
    "That folder no longer exists.": "Цієї теки більше немає.",
    "the proxy refused our authentication method": "проксі відхилив метод автентифікації",
    "proxy authentication failed - check the username and password": "помилка автентифікації проксі — перевірте ім'я користувача та пароль",
    "the proxy sent a malformed reply": "проксі надіслав некоректну відповідь",
    "the proxy could not reach the server (%1)": "проксі не зміг підключитися до сервера (%1)",
    "playing... tap to stop": "відтворення... натисніть, щоб зупинити",
    "loading %1%": "завантаження %1%",
    "tap to play": "натисніть, щоб відтворити",
    "could not open the voice file": "не вдалося відкрити голосовий файл",
    "could not decode the voice message": "не вдалося декодувати голосове повідомлення",
    "audio is unavailable (%1)": "аудіо недоступне (%1)",
    "could not open audio (%1)": "не вдалося відкрити аудіо (%1)",
    "could not prepare playback": "не вдалося підготувати відтворення",
    "could not start playback (%1)": "не вдалося почати відтворення (%1)",
    "could not play (%1)": "не вдалося відтворити (%1)",
    "recording is only available on the phone": "запис доступний лише на телефоні",
    "Proxy: %1": "Проксі: %1",
    "on": "увімк",
    "No connection through the proxy. Check the proxy or tap Reconnect.": "Немає з'єднання через проксі. Перевірте проксі або натисніть «Перепідключитися».",
    "No connection. Tap Reconnect, or set up a proxy if Telegram is blocked.": "Немає з'єднання. Натисніть «Перепідключитися» або налаштуйте проксі, якщо Telegram заблоковано.",
    "Saved photos and files go here. Pick a drive, or \"Choose folder...\" for any folder.": "Сюди зберігаються фото та файли. Виберіть диск або «Вибрати теку...» для будь-якої теки.",
    "Saved photos and files go to a \"Symbigram\" folder on this drive.": "Збережені фото та файли потрапляють у теку «Symbigram» на цьому диску.",
    "End the secret chat with \"%1\"? Its messages live only on this device and will be removed here.": "Завершити секретний чат з «%1»? Його повідомлення зберігаються лише на цьому пристрої та будуть видалені тут.",
    "%1 wants to start a secret chat": "%1 хоче почати секретний чат",
}


def fill(lang, table):
    path = os.path.join(ROOT, "translations", "symbigram_%s.ts" % lang)
    tree = ET.parse(path)
    root = tree.getroot()
    root.set("language", lang)
    missing = []
    for ctx in root.findall("context"):
        for msg in ctx.findall("message"):
            source = msg.find("source").text or ""
            tr = msg.find("translation")
            if tr is None:
                tr = ET.SubElement(msg, "translation")
            if source in table:
                tr.text = table[source]
                if "type" in tr.attrib:
                    del tr.attrib["type"]
            else:
                missing.append(source)
    tree.write(path, encoding="utf-8", xml_declaration=True)
    print("%s: %d untranslated" % (lang, len(missing)))
    for m in missing:
        print("   " + m)


fill("ru", RU)
fill("uk", UK)
