#!/usr/bin/env python3
# Fills translations/symbigram_<lang>.ts from the tables below (source text -> translation).
# Strings not in a table stay untranslated (English) and are listed. Languages: ru, uk, vi, he
# (all full-coverage; he is right-to-left, forced in main.cpp/main.qml).
#
#   lupdate -extensions qml,cpp,h -no-obsolete src qml -ts translations/symbigram_ru.ts translations/symbigram_uk.ts translations/symbigram_vi.ts translations/symbigram_he.ts
#   python tools/translate.py
#   lrelease translations/symbigram_ru.ts translations/symbigram_uk.ts translations/symbigram_vi.ts translations/symbigram_he.ts
import os
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

RU = {
    "version %1": "версия %1",
    "A Telegram client for Symbian Anna/Belle, ported from Lumigram/LumigramPlus for Windows Phone 8.1. It speaks MTProto 2.0 directly to Telegram - no bridge, no proxy; the encryption key is made on the phone.":
        "Telegram-клиент для Symbian Anna/Belle, перенесённый с Lumigram/LumigramPlus для Windows Phone 8.1. Говорит с Telegram напрямую по MTProto 2.0 — без моста и прокси; ключ шифрования создаётся на телефоне.",
    "Sign-in is by QR code only (scan from a signed-in Telegram, plus the two-step password if set). Text messages, photos and files (view, save and send), groups and channels.":
        "Вход только по QR-коду (сканируется из Telegram, где вы уже вошли; плюс пароль двухэтапной проверки, если он есть). Текстовые сообщения, фото и файлы (просмотр, сохранение и отправка), группы и каналы.",
    "Log": "Журнал",
    "Copy log": "Скопировать журнал",
    "Not connected.": "Нет соединения.",
    "Connecting...": "Подключение...",
    "Connecting and creating the encryption key...": "Подключение и создание ключа шифрования...",
    "Checking the password (this takes a few seconds)...": "Проверка пароля (это займёт несколько секунд)...",
    "This account has two-step verification. Enter the password.": "У этого аккаунта включена двухэтапная проверка. Введите пароль.",
    "Requesting a sign-in code...": "Запрос кода для входа...",
    "Waiting for the code to be scanned...": "Ожидание сканирования кода...",
    "Signing in...": "Вход...",
    "Connection lost: %1. Reconnecting...": "Соединение потеряно: %1. Переподключение...",
    "Connection failed: %1. Retrying...": "Не удалось подключиться: %1. Повтор...",
    "Enter the password.": "Введите пароль.",
    "Copied.": "Скопировано.",
    "Load older messages": "Загрузить более старые сообщения",
    "Reload": "Обновить",
    "Unmute": "Включить уведомления",
    "Mute": "Отключить уведомления",
    "Mark as read": "Отметить прочитанным",
    "Copy text": "Скопировать текст",
    "Reply": "Ответить",
    "Replying to": "Ответ на",
    "Edit": "Изменить",
    "Editing message": "Изменение сообщения",
    "edit the text, then tap Save": "измените текст и нажмите «Сохранить»",
    "Save": "Сохранить",
    "Could not edit the message: %1": "Не удалось изменить сообщение: %1",
    "Retry": "Повторить",
    "Delete for me": "Удалить у себя",
    "Delete for everyone": "Удалить у всех",
    "connecting...": "подключение...",
    "offline": "не в сети",
    "online": "в сети",
    "Older messages": "Более старые сообщения",
    "Could not load the messages: %1": "Не удалось загрузить сообщения: %1",
    "No messages yet.": "Сообщений пока нет.",
    "channel - only its admins can post": "канал — писать могут только его администраторы",
    "message": "сообщение",
    "Send": "Отправить",
    "Yesterday": "Вчера",
    "%1 is typing...": "%1 печатает...",
    "typing...": "печатает...",
    "You: %1": "Вы: %1",
    "Connect": "Подключиться",
    "Disconnect": "Отключиться",
    "Settings": "Настройки",
    "About": "О программе",
    "Sign out": "Выход из аккаунта",
    "Exit": "Выход из приложения",
    "Sign out? The session will be ended on Telegram and removed from this phone.": "Выйти из аккаунта? Сеанс будет завершён в Telegram и удалён с этого телефона.",
    "Cancel": "Отмена",
    "New chat": "Новый чат",
    "Find": "Найти",
    "@username, phone number, t.me link, or a contact's name": "@username, номер телефона, ссылка t.me или имя контакта",
    "@username or +phone": "@username или +телефон",
    "Clear history": "Очистить историю",
    "Delete all messages of \"%1\" on Telegram (for you)?": "Удалить все сообщения чата «%1» в Telegram (у себя)?",
    "Delete": "Удалить",
    "loading...": "загрузка...",
    "Older chats": "Более старые чаты",
    "Loading chats...": "Загрузка чатов...",
    "No chats yet. Tap + to find someone.": "Чатов пока нет. Нажмите +, чтобы найти собеседника.",
    "Offline. Use the menu to connect.": "Не в сети. Подключитесь через меню.",
    "Telegram for Symbian": "Telegram для Symbian",
    "No connection. Tap the refresh button to try again.": "Нет соединения. Нажмите кнопку обновления, чтобы повторить.",
    "The code renews in %1 s": "Код обновится через %1 с",
    "Open Telegram on a phone or PC where you are signed in: Settings > Devices > Link Desktop Device, and scan this code.":
        "Откройте Telegram на телефоне или ПК, где вы уже вошли: Настройки > Устройства > Подключить устройство, и отсканируйте этот код.",
    "Two-step verification password": "Пароль двухэтапной проверки",
    "hint: %1": "подсказка: %1",
    "password": "пароль",
    "show password": "показать пароль",
    "checking...": "проверка...",
    "sign in": "войти",
    "Symbigram talks MTProto 2.0 straight to Telegram's servers: the encryption key is made on this phone and never leaves it. The session shows up under Devices in Telegram, where it can be ended at any time.":
        "Symbigram говорит с серверами Telegram напрямую по MTProto 2.0: ключ шифрования создаётся на этом телефоне и никогда его не покидает. Сеанс виден в разделе «Устройства» в Telegram, где его можно завершить в любой момент.",
    "Forwarded from %1": "Переслано от %1",
    "edited": "изменено",
    "Today": "Сегодня",
    "reply": "ответ",
    "You": "Вы",
    "last seen at %1": "был(а) в %1",
    "last seen yesterday at %1": "был(а) вчера в %1",
    "last seen %1": "был(а) %1",
    "last seen recently": "был(а) недавно",
    "last seen within a week": "был(а) на этой неделе",
    "last seen within a month": "был(а) в этом месяце",
    "last seen a long time ago": "был(а) давно",
    "bot": "бот",
    "Saved Messages": "Избранное",
    "channel, %1 subscribers": "канал, подписчиков: %1",
    "channel": "канал",
    "%1 members": "участников: %1",
    "group": "группа",
    "The message was not sent: %1": "Сообщение не отправлено: %1",
    "key exchange failed: %1": "обмен ключами не удался: %1",
    "no response from the server": "сервер не отвечает",
    "connection closed": "соединение закрыто",
    "connection timed out": "время ожидания соединения истекло",
    "Symbigram: new message": "Symbigram: новое сообщение",
    "Symbigram: %1 new messages": "Symbigram: новых сообщений: %1",
    "App language": "Язык приложения",
    "System default": "Как в системе",
    "Notifications": "Уведомления",
    "Popup for new messages": "Всплывающее окно о новых сообщениях",
    "Vibrate": "Вибрация",
    "Groups and channels": "Группы и каналы",
    "For messages that arrive while another application is in front: the \"new messages\" dialog, the popup and the vibration. Chats muted in Telegram stay quiet. Symbigram stays connected in the background either way.":
        "Для сообщений, пришедших, пока открыто другое приложение: диалог «новые сообщения», всплывающее окно и вибрация. Чаты, отключённые в Telegram, остаются беззвучными. Symbigram в любом случае остаётся на связи в фоне.",
    "Connect on start": "Подключаться при запуске",
    "Takes effect after the app is restarted.": "Вступает в силу после перезапуска приложения.",
    "Signed out.": "Выход выполнен.",
    "Enter a username, a phone number or a name.": "Введите имя пользователя, номер телефона или имя.",
    "This account has no password set.": "У этого аккаунта нет пароля.",
    "Unsupported password method.": "Неподдерживаемый способ проверки пароля.",
    "Nobody found.": "Никого не найдено.",
    "The session was ended (%1). Please sign in again.": "Сеанс завершён (%1). Войдите снова.",
    "Wrong password.": "Неверный пароль.",
    "Too many attempts. Wait %1 seconds.": "Слишком много попыток. Подождите %1 с.",
    "Could not load the chat list: %1": "Не удалось загрузить список чатов: %1",
    "user %1": "пользователь %1",
    "chat %1": "чат %1",
    "deleted account": "удалённый аккаунт",
    "video": "видео",
    "photo": "фото",
    "location %1, %2": "геопозиция %1, %2",
    "location": "геопозиция",
    "location: %1": "место: %1",
    "contact: %1 %2 %3": "контакт: %1 %2 %3",
    "poll: %1": "опрос: %1",
    "dice: %1": "кубик: %1",
    "game": "игра",
    "invoice": "счёт",
    "story": "история",
    "file": "файл",
    "sticker": "стикер",
    "sticker %1": "стикер %1",
    "voice message %1": "голосовое сообщение %1",
    "voice message": "голосовое сообщение",
    "video message %1": "видеосообщение %1",
    "video message": "видеосообщение",
    "GIF": "GIF",
    "video %1": "видео %1",
    "audio %1": "аудио %1",
    "audio": "аудио",
    "image": "изображение",
    "%1 MB": "%1 МБ",
    "%1 KB": "%1 КБ",
    "%1 B": "%1 Б",
    "file: %1 (%2)": "файл: %1 (%2)",
    "unsupported attachment": "неподдерживаемое вложение",
    "attachment": "вложение",
    "created the group \"%1\"": "создал(а) группу «%1»",
    "created the channel \"%1\"": "создал(а) канал «%1»",
    "added %1": "добавил(а) %1",
    "removed %1": "удалил(а) %1",
    "joined by invite link": "вступил(а) по ссылке-приглашению",
    "pinned a message": "закрепил(а) сообщение",
    "joined Telegram": "присоединился(-ась) к Telegram",
    "cleared the history": "очистил(а) историю",
    "service message": "служебное сообщение",
    "empty message": "пустое сообщение",
    "Folders": "Папки",
    "Folder": "Папка",
    "All chats": "Все чаты",
    "Archive": "Архив",
    "tap to switch folder": "нажмите, чтобы сменить папку",
    "The archive is empty.": "Архив пуст.",
    "No chats in this folder.": "В этой папке нет чатов.",
    "Keep a log": "Вести журнал",
    "Off by default. Turn it on only to collect a diagnostic log (shown on the About page) when something goes wrong.": "По умолчанию выключено. Включайте только для сбора диагностического журнала (виден на странице «О программе»), когда что-то идёт не так.",
    "Logging is off. Turn on \"Keep a log\" in Settings to collect one.": "Журнал выключен. Включите «Вести журнал» в настройках, чтобы собрать его.",
    "Images (*.jpg *.jpeg *.png *.gif *.bmp)": "Изображения (*.jpg *.jpeg *.png *.gif *.bmp)",
    "All files (*)": "Все файлы (*)",
    "Choose an image": "Выберите изображение",
    "Send image": "Отправить изображение",
    "Send file": "Отправить файл",
    "Caption (optional)": "Подпись (необязательно)",
    "add a caption": "добавьте подпись",
    "Choose a file": "Выберите файл",
    "Sending the image...": "Отправка изображения...",
    "Sending the file...": "Отправка файла...",
    "Image": "Изображение",
    "File": "Файл",
    "Save to phone": "Сохранить в телефон",
    "Open": "Открыть",
    "Save": "Сохранить",
    "Close": "Закрыть",
    "Tap to load": "Нажмите, чтобы загрузить",
    "Failed - tap to retry": "Ошибка — нажмите, чтобы повторить",
    "Voice message": "Голосовое сообщение",
    "Video": "Видео",
    "tap to open": "нажмите, чтобы открыть",
    "downloading %1%": "загрузка %1%",
    "tap to download": "нажмите, чтобы скачать",
    "Saved to %1": "Сохранено в %1",
    "Could not save the file.": "Не удалось сохранить файл.",
    "the server rejected a part of the file": "сервер отклонил часть файла",
    "the file is served from a CDN, which is not supported": "файл раздаётся через CDN, что не поддерживается",
    "unexpected reply": "неожиданный ответ",
    "could not write the file": "не удалось записать файл",
    "could not create the file": "не удалось создать файл",
    "the file is empty": "файл пуст",
    "could not read the file": "не удалось прочитать файл",
    "the file is too large": "файл слишком большой",
    "Start secret chat": "Начать секретный чат",
    "Verify encryption key": "Проверить ключ шифрования",
    "Self-destruct timer": "Таймер самоуничтожения",
    "Delete secret chat": "Удалить секретный чат",
    "End this secret chat? Its messages, which live only on this device, will be removed here.": "Завершить этот секретный чат? Его сообщения, которые хранятся только на этом устройстве, будут удалены здесь.",
    "Encryption key": "Ключ шифрования",
    "If this key matches on both phones, no one is intercepting the chat. Compare it with %1 in person or over a trusted channel.": "Если этот ключ совпадает на обоих телефонах, чат никто не перехватывает. Сравните его с %1 лично или по надёжному каналу.",
    "%1 wants to start an end-to-end encrypted chat.": "%1 хочет начать сквозной зашифрованный чат.",
    "Waiting for the other side to come online and accept...": "Ожидание, пока собеседник выйдет в сеть и примет запрос...",
    "Decline": "Отклонить",
    "Cancel request": "Отменить запрос",
    "encrypted message": "зашифрованное сообщение",
    "secret chat": "секретный чат",
    "wants to start a secret chat": "хочет начать секретный чат",
    "waiting to be accepted...": "ожидает подтверждения...",
    "end-to-end encrypted": "сквозное шифрование",
    "end-to-end encrypted, self-destruct %1s": "сквозное шифрование, самоуничтожение %1с",
    "Secret chats can only be opened with a person.": "Секретные чаты можно открывать только с человеком.",
    "The secret chat is not ready.": "Секретный чат не готов.",
    "Secret chats can only be started with a person.": "Секретные чаты можно начинать только с человеком.",
    "Starting a secret chat...": "Создание секретного чата...",
    "Someone wants to start a secret chat.": "Кто-то хочет начать секретный чат.",
    "%1 wants to start a secret chat.": "%1 хочет начать секретный чат.",
    "Secret chat is ready.": "Секретный чат готов.",
    "Secret chat": "Секретный чат",
    "Encrypted message": "Зашифрованное сообщение",
    "Could not start the secret chat: %1": "Не удалось начать секретный чат: %1",
    "Could not accept the secret chat: %1": "Не удалось принять секретный чат: %1",
    "Accept": "Принять",
    "Off": "Выкл.",
    "5 seconds": "5 секунд",
    "30 seconds": "30 секунд",
    "1 minute": "1 минута",
    "1 hour": "1 час",
    "1 day": "1 день",
    "1 week": "1 неделя",
    "Saved": "Сохранено",
    "File saved to: %1": "Файл сохранён: %1",
    "Could not save the file to %1": "Не удалось сохранить файл в %1",
    "Could not open the file.": "Не удалось открыть файл.",
    "Phone memory": "Память телефона",
    "Mass memory": "Массовая память",
    "Memory card": "Карта памяти",
    "Save downloads to": "Сохранять загрузки в",
    "Clear cache": "Очистить кэш",
    "Clear": "Очистить",
    "Downloaded media held on the phone: %1": "Загруженные медиа на телефоне: %1",
    "The app's private store of downloaded photos, avatars and files (separate from the folder above). Clearing it just re-downloads on demand.": "Внутреннее хранилище загруженных фото, аватаров и файлов (отдельно от папки выше). После очистки они будут загружаться заново по мере необходимости.",
    "Delete the %1 of downloaded media held on the phone? It will be fetched again when needed.": "Удалить %1 загруженных медиа на телефоне? Они будут загружены заново при необходимости.",
    "Cache cleared (%1 freed).": "Кэш очищен (освобождено %1).",
    "Choose folder...": "Выбрать папку...",
    "Choose download folder": "Выберите папку загрузок",
    "SOCKS5 proxy": "SOCKS5-прокси",
    "Proxy server": "Сервер прокси",
    "not set": "не задан",
    "Route the connection through a SOCKS5 proxy. Changing it reconnects.": "Направлять соединение через SOCKS5-прокси. Изменение переподключает.",
    "Server": "Сервер",
    "host or IP": "хост или IP",
    "Port": "Порт",
    "Username (optional)": "Имя пользователя (необязательно)",
    "Password (optional)": "Пароль (необязательно)",
    "Reconnect": "Переподключиться",
    "Enable": "Включить",
    "Set up proxy": "Настроить прокси",
    "Cannot record a voice message here.": "Здесь нельзя записать голосовое сообщение.",
    "Sending the voice message...": "Отправка голосового сообщения...",
    "the microphone is unavailable (%1)": "микрофон недоступен (%1)",
    "could not open the microphone (%1)": "не удалось открыть микрофон (%1)",
    "could not start recording (%1)": "не удалось начать запись (%1)",
    "the recording was too short": "запись слишком короткая",
    "could not encode the recording": "не удалось закодировать запись",
    "could not save the recording": "не удалось сохранить запись",
    "could not read the recording": "не удалось прочитать запись",
    "Archive chat": "Архивировать чат",
    "Unarchive chat": "Разархивировать чат",
    "Move to folder": "Переместить в папку",
    "All chats (no folder)": "Все чаты (без папки)",
    "Sign in with QR code": "Войти по QR-коду",
    "Sign in with phone number": "Войти по номеру телефона",
    "Use QR code instead": "Использовать QR-код",
    "Phone number": "Номер телефона",
    "Include the country code. Telegram will send a login code to this number.": "Укажите код страны. Telegram пришлёт на этот номер код для входа.",
    "requesting...": "запрос...",
    "send code": "отправить код",
    "Enter the code sent to %1": "Введите код, отправленный на %1",
    "code": "код",
    "signing in...": "вход...",
    "Resend code": "Отправить код снова",
    "Change number": "Изменить номер",
    "Enter your phone number.": "Введите номер телефона.",
    "Enter the code.": "Введите код.",
    "Enter the code Telegram sent to %1.": "Введите код, который Telegram отправил на %1.",
    "Requesting a code...": "Запрос кода...",
    "Enter your phone number, with the country code, to get a code.": "Введите номер телефона с кодом страны, чтобы получить код.",
    "Enter a valid phone number, with the country code.": "Введите корректный номер телефона с кодом страны.",
    "No Telegram account uses this number. Sign-up isn't supported here.": "К этому номеру не привязан аккаунт Telegram. Регистрация здесь не поддерживается.",
    "That phone number is not valid.": "Этот номер телефона недействителен.",
    "That phone number is banned from Telegram.": "Этот номер заблокирован в Telegram.",
    "Too many codes requested for this number. Try again later.": "Слишком много запросов кода для этого номера. Повторите позже.",
    "Too many attempts. Try again later.": "Слишком много попыток. Повторите позже.",
    "This build's Telegram API key was rejected.": "Ключ API Telegram этой сборки отклонён.",
    "Wrong code. Check it and try again.": "Неверный код. Проверьте и попробуйте снова.",
    "The code expired. Request a new one.": "Код истёк. Запросите новый.",
    "Delete chat": "Удалить чат",
    "Delete for me": "Удалить у меня",
    "Myself": "У меня",
    "All": "У всех",
    "Delete for all": "Удалить у всех",
    "Delete the chat \"%1\"? \"All\" also removes it for the other side.": "Удалить чат «%1»? «У всех» также удалит его у собеседника.",
    "Could not change the folder: %1": "Не удалось изменить папку: %1",
    "That folder must keep at least one chat, so the chat stays in it too.": "В папке должен остаться хотя бы один чат, поэтому чат останется и в ней.",
    "That folder no longer exists.": "Этой папки больше нет.",
    "the proxy refused our authentication method": "прокси отклонил метод аутентификации",
    "proxy authentication failed - check the username and password": "ошибка аутентификации прокси — проверьте имя пользователя и пароль",
    "the proxy sent a malformed reply": "прокси прислал некорректный ответ",
    "the proxy could not reach the server (%1)": "прокси не смог подключиться к серверу (%1)",
    "playing... tap to stop": "воспроизведение... нажмите, чтобы остановить",
    "loading %1%": "загрузка %1%",
    "tap to play": "нажмите, чтобы воспроизвести",
    "tap to play in player": "нажмите, чтобы открыть в плеере",
    "buffering %1%... opening player": "буферизация %1%... открываю плеер",
    "Could not play this audio: %1": "Не удалось воспроизвести аудио: %1",
    "could not open the voice file": "не удалось открыть голосовой файл",
    "could not decode the voice message": "не удалось декодировать голосовое сообщение",
    "audio is unavailable (%1)": "аудио недоступно (%1)",
    "could not open audio (%1)": "не удалось открыть аудио (%1)",
    "could not prepare playback": "не удалось подготовить воспроизведение",
    "could not start playback (%1)": "не удалось начать воспроизведение (%1)",
    "could not play (%1)": "не удалось воспроизвести (%1)",
    "recording is only available on the phone": "запись доступна только на телефоне",
    "Proxy: %1": "Прокси: %1",
    "on": "вкл",
    "No connection through the proxy. Check the proxy or tap Reconnect.": "Нет соединения через прокси. Проверьте прокси или нажмите «Переподключиться».",
    "No connection. Tap Reconnect, or set up a proxy if Telegram is blocked.": "Нет соединения. Нажмите «Переподключиться» или настройте прокси, если Telegram заблокирован.",
    "Saved photos and files go here. Pick a drive, or \"Choose folder...\" for any folder.": "Сюда сохраняются фото и файлы. Выберите диск или «Выбрать папку...» для любой папки.",
    "Saved photos and files go to a \"Symbigram\" folder on this drive.": "Сохранённые фото и файлы попадают в папку «Symbigram» на этом диске.",
    "End the secret chat with \"%1\"? Its messages live only on this device and will be removed here.": "Завершить секретный чат с «%1»? Его сообщения хранятся только на этом устройстве и будут удалены здесь.",
    "%1 wants to start a secret chat": "%1 хочет начать секретный чат",
}

UK = {
    "version %1": "версія %1",
    "A Telegram client for Symbian Anna/Belle, ported from Lumigram/LumigramPlus for Windows Phone 8.1. It speaks MTProto 2.0 directly to Telegram - no bridge, no proxy; the encryption key is made on the phone.":
        "Telegram-клієнт для Symbian Anna/Belle, перенесений із Lumigram/LumigramPlus для Windows Phone 8.1. Спілкується з Telegram напряму по MTProto 2.0 — без мосту та проксі; ключ шифрування створюється на телефоні.",
    "Sign-in is by QR code only (scan from a signed-in Telegram, plus the two-step password if set). Text messages, photos and files (view, save and send), groups and channels.":
        "Вхід лише за QR-кодом (сканується з Telegram, де ви вже увійшли; плюс пароль двоетапної перевірки, якщо він є). Текстові повідомлення, фото та файли (перегляд, збереження й надсилання), групи та канали.",
    "Log": "Журнал",
    "Copy log": "Скопіювати журнал",
    "Not connected.": "Немає з'єднання.",
    "Connecting...": "Підключення...",
    "Connecting and creating the encryption key...": "Підключення та створення ключа шифрування...",
    "Checking the password (this takes a few seconds)...": "Перевірка пароля (це займе кілька секунд)...",
    "This account has two-step verification. Enter the password.": "У цього облікового запису ввімкнено двоетапну перевірку. Введіть пароль.",
    "Requesting a sign-in code...": "Запит коду для входу...",
    "Waiting for the code to be scanned...": "Очікування сканування коду...",
    "Signing in...": "Вхід...",
    "Connection lost: %1. Reconnecting...": "З'єднання втрачено: %1. Перепідключення...",
    "Connection failed: %1. Retrying...": "Не вдалося підключитися: %1. Повтор...",
    "Enter the password.": "Введіть пароль.",
    "Copied.": "Скопійовано.",
    "Load older messages": "Завантажити старіші повідомлення",
    "Reload": "Оновити",
    "Unmute": "Увімкнути сповіщення",
    "Mute": "Вимкнути сповіщення",
    "Mark as read": "Позначити прочитаним",
    "Copy text": "Скопіювати текст",
    "Reply": "Відповісти",
    "Replying to": "Відповідь на",
    "Edit": "Змінити",
    "Editing message": "Редагування повідомлення",
    "edit the text, then tap Save": "змініть текст і натисніть «Зберегти»",
    "Save": "Зберегти",
    "Could not edit the message: %1": "Не вдалося змінити повідомлення: %1",
    "Retry": "Повторити",
    "Delete for me": "Видалити в себе",
    "Delete for everyone": "Видалити в усіх",
    "connecting...": "підключення...",
    "offline": "не в мережі",
    "online": "у мережі",
    "Older messages": "Старіші повідомлення",
    "Could not load the messages: %1": "Не вдалося завантажити повідомлення: %1",
    "No messages yet.": "Повідомлень поки немає.",
    "channel - only its admins can post": "канал — писати можуть лише його адміністратори",
    "message": "повідомлення",
    "Send": "Надіслати",
    "Yesterday": "Вчора",
    "%1 is typing...": "%1 друкує...",
    "typing...": "друкує...",
    "You: %1": "Ви: %1",
    "Connect": "Підключитися",
    "Disconnect": "Відключитися",
    "Settings": "Налаштування",
    "About": "Про програму",
    "Sign out": "Вихід з облікового запису",
    "Exit": "Вихід із застосунку",
    "Sign out? The session will be ended on Telegram and removed from this phone.": "Вийти з облікового запису? Сеанс буде завершено в Telegram і видалено з цього телефону.",
    "Cancel": "Скасувати",
    "New chat": "Новий чат",
    "Find": "Знайти",
    "@username, phone number, t.me link, or a contact's name": "@username, номер телефону, посилання t.me або ім'я контакту",
    "@username or +phone": "@username або +телефон",
    "Clear history": "Очистити історію",
    "Delete all messages of \"%1\" on Telegram (for you)?": "Видалити всі повідомлення чату «%1» у Telegram (у себе)?",
    "Delete": "Видалити",
    "loading...": "завантаження...",
    "Older chats": "Старіші чати",
    "Loading chats...": "Завантаження чатів...",
    "No chats yet. Tap + to find someone.": "Чатів поки немає. Натисніть +, щоб знайти співрозмовника.",
    "Offline. Use the menu to connect.": "Не в мережі. Підключіться через меню.",
    "Telegram for Symbian": "Telegram для Symbian",
    "No connection. Tap the refresh button to try again.": "Немає з'єднання. Натисніть кнопку оновлення, щоб повторити.",
    "The code renews in %1 s": "Код оновиться через %1 с",
    "Open Telegram on a phone or PC where you are signed in: Settings > Devices > Link Desktop Device, and scan this code.":
        "Відкрийте Telegram на телефоні або ПК, де ви вже увійшли: Налаштування > Пристрої > Підключити пристрій, і відскануйте цей код.",
    "Two-step verification password": "Пароль двоетапної перевірки",
    "hint: %1": "підказка: %1",
    "password": "пароль",
    "show password": "показати пароль",
    "checking...": "перевірка...",
    "sign in": "увійти",
    "Symbigram talks MTProto 2.0 straight to Telegram's servers: the encryption key is made on this phone and never leaves it. The session shows up under Devices in Telegram, where it can be ended at any time.":
        "Symbigram спілкується із серверами Telegram напряму по MTProto 2.0: ключ шифрування створюється на цьому телефоні й ніколи його не залишає. Сеанс видно в розділі «Пристрої» в Telegram, де його можна завершити будь-коли.",
    "Forwarded from %1": "Переслано від %1",
    "edited": "змінено",
    "Today": "Сьогодні",
    "reply": "відповідь",
    "You": "Ви",
    "last seen at %1": "був(ла) о %1",
    "last seen yesterday at %1": "був(ла) вчора о %1",
    "last seen %1": "був(ла) %1",
    "last seen recently": "був(ла) нещодавно",
    "last seen within a week": "був(ла) цього тижня",
    "last seen within a month": "був(ла) цього місяця",
    "last seen a long time ago": "був(ла) давно",
    "bot": "бот",
    "Saved Messages": "Збережене",
    "channel, %1 subscribers": "канал, підписників: %1",
    "channel": "канал",
    "%1 members": "учасників: %1",
    "group": "група",
    "The message was not sent: %1": "Повідомлення не надіслано: %1",
    "key exchange failed: %1": "обмін ключами не вдався: %1",
    "no response from the server": "сервер не відповідає",
    "connection closed": "з'єднання закрито",
    "connection timed out": "час очікування з'єднання минув",
    "Symbigram: new message": "Symbigram: нове повідомлення",
    "Symbigram: %1 new messages": "Symbigram: нових повідомлень: %1",
    "App language": "Мова програми",
    "System default": "Як у системі",
    "Notifications": "Сповіщення",
    "Popup for new messages": "Спливаюче вікно про нові повідомлення",
    "Vibrate": "Вібрація",
    "Groups and channels": "Групи та канали",
    "For messages that arrive while another application is in front: the \"new messages\" dialog, the popup and the vibration. Chats muted in Telegram stay quiet. Symbigram stays connected in the background either way.":
        "Для повідомлень, що надійшли, поки відкрито іншу програму: діалог «нові повідомлення», спливаюче вікно та вібрація. Чати, вимкнені в Telegram, лишаються беззвучними. Symbigram у будь-якому разі лишається на зв'язку у фоні.",
    "Connect on start": "Підключатися під час запуску",
    "Takes effect after the app is restarted.": "Набуде чинності після перезапуску програми.",
    "Signed out.": "Вихід виконано.",
    "Enter a username, a phone number or a name.": "Введіть ім'я користувача, номер телефону або ім'я.",
    "This account has no password set.": "У цього облікового запису немає пароля.",
    "Unsupported password method.": "Непідтримуваний спосіб перевірки пароля.",
    "Nobody found.": "Нікого не знайдено.",
    "The session was ended (%1). Please sign in again.": "Сеанс завершено (%1). Увійдіть знову.",
    "Wrong password.": "Неправильний пароль.",
    "Too many attempts. Wait %1 seconds.": "Забагато спроб. Зачекайте %1 с.",
    "Could not load the chat list: %1": "Не вдалося завантажити список чатів: %1",
    "user %1": "користувач %1",
    "chat %1": "чат %1",
    "deleted account": "видалений обліковий запис",
    "video": "відео",
    "photo": "фото",
    "location %1, %2": "геопозиція %1, %2",
    "location": "геопозиція",
    "location: %1": "місце: %1",
    "contact: %1 %2 %3": "контакт: %1 %2 %3",
    "poll: %1": "опитування: %1",
    "dice: %1": "кубик: %1",
    "game": "гра",
    "invoice": "рахунок",
    "story": "історія",
    "file": "файл",
    "sticker": "стікер",
    "sticker %1": "стікер %1",
    "voice message %1": "голосове повідомлення %1",
    "voice message": "голосове повідомлення",
    "video message %1": "відеоповідомлення %1",
    "video message": "відеоповідомлення",
    "GIF": "GIF",
    "video %1": "відео %1",
    "audio %1": "аудіо %1",
    "audio": "аудіо",
    "image": "зображення",
    "%1 MB": "%1 МБ",
    "%1 KB": "%1 КБ",
    "%1 B": "%1 Б",
    "file: %1 (%2)": "файл: %1 (%2)",
    "unsupported attachment": "непідтримуване вкладення",
    "attachment": "вкладення",
    "created the group \"%1\"": "створив(ла) групу «%1»",
    "created the channel \"%1\"": "створив(ла) канал «%1»",
    "added %1": "додав(ла) %1",
    "removed %1": "видалив(ла) %1",
    "joined by invite link": "приєднався(-лась) за посиланням-запрошенням",
    "pinned a message": "закріпив(ла) повідомлення",
    "joined Telegram": "приєднався(-лась) до Telegram",
    "cleared the history": "очистив(ла) історію",
    "service message": "службове повідомлення",
    "empty message": "порожнє повідомлення",
    "Folders": "Теки",
    "tap to switch folder": "натисніть, щоб змінити теку",
    "Folder": "Тека",
    "All chats": "Усі чати",
    "Archive": "Архів",
    "tap the menu to change folder": "натисніть меню, щоб змінити теку",
    "The archive is empty.": "Архів порожній.",
    "No chats in this folder.": "У цій теці немає чатів.",
    "Keep a log": "Вести журнал",
    "Off by default. Turn it on only to collect a diagnostic log (shown on the About page) when something goes wrong.": "Типово вимкнено. Вмикайте лише для збору діагностичного журналу (видно на сторінці «Про програму»), коли щось іде не так.",
    "Logging is off. Turn on \"Keep a log\" in Settings to collect one.": "Журнал вимкнено. Увімкніть «Вести журнал» у налаштуваннях, щоб зібрати його.",
    "Images (*.jpg *.jpeg *.png *.gif *.bmp)": "Зображення (*.jpg *.jpeg *.png *.gif *.bmp)",
    "All files (*)": "Усі файли (*)",
    "Choose an image": "Виберіть зображення",
    "Send image": "Надіслати зображення",
    "Send file": "Надіслати файл",
    "Caption (optional)": "Підпис (необов'язково)",
    "add a caption": "додайте підпис",
    "Choose a file": "Виберіть файл",
    "Sending the image...": "Надсилання зображення...",
    "Sending the file...": "Надсилання файлу...",
    "Image": "Зображення",
    "File": "Файл",
    "Save to phone": "Зберегти в телефон",
    "Open": "Відкрити",
    "Save": "Зберегти",
    "Close": "Закрити",
    "Tap to load": "Натисніть, щоб завантажити",
    "Failed - tap to retry": "Помилка — натисніть, щоб повторити",
    "Voice message": "Голосове повідомлення",
    "Video": "Відео",
    "tap to open": "натисніть, щоб відкрити",
    "downloading %1%": "завантаження %1%",
    "tap to download": "натисніть, щоб завантажити",
    "Saved to %1": "Збережено в %1",
    "Could not save the file.": "Не вдалося зберегти файл.",
    "the server rejected a part of the file": "сервер відхилив частину файлу",
    "the file is served from a CDN, which is not supported": "файл роздається через CDN, що не підтримується",
    "unexpected reply": "неочікувана відповідь",
    "could not write the file": "не вдалося записати файл",
    "could not create the file": "не вдалося створити файл",
    "the file is empty": "файл порожній",
    "could not read the file": "не вдалося прочитати файл",
    "the file is too large": "файл завеликий",
    "Start secret chat": "Почати секретний чат",
    "Verify encryption key": "Перевірити ключ шифрування",
    "Self-destruct timer": "Таймер самознищення",
    "Delete secret chat": "Видалити секретний чат",
    "End this secret chat? Its messages, which live only on this device, will be removed here.": "Завершити цей секретний чат? Його повідомлення, що зберігаються лише на цьому пристрої, будуть видалені тут.",
    "Encryption key": "Ключ шифрування",
    "If this key matches on both phones, no one is intercepting the chat. Compare it with %1 in person or over a trusted channel.": "Якщо цей ключ збігається на обох телефонах, чат ніхто не перехоплює. Порівняйте його з %1 особисто або надійним каналом.",
    "%1 wants to start an end-to-end encrypted chat.": "%1 хоче почати наскрізно зашифрований чат.",
    "Waiting for the other side to come online and accept...": "Очікування, поки співрозмовник вийде в мережу та прийме запит...",
    "Decline": "Відхилити",
    "Cancel request": "Скасувати запит",
    "encrypted message": "зашифроване повідомлення",
    "secret chat": "секретний чат",
    "wants to start a secret chat": "хоче почати секретний чат",
    "waiting to be accepted...": "очікує підтвердження...",
    "end-to-end encrypted": "наскрізне шифрування",
    "end-to-end encrypted, self-destruct %1s": "наскрізне шифрування, самознищення %1с",
    "Secret chats can only be opened with a person.": "Секретні чати можна відкривати лише з людиною.",
    "The secret chat is not ready.": "Секретний чат не готовий.",
    "Secret chats can only be started with a person.": "Секретні чати можна починати лише з людиною.",
    "Starting a secret chat...": "Створення секретного чату...",
    "Someone wants to start a secret chat.": "Хтось хоче почати секретний чат.",
    "%1 wants to start a secret chat.": "%1 хоче почати секретний чат.",
    "Secret chat is ready.": "Секретний чат готовий.",
    "Secret chat": "Секретний чат",
    "Encrypted message": "Зашифроване повідомлення",
    "Could not start the secret chat: %1": "Не вдалося почати секретний чат: %1",
    "Could not accept the secret chat: %1": "Не вдалося прийняти секретний чат: %1",
    "Accept": "Прийняти",
    "Off": "Вимк.",
    "5 seconds": "5 секунд",
    "30 seconds": "30 секунд",
    "1 minute": "1 хвилина",
    "1 hour": "1 година",
    "1 day": "1 день",
    "1 week": "1 тиждень",
    "Saved": "Збережено",
    "File saved to: %1": "Файл збережено: %1",
    "Could not save the file to %1": "Не вдалося зберегти файл у %1",
    "Could not open the file.": "Не вдалося відкрити файл.",
    "Phone memory": "Пам'ять телефону",
    "Mass memory": "Масова пам'ять",
    "Memory card": "Картка пам'яті",
    "Save downloads to": "Зберігати завантаження в",
    "Clear cache": "Очистити кеш",
    "Clear": "Очистити",
    "Downloaded media held on the phone: %1": "Завантажені медіа на телефоні: %1",
    "The app's private store of downloaded photos, avatars and files (separate from the folder above). Clearing it just re-downloads on demand.": "Внутрішнє сховище завантажених фото, аватарів і файлів (окремо від теки вище). Після очищення вони завантажаться знову за потреби.",
    "Delete the %1 of downloaded media held on the phone? It will be fetched again when needed.": "Видалити %1 завантажених медіа на телефоні? Їх буде завантажено знову за потреби.",
    "Cache cleared (%1 freed).": "Кеш очищено (звільнено %1).",
    "Choose folder...": "Вибрати теку...",
    "Choose download folder": "Виберіть теку завантажень",
    "SOCKS5 proxy": "SOCKS5-проксі",
    "Proxy server": "Сервер проксі",
    "not set": "не задано",
    "Route the connection through a SOCKS5 proxy. Changing it reconnects.": "Спрямовувати з'єднання через SOCKS5-проксі. Зміна перепідключає.",
    "Server": "Сервер",
    "host or IP": "хост або IP",
    "Port": "Порт",
    "Username (optional)": "Ім'я користувача (необов'язково)",
    "Password (optional)": "Пароль (необов'язково)",
    "Reconnect": "Перепідключитися",
    "Enable": "Увімкнути",
    "Set up proxy": "Налаштувати проксі",
    "Cannot record a voice message here.": "Тут не можна записати голосове повідомлення.",
    "Sending the voice message...": "Надсилання голосового повідомлення...",
    "the microphone is unavailable (%1)": "мікрофон недоступний (%1)",
    "could not open the microphone (%1)": "не вдалося відкрити мікрофон (%1)",
    "could not start recording (%1)": "не вдалося почати запис (%1)",
    "the recording was too short": "запис занадто короткий",
    "could not encode the recording": "не вдалося закодувати запис",
    "could not save the recording": "не вдалося зберегти запис",
    "could not read the recording": "не вдалося прочитати запис",
    "Archive chat": "Архівувати чат",
    "Unarchive chat": "Розархівувати чат",
    "Move to folder": "Перемістити в теку",
    "All chats (no folder)": "Усі чати (без теки)",
    "Sign in with QR code": "Увійти за QR-кодом",
    "Sign in with phone number": "Увійти за номером телефону",
    "Use QR code instead": "Використати QR-код",
    "Phone number": "Номер телефону",
    "Include the country code. Telegram will send a login code to this number.": "Вкажіть код країни. Telegram надішле на цей номер код для входу.",
    "requesting...": "запит...",
    "send code": "надіслати код",
    "Enter the code sent to %1": "Введіть код, надісланий на %1",
    "code": "код",
    "signing in...": "вхід...",
    "Resend code": "Надіслати код знову",
    "Change number": "Змінити номер",
    "Enter your phone number.": "Введіть номер телефону.",
    "Enter the code.": "Введіть код.",
    "Enter the code Telegram sent to %1.": "Введіть код, який Telegram надіслав на %1.",
    "Requesting a code...": "Запит коду...",
    "Enter your phone number, with the country code, to get a code.": "Введіть номер телефону з кодом країни, щоб отримати код.",
    "Enter a valid phone number, with the country code.": "Введіть коректний номер телефону з кодом країни.",
    "No Telegram account uses this number. Sign-up isn't supported here.": "До цього номера не прив'язано акаунт Telegram. Реєстрація тут не підтримується.",
    "That phone number is not valid.": "Цей номер телефону недійсний.",
    "That phone number is banned from Telegram.": "Цей номер заблоковано в Telegram.",
    "Too many codes requested for this number. Try again later.": "Забагато запитів коду для цього номера. Спробуйте пізніше.",
    "Too many attempts. Try again later.": "Забагато спроб. Спробуйте пізніше.",
    "This build's Telegram API key was rejected.": "Ключ API Telegram цієї збірки відхилено.",
    "Wrong code. Check it and try again.": "Невірний код. Перевірте та спробуйте знову.",
    "The code expired. Request a new one.": "Код застарів. Запросіть новий.",
    "Delete chat": "Видалити чат",
    "Delete for me": "Видалити в мене",
    "Myself": "У мене",
    "All": "У всіх",
    "Delete for all": "Видалити в усіх",
    "Delete the chat \"%1\"? \"All\" also removes it for the other side.": "Видалити чат «%1»? «У всіх» також видалить його у співрозмовника.",
    "Could not change the folder: %1": "Не вдалося змінити теку: %1",
    "That folder must keep at least one chat, so the chat stays in it too.": "У теці має лишатися хоча б один чат, тож чат залишиться і в ній.",
    "That folder no longer exists.": "Цієї теки більше немає.",
    "the proxy refused our authentication method": "проксі відхилив метод автентифікації",
    "proxy authentication failed - check the username and password": "помилка автентифікації проксі — перевірте ім'я користувача та пароль",
    "the proxy sent a malformed reply": "проксі надіслав некоректну відповідь",
    "the proxy could not reach the server (%1)": "проксі не зміг підключитися до сервера (%1)",
    "playing... tap to stop": "відтворення... натисніть, щоб зупинити",
    "loading %1%": "завантаження %1%",
    "tap to play": "натисніть, щоб відтворити",
    "tap to play in player": "натисніть, щоб відкрити у плеєрі",
    "buffering %1%... opening player": "буферизація %1%... відкриваю плеєр",
    "Could not play this audio: %1": "Не вдалося відтворити аудіо: %1",
    "could not open the voice file": "не вдалося відкрити голосовий файл",
    "could not decode the voice message": "не вдалося декодувати голосове повідомлення",
    "audio is unavailable (%1)": "аудіо недоступне (%1)",
    "could not open audio (%1)": "не вдалося відкрити аудіо (%1)",
    "could not prepare playback": "не вдалося підготувати відтворення",
    "could not start playback (%1)": "не вдалося почати відтворення (%1)",
    "could not play (%1)": "не вдалося відтворити (%1)",
    "recording is only available on the phone": "запис доступний лише на телефоні",
    "Proxy: %1": "Проксі: %1",
    "on": "увімк",
    "No connection through the proxy. Check the proxy or tap Reconnect.": "Немає з'єднання через проксі. Перевірте проксі або натисніть «Перепідключитися».",
    "No connection. Tap Reconnect, or set up a proxy if Telegram is blocked.": "Немає з'єднання. Натисніть «Перепідключитися» або налаштуйте проксі, якщо Telegram заблоковано.",
    "Saved photos and files go here. Pick a drive, or \"Choose folder...\" for any folder.": "Сюди зберігаються фото та файли. Виберіть диск або «Вибрати теку...» для будь-якої теки.",
    "Saved photos and files go to a \"Symbigram\" folder on this drive.": "Збережені фото та файли потрапляють у теку «Symbigram» на цьому диску.",
    "End the secret chat with \"%1\"? Its messages live only on this device and will be removed here.": "Завершити секретний чат з «%1»? Його повідомлення зберігаються лише на цьому пристрої та будуть видалені тут.",
    "%1 wants to start a secret chat": "%1 хоче почати секретний чат",
}

# Vietnamese and Hebrew now cover the WHOLE app (parity with RU/UK). Hebrew is RTL - the app
# forces right-to-left layout when "he" is selected (main.cpp setLayoutDirection + main.qml
# LayoutMirroring). "OK" and the "+1 555 123 4567" example number are left untranslated, as in RU/UK.
VI = {
    "version %1": "phiên bản %1",
    "A Telegram client for Symbian Anna/Belle, ported from Lumigram/LumigramPlus for Windows Phone 8.1. It speaks MTProto 2.0 directly to Telegram - no bridge, no proxy; the encryption key is made on the phone.":
        "Một ứng dụng Telegram cho Symbian Anna/Belle, được chuyển từ Lumigram/LumigramPlus cho Windows Phone 8.1. Nó giao tiếp MTProto 2.0 trực tiếp với Telegram — không cầu nối, không proxy; khóa mã hóa được tạo trên điện thoại.",
    "Sign-in is by QR code only (scan from a signed-in Telegram, plus the two-step password if set). Text messages, photos and files (view, save and send), groups and channels.":
        "Chỉ đăng nhập bằng mã QR (quét từ một Telegram đã đăng nhập, kèm mật khẩu hai bước nếu có). Tin nhắn văn bản, ảnh và tệp (xem, lưu và gửi), nhóm và kênh.",
    "Log": "Nhật ký",
    "Copy log": "Sao chép nhật ký",
    "Not connected.": "Chưa kết nối.",
    "Connecting...": "Đang kết nối...",
    "Connecting and creating the encryption key...": "Đang kết nối và tạo khóa mã hóa...",
    "Checking the password (this takes a few seconds)...": "Đang kiểm tra mật khẩu (mất vài giây)...",
    "This account has two-step verification. Enter the password.": "Tài khoản này có xác minh hai bước. Nhập mật khẩu.",
    "Requesting a sign-in code...": "Đang yêu cầu mã đăng nhập...",
    "Waiting for the code to be scanned...": "Đang chờ mã được quét...",
    "Signing in...": "Đang đăng nhập...",
    "Connection lost: %1. Reconnecting...": "Mất kết nối: %1. Đang kết nối lại...",
    "Connection failed: %1. Retrying...": "Kết nối thất bại: %1. Đang thử lại...",
    "Enter the password.": "Nhập mật khẩu.",
    "Copied.": "Đã sao chép.",
    "Load older messages": "Tải tin nhắn cũ hơn",
    "Reload": "Tải lại",
    "Unmute": "Bật tiếng",
    "Mute": "Tắt tiếng",
    "Mark as read": "Đánh dấu đã đọc",
    "Copy text": "Sao chép văn bản",
    "Reply": "Trả lời",
    "Replying to": "Đang trả lời",
    "Edit": "Sửa",
    "Editing message": "Đang sửa tin nhắn",
    "edit the text, then tap Save": "sửa văn bản, rồi nhấn Lưu",
    "Save": "Lưu",
    "Could not edit the message: %1": "Không thể sửa tin nhắn: %1",
    "Retry": "Thử lại",
    "Delete for me": "Xóa ở phía tôi",
    "Delete for everyone": "Xóa ở mọi phía",
    "connecting...": "đang kết nối...",
    "offline": "ngoại tuyến",
    "online": "trực tuyến",
    "Older messages": "Tin nhắn cũ hơn",
    "Could not load the messages: %1": "Không thể tải tin nhắn: %1",
    "No messages yet.": "Chưa có tin nhắn.",
    "channel - only its admins can post": "kênh — chỉ quản trị viên mới đăng được",
    "message": "tin nhắn",
    "Send": "Gửi",
    "Yesterday": "Hôm qua",
    "%1 is typing...": "%1 đang nhập...",
    "typing...": "đang nhập...",
    "You: %1": "Bạn: %1",
    "Connect": "Kết nối",
    "Disconnect": "Ngắt kết nối",
    "Settings": "Cài đặt",
    "About": "Giới thiệu",
    "Sign out": "Đăng xuất",
    "Exit": "Thoát",
    "Sign out? The session will be ended on Telegram and removed from this phone.": "Đăng xuất? Phiên sẽ bị kết thúc trên Telegram và xóa khỏi điện thoại này.",
    "Cancel": "Hủy",
    "New chat": "Trò chuyện mới",
    "Find": "Tìm",
    "@username, phone number, t.me link, or a contact's name": "@tên_người_dùng, số điện thoại, liên kết t.me, hoặc tên một liên hệ",
    "@username or +phone": "@tên_người_dùng hoặc +số",
    "Clear history": "Xóa lịch sử",
    "Delete all messages of \"%1\" on Telegram (for you)?": "Xóa tất cả tin nhắn của «%1» trên Telegram (ở phía bạn)?",
    "Delete": "Xóa",
    "loading...": "đang tải...",
    "Older chats": "Trò chuyện cũ hơn",
    "Loading chats...": "Đang tải các cuộc trò chuyện...",
    "No chats yet. Tap + to find someone.": "Chưa có cuộc trò chuyện nào. Nhấn + để tìm ai đó.",
    "Offline. Use the menu to connect.": "Ngoại tuyến. Dùng menu để kết nối.",
    "Telegram for Symbian": "Telegram cho Symbian",
    "No connection. Tap the refresh button to try again.": "Không có kết nối. Nhấn nút làm mới để thử lại.",
    "The code renews in %1 s": "Mã sẽ làm mới sau %1 giây",
    "Open Telegram on a phone or PC where you are signed in: Settings > Devices > Link Desktop Device, and scan this code.":
        "Mở Telegram trên điện thoại hoặc PC nơi bạn đã đăng nhập: Cài đặt > Thiết bị > Liên kết thiết bị máy tính, và quét mã này.",
    "Two-step verification password": "Mật khẩu xác minh hai bước",
    "hint: %1": "gợi ý: %1",
    "password": "mật khẩu",
    "show password": "hiện mật khẩu",
    "checking...": "đang kiểm tra...",
    "sign in": "đăng nhập",
    "Symbigram talks MTProto 2.0 straight to Telegram's servers: the encryption key is made on this phone and never leaves it. The session shows up under Devices in Telegram, where it can be ended at any time.":
        "Symbigram giao tiếp MTProto 2.0 trực tiếp với máy chủ của Telegram: khóa mã hóa được tạo trên điện thoại này và không bao giờ rời khỏi nó. Phiên hiển thị trong mục Thiết bị trên Telegram, nơi có thể kết thúc bất cứ lúc nào.",
    "Forwarded from %1": "Chuyển tiếp từ %1",
    "edited": "đã sửa",
    "Today": "Hôm nay",
    "reply": "trả lời",
    "You": "Bạn",
    "last seen at %1": "hoạt động lần cuối lúc %1",
    "last seen yesterday at %1": "hoạt động lần cuối hôm qua lúc %1",
    "last seen %1": "hoạt động lần cuối %1",
    "last seen recently": "hoạt động gần đây",
    "last seen within a week": "hoạt động trong tuần qua",
    "last seen within a month": "hoạt động trong tháng qua",
    "last seen a long time ago": "hoạt động đã lâu",
    "bot": "bot",
    "Saved Messages": "Tin nhắn đã lưu",
    "channel, %1 subscribers": "kênh, %1 người đăng ký",
    "channel": "kênh",
    "%1 members": "%1 thành viên",
    "group": "nhóm",
    "The message was not sent: %1": "Tin nhắn chưa được gửi: %1",
    "key exchange failed: %1": "trao đổi khóa thất bại: %1",
    "no response from the server": "máy chủ không phản hồi",
    "connection closed": "kết nối đã đóng",
    "connection timed out": "kết nối quá thời gian chờ",
    "Symbigram: new message": "Symbigram: tin nhắn mới",
    "Symbigram: %1 new messages": "Symbigram: %1 tin nhắn mới",
    "App language": "Ngôn ngữ ứng dụng",
    "System default": "Theo hệ thống",
    "Notifications": "Thông báo",
    "Popup for new messages": "Cửa sổ bật lên cho tin nhắn mới",
    "Vibrate": "Rung",
    "Groups and channels": "Nhóm và kênh",
    "For messages that arrive while another application is in front: the \"new messages\" dialog, the popup and the vibration. Chats muted in Telegram stay quiet. Symbigram stays connected in the background either way.":
        "Đối với tin nhắn đến khi một ứng dụng khác đang hiển thị: hộp thoại «tin nhắn mới», cửa sổ bật lên và rung. Các cuộc trò chuyện đã tắt tiếng trong Telegram vẫn im lặng. Dù thế nào Symbigram vẫn giữ kết nối ở chế độ nền.",
    "Connect on start": "Kết nối khi khởi động",
    "Takes effect after the app is restarted.": "Có hiệu lực sau khi khởi động lại ứng dụng.",
    "Signed out.": "Đã đăng xuất.",
    "Enter a username, a phone number or a name.": "Nhập tên người dùng, số điện thoại hoặc tên.",
    "This account has no password set.": "Tài khoản này chưa đặt mật khẩu.",
    "Unsupported password method.": "Phương thức mật khẩu không được hỗ trợ.",
    "Nobody found.": "Không tìm thấy ai.",
    "The session was ended (%1). Please sign in again.": "Phiên đã kết thúc (%1). Vui lòng đăng nhập lại.",
    "Wrong password.": "Sai mật khẩu.",
    "Too many attempts. Wait %1 seconds.": "Quá nhiều lần thử. Chờ %1 giây.",
    "Could not load the chat list: %1": "Không thể tải danh sách trò chuyện: %1",
    "user %1": "người dùng %1",
    "chat %1": "cuộc trò chuyện %1",
    "deleted account": "tài khoản đã xóa",
    "video": "video",
    "photo": "ảnh",
    "location %1, %2": "vị trí %1, %2",
    "location": "vị trí",
    "location: %1": "vị trí: %1",
    "contact: %1 %2 %3": "liên hệ: %1 %2 %3",
    "poll: %1": "khảo sát: %1",
    "dice: %1": "xúc xắc: %1",
    "game": "trò chơi",
    "invoice": "hóa đơn",
    "story": "tin",
    "file": "tệp",
    "sticker": "nhãn dán",
    "sticker %1": "nhãn dán %1",
    "voice message %1": "tin nhắn thoại %1",
    "voice message": "tin nhắn thoại",
    "video message %1": "tin nhắn video %1",
    "video message": "tin nhắn video",
    "GIF": "GIF",
    "video %1": "video %1",
    "audio %1": "âm thanh %1",
    "audio": "âm thanh",
    "image": "hình ảnh",
    "%1 MB": "%1 MB",
    "%1 KB": "%1 KB",
    "%1 B": "%1 B",
    "file: %1 (%2)": "tệp: %1 (%2)",
    "unsupported attachment": "tệp đính kèm không được hỗ trợ",
    "attachment": "tệp đính kèm",
    "created the group \"%1\"": "đã tạo nhóm «%1»",
    "created the channel \"%1\"": "đã tạo kênh «%1»",
    "added %1": "đã thêm %1",
    "removed %1": "đã xóa %1",
    "joined by invite link": "đã tham gia qua liên kết mời",
    "pinned a message": "đã ghim một tin nhắn",
    "joined Telegram": "đã tham gia Telegram",
    "cleared the history": "đã xóa lịch sử",
    "service message": "tin nhắn dịch vụ",
    "empty message": "tin nhắn trống",
    "Folders": "Thư mục",
    "Folder": "Thư mục",
    "All chats": "Tất cả trò chuyện",
    "Archive": "Lưu trữ",
    "tap to switch folder": "nhấn để chuyển thư mục",
    "The archive is empty.": "Kho lưu trữ trống.",
    "No chats in this folder.": "Không có cuộc trò chuyện nào trong thư mục này.",
    "Keep a log": "Ghi nhật ký",
    "Off by default. Turn it on only to collect a diagnostic log (shown on the About page) when something goes wrong.": "Mặc định tắt. Chỉ bật để thu thập nhật ký chẩn đoán (hiển thị ở trang «Giới thiệu») khi có sự cố.",
    "Logging is off. Turn on \"Keep a log\" in Settings to collect one.": "Ghi nhật ký đang tắt. Bật «Ghi nhật ký» trong Cài đặt để thu thập.",
    "Images (*.jpg *.jpeg *.png *.gif *.bmp)": "Hình ảnh (*.jpg *.jpeg *.png *.gif *.bmp)",
    "All files (*)": "Tất cả tệp (*)",
    "Choose an image": "Chọn một hình ảnh",
    "Send image": "Gửi hình ảnh",
    "Send file": "Gửi tệp",
    "Caption (optional)": "Chú thích (tùy chọn)",
    "add a caption": "thêm chú thích",
    "Choose a file": "Chọn một tệp",
    "Sending the image...": "Đang gửi hình ảnh...",
    "Sending the file...": "Đang gửi tệp...",
    "Image": "Hình ảnh",
    "File": "Tệp",
    "Save to phone": "Lưu vào điện thoại",
    "Open": "Mở",
    "Close": "Đóng",
    "Tap to load": "Nhấn để tải",
    "Failed - tap to retry": "Thất bại — nhấn để thử lại",
    "Voice message": "Tin nhắn thoại",
    "Video": "Video",
    "tap to open": "nhấn để mở",
    "downloading %1%": "đang tải %1%",
    "tap to download": "nhấn để tải xuống",
    "Saved to %1": "Đã lưu vào %1",
    "Could not save the file.": "Không thể lưu tệp.",
    "the server rejected a part of the file": "máy chủ đã từ chối một phần của tệp",
    "the file is served from a CDN, which is not supported": "tệp được phục vụ từ CDN, điều này không được hỗ trợ",
    "unexpected reply": "phản hồi không mong đợi",
    "could not write the file": "không thể ghi tệp",
    "could not create the file": "không thể tạo tệp",
    "the file is empty": "tệp trống",
    "could not read the file": "không thể đọc tệp",
    "the file is too large": "tệp quá lớn",
    "Start secret chat": "Bắt đầu trò chuyện bí mật",
    "Verify encryption key": "Xác minh khóa mã hóa",
    "Self-destruct timer": "Hẹn giờ tự hủy",
    "Delete secret chat": "Xóa trò chuyện bí mật",
    "End this secret chat? Its messages, which live only on this device, will be removed here.": "Kết thúc trò chuyện bí mật này? Các tin nhắn của nó, chỉ tồn tại trên thiết bị này, sẽ bị xóa tại đây.",
    "Encryption key": "Khóa mã hóa",
    "If this key matches on both phones, no one is intercepting the chat. Compare it with %1 in person or over a trusted channel.": "Nếu khóa này khớp trên cả hai điện thoại, không ai đang chặn cuộc trò chuyện. So sánh nó với %1 trực tiếp hoặc qua một kênh đáng tin cậy.",
    "%1 wants to start an end-to-end encrypted chat.": "%1 muốn bắt đầu một cuộc trò chuyện mã hóa đầu cuối.",
    "Waiting for the other side to come online and accept...": "Đang chờ phía bên kia trực tuyến và chấp nhận...",
    "Decline": "Từ chối",
    "Cancel request": "Hủy yêu cầu",
    "encrypted message": "tin nhắn được mã hóa",
    "secret chat": "trò chuyện bí mật",
    "wants to start a secret chat": "muốn bắt đầu trò chuyện bí mật",
    "waiting to be accepted...": "đang chờ được chấp nhận...",
    "end-to-end encrypted": "mã hóa đầu cuối",
    "end-to-end encrypted, self-destruct %1s": "mã hóa đầu cuối, tự hủy %1 giây",
    "Secret chats can only be opened with a person.": "Chỉ có thể mở trò chuyện bí mật với một người.",
    "The secret chat is not ready.": "Trò chuyện bí mật chưa sẵn sàng.",
    "Secret chats can only be started with a person.": "Chỉ có thể bắt đầu trò chuyện bí mật với một người.",
    "Starting a secret chat...": "Đang bắt đầu trò chuyện bí mật...",
    "Someone wants to start a secret chat.": "Ai đó muốn bắt đầu trò chuyện bí mật.",
    "%1 wants to start a secret chat.": "%1 muốn bắt đầu trò chuyện bí mật.",
    "Secret chat is ready.": "Trò chuyện bí mật đã sẵn sàng.",
    "Secret chat": "Trò chuyện bí mật",
    "Encrypted message": "Tin nhắn được mã hóa",
    "Could not start the secret chat: %1": "Không thể bắt đầu trò chuyện bí mật: %1",
    "Could not accept the secret chat: %1": "Không thể chấp nhận trò chuyện bí mật: %1",
    "Accept": "Chấp nhận",
    "Off": "Tắt",
    "5 seconds": "5 giây",
    "30 seconds": "30 giây",
    "1 minute": "1 phút",
    "1 hour": "1 giờ",
    "1 day": "1 ngày",
    "1 week": "1 tuần",
    "Saved": "Đã lưu",
    "File saved to: %1": "Đã lưu tệp vào: %1",
    "Could not save the file to %1": "Không thể lưu tệp vào %1",
    "Could not open the file.": "Không thể mở tệp.",
    "Phone memory": "Bộ nhớ điện thoại",
    "Mass memory": "Bộ nhớ lớn",
    "Memory card": "Thẻ nhớ",
    "Save downloads to": "Lưu tải xuống vào",
    "Clear cache": "Xóa bộ nhớ đệm",
    "Clear": "Xóa",
    "Downloaded media held on the phone: %1": "Nội dung đã tải lưu trên điện thoại: %1",
    "The app's private store of downloaded photos, avatars and files (separate from the folder above). Clearing it just re-downloads on demand.": "Kho lưu trữ riêng của ứng dụng chứa ảnh, ảnh đại diện và tệp đã tải (tách biệt với thư mục ở trên). Xóa nó chỉ khiến chúng được tải lại khi cần.",
    "Delete the %1 of downloaded media held on the phone? It will be fetched again when needed.": "Xóa %1 nội dung đã tải lưu trên điện thoại? Nó sẽ được tải lại khi cần.",
    "Cache cleared (%1 freed).": "Đã xóa bộ nhớ đệm (giải phóng %1).",
    "Choose folder...": "Chọn thư mục...",
    "Choose download folder": "Chọn thư mục tải xuống",
    "SOCKS5 proxy": "Proxy SOCKS5",
    "Proxy server": "Máy chủ proxy",
    "not set": "chưa đặt",
    "Route the connection through a SOCKS5 proxy. Changing it reconnects.": "Định tuyến kết nối qua proxy SOCKS5. Thay đổi sẽ kết nối lại.",
    "Server": "Máy chủ",
    "host or IP": "máy chủ hoặc IP",
    "Port": "Cổng",
    "Username (optional)": "Tên người dùng (tùy chọn)",
    "Password (optional)": "Mật khẩu (tùy chọn)",
    "Reconnect": "Kết nối lại",
    "Enable": "Bật",
    "Set up proxy": "Thiết lập proxy",
    "Cannot record a voice message here.": "Không thể ghi âm tin nhắn thoại ở đây.",
    "Sending the voice message...": "Đang gửi tin nhắn thoại...",
    "the microphone is unavailable (%1)": "micrô không khả dụng (%1)",
    "could not open the microphone (%1)": "không thể mở micrô (%1)",
    "could not start recording (%1)": "không thể bắt đầu ghi âm (%1)",
    "the recording was too short": "bản ghi quá ngắn",
    "could not encode the recording": "không thể mã hóa bản ghi",
    "could not save the recording": "không thể lưu bản ghi",
    "could not read the recording": "không thể đọc bản ghi",
    "Archive chat": "Lưu trữ cuộc trò chuyện",
    "Unarchive chat": "Bỏ lưu trữ cuộc trò chuyện",
    "Move to folder": "Chuyển đến thư mục",
    "All chats (no folder)": "Tất cả trò chuyện (không thư mục)",
    "Sign in with QR code": "Đăng nhập bằng mã QR",
    "Sign in with phone number": "Đăng nhập bằng số điện thoại",
    "Use QR code instead": "Dùng mã QR thay thế",
    "Phone number": "Số điện thoại",
    "Include the country code. Telegram will send a login code to this number.": "Bao gồm mã quốc gia. Telegram sẽ gửi mã đăng nhập đến số này.",
    "requesting...": "đang yêu cầu...",
    "send code": "gửi mã",
    "Enter the code sent to %1": "Nhập mã đã gửi đến %1",
    "code": "mã",
    "signing in...": "đang đăng nhập...",
    "Resend code": "Gửi lại mã",
    "Change number": "Đổi số",
    "Enter your phone number.": "Nhập số điện thoại của bạn.",
    "Enter the code.": "Nhập mã.",
    "Enter the code Telegram sent to %1.": "Nhập mã mà Telegram đã gửi đến %1.",
    "Requesting a code...": "Đang yêu cầu mã...",
    "Enter your phone number, with the country code, to get a code.": "Nhập số điện thoại của bạn, kèm mã quốc gia, để nhận mã.",
    "Enter a valid phone number, with the country code.": "Nhập một số điện thoại hợp lệ, kèm mã quốc gia.",
    "No Telegram account uses this number. Sign-up isn't supported here.": "Không có tài khoản Telegram nào dùng số này. Đăng ký không được hỗ trợ ở đây.",
    "That phone number is not valid.": "Số điện thoại đó không hợp lệ.",
    "That phone number is banned from Telegram.": "Số điện thoại đó bị cấm khỏi Telegram.",
    "Too many codes requested for this number. Try again later.": "Đã yêu cầu quá nhiều mã cho số này. Thử lại sau.",
    "Too many attempts. Try again later.": "Quá nhiều lần thử. Thử lại sau.",
    "This build's Telegram API key was rejected.": "Khóa API Telegram của bản dựng này bị từ chối.",
    "Wrong code. Check it and try again.": "Sai mã. Kiểm tra và thử lại.",
    "The code expired. Request a new one.": "Mã đã hết hạn. Yêu cầu mã mới.",
    "Delete chat": "Xóa cuộc trò chuyện",
    "Myself": "Chính tôi",
    "All": "Tất cả",
    "Delete for all": "Xóa ở mọi phía",
    "Delete the chat \"%1\"? \"All\" also removes it for the other side.": "Xóa cuộc trò chuyện «%1»? «Tất cả» cũng xóa nó ở phía bên kia.",
    "Could not change the folder: %1": "Không thể đổi thư mục: %1",
    "That folder must keep at least one chat, so the chat stays in it too.": "Thư mục đó phải giữ ít nhất một cuộc trò chuyện, nên cuộc trò chuyện vẫn ở trong đó.",
    "That folder no longer exists.": "Thư mục đó không còn tồn tại.",
    "the proxy refused our authentication method": "proxy đã từ chối phương thức xác thực của chúng tôi",
    "proxy authentication failed - check the username and password": "xác thực proxy thất bại — kiểm tra tên người dùng và mật khẩu",
    "the proxy sent a malformed reply": "proxy đã gửi phản hồi không hợp lệ",
    "the proxy could not reach the server (%1)": "proxy không thể kết nối đến máy chủ (%1)",
    "playing... tap to stop": "đang phát... nhấn để dừng",
    "loading %1%": "đang tải %1%",
    "tap to play": "nhấn để phát",
    "tap to play in player": "nhấn để phát trong trình phát",
    "buffering %1%... opening player": "đang đệm %1%... đang mở trình phát",
    "Could not play this audio: %1": "Không thể phát âm thanh này: %1",
    "could not open the voice file": "không thể mở tệp thoại",
    "could not decode the voice message": "không thể giải mã tin nhắn thoại",
    "audio is unavailable (%1)": "âm thanh không khả dụng (%1)",
    "could not open audio (%1)": "không thể mở âm thanh (%1)",
    "could not prepare playback": "không thể chuẩn bị phát",
    "could not start playback (%1)": "không thể bắt đầu phát (%1)",
    "could not play (%1)": "không thể phát (%1)",
    "recording is only available on the phone": "ghi âm chỉ khả dụng trên điện thoại",
    "Proxy: %1": "Proxy: %1",
    "on": "bật",
    "No connection through the proxy. Check the proxy or tap Reconnect.": "Không có kết nối qua proxy. Kiểm tra proxy hoặc nhấn Kết nối lại.",
    "No connection. Tap Reconnect, or set up a proxy if Telegram is blocked.": "Không có kết nối. Nhấn Kết nối lại, hoặc thiết lập proxy nếu Telegram bị chặn.",
    "Saved photos and files go here. Pick a drive, or \"Choose folder...\" for any folder.": "Ảnh và tệp đã lưu sẽ vào đây. Chọn một ổ đĩa, hoặc «Chọn thư mục...» cho thư mục bất kỳ.",
    "Saved photos and files go to a \"Symbigram\" folder on this drive.": "Ảnh và tệp đã lưu sẽ vào thư mục «Symbigram» trên ổ đĩa này.",
    "End the secret chat with \"%1\"? Its messages live only on this device and will be removed here.": "Kết thúc trò chuyện bí mật với «%1»? Các tin nhắn của nó chỉ tồn tại trên thiết bị này và sẽ bị xóa tại đây.",
    "%1 wants to start a secret chat": "%1 muốn bắt đầu trò chuyện bí mật",
}

HE = {
    "version %1": "גרסה %1",
    "A Telegram client for Symbian Anna/Belle, ported from Lumigram/LumigramPlus for Windows Phone 8.1. It speaks MTProto 2.0 directly to Telegram - no bridge, no proxy; the encryption key is made on the phone.":
        "לקוח טלגרם ל-Symbian Anna/Belle, מבוסס על Lumigram/LumigramPlus ל-Windows Phone 8.1. הוא מדבר MTProto 2.0 ישירות מול טלגרם — ללא גשר וללא פרוקסי; מפתח ההצפנה נוצר בטלפון.",
    "Sign-in is by QR code only (scan from a signed-in Telegram, plus the two-step password if set). Text messages, photos and files (view, save and send), groups and channels.":
        "הכניסה היא בעזרת קוד QR בלבד (סריקה מטלגרם שכבר מחוברים בו, בתוספת סיסמת האימות הדו-שלבי אם הוגדרה). הודעות טקסט, תמונות וקבצים (צפייה, שמירה ושליחה), קבוצות וערוצים.",
    "Log": "יומן",
    "Copy log": "העתקת היומן",
    "Not connected.": "לא מחובר.",
    "Connecting...": "מתחבר...",
    "Connecting and creating the encryption key...": "מתחבר ויוצר את מפתח ההצפנה...",
    "Checking the password (this takes a few seconds)...": "בודק את הסיסמה (זה אורך כמה שניות)...",
    "This account has two-step verification. Enter the password.": "לחשבון זה יש אימות דו-שלבי. הזינו את הסיסמה.",
    "Requesting a sign-in code...": "מבקש קוד כניסה...",
    "Waiting for the code to be scanned...": "ממתין לסריקת הקוד...",
    "Signing in...": "מתחבר...",
    "Connection lost: %1. Reconnecting...": "החיבור אבד: %1. מתחבר מחדש...",
    "Connection failed: %1. Retrying...": "החיבור נכשל: %1. מנסה שוב...",
    "Enter the password.": "הזינו את הסיסמה.",
    "Copied.": "הועתק.",
    "Load older messages": "טעינת הודעות ישנות יותר",
    "Reload": "רענון",
    "Unmute": "ביטול השתקה",
    "Mute": "השתקה",
    "Mark as read": "סימון כנקרא",
    "Copy text": "העתקת הטקסט",
    "Reply": "תגובה",
    "Replying to": "בתגובה ל",
    "Edit": "עריכה",
    "Editing message": "עריכת הודעה",
    "edit the text, then tap Save": "ערכו את הטקסט, ואז הקישו על שמירה",
    "Save": "שמירה",
    "Could not edit the message: %1": "לא ניתן היה לערוך את ההודעה: %1",
    "Retry": "ניסיון חוזר",
    "Delete for me": "מחיקה אצלי",
    "Delete for everyone": "מחיקה אצל כולם",
    "connecting...": "מתחבר...",
    "offline": "לא מחובר",
    "online": "מחובר",
    "Older messages": "הודעות ישנות יותר",
    "Could not load the messages: %1": "לא ניתן היה לטעון את ההודעות: %1",
    "No messages yet.": "אין הודעות עדיין.",
    "channel - only its admins can post": "ערוץ — רק מנהליו יכולים לפרסם",
    "message": "הודעה",
    "Send": "שליחה",
    "Yesterday": "אתמול",
    "%1 is typing...": "%1 מקליד...",
    "typing...": "מקליד...",
    "You: %1": "אתם: %1",
    "Connect": "התחברות",
    "Disconnect": "ניתוק",
    "Settings": "הגדרות",
    "About": "אודות",
    "Sign out": "התנתקות",
    "Exit": "יציאה",
    "Sign out? The session will be ended on Telegram and removed from this phone.": "להתנתק? ההפעלה תסתיים בטלגרם ותוסר מטלפון זה.",
    "Cancel": "ביטול",
    "New chat": "צ'אט חדש",
    "Find": "חיפוש",
    "@username, phone number, t.me link, or a contact's name": "@שם_משתמש, מספר טלפון, קישור t.me, או שם של איש קשר",
    "@username or +phone": "@שם_משתמש או +טלפון",
    "Clear history": "ניקוי ההיסטוריה",
    "Delete all messages of \"%1\" on Telegram (for you)?": "למחוק את כל ההודעות של «%1» בטלגרם (אצלכם)?",
    "Delete": "מחיקה",
    "loading...": "טוען...",
    "Older chats": "צ'אטים ישנים יותר",
    "Loading chats...": "טוען צ'אטים...",
    "No chats yet. Tap + to find someone.": "אין צ'אטים עדיין. הקישו על + כדי למצוא מישהו.",
    "Offline. Use the menu to connect.": "לא מחובר. השתמשו בתפריט כדי להתחבר.",
    "Telegram for Symbian": "טלגרם ל-Symbian",
    "No connection. Tap the refresh button to try again.": "אין חיבור. הקישו על כפתור הרענון כדי לנסות שוב.",
    "The code renews in %1 s": "הקוד יתחדש בעוד %1 שנ'",
    "Open Telegram on a phone or PC where you are signed in: Settings > Devices > Link Desktop Device, and scan this code.":
        "פתחו את טלגרם בטלפון או במחשב שבו אתם מחוברים: הגדרות > מכשירים > קישור מכשיר שולחני, וסרקו קוד זה.",
    "Two-step verification password": "סיסמת אימות דו-שלבי",
    "hint: %1": "רמז: %1",
    "password": "סיסמה",
    "show password": "הצגת הסיסמה",
    "checking...": "בודק...",
    "sign in": "כניסה",
    "Symbigram talks MTProto 2.0 straight to Telegram's servers: the encryption key is made on this phone and never leaves it. The session shows up under Devices in Telegram, where it can be ended at any time.":
        "Symbigram מדבר MTProto 2.0 ישירות מול השרתים של טלגרם: מפתח ההצפנה נוצר בטלפון זה ולעולם אינו עוזב אותו. ההפעלה מופיעה תחת «מכשירים» בטלגרם, שם ניתן לסיים אותה בכל עת.",
    "Forwarded from %1": "הועבר מ-%1",
    "edited": "נערך",
    "Today": "היום",
    "reply": "תגובה",
    "You": "אתם",
    "last seen at %1": "נראה לאחרונה ב-%1",
    "last seen yesterday at %1": "נראה לאחרונה אתמול ב-%1",
    "last seen %1": "נראה לאחרונה %1",
    "last seen recently": "נראה לאחרונה לפני זמן קצר",
    "last seen within a week": "נראה לאחרונה בשבוע האחרון",
    "last seen within a month": "נראה לאחרונה בחודש האחרון",
    "last seen a long time ago": "נראה לאחרונה לפני זמן רב",
    "bot": "בוט",
    "Saved Messages": "הודעות שמורות",
    "channel, %1 subscribers": "ערוץ, %1 מנויים",
    "channel": "ערוץ",
    "%1 members": "%1 חברים",
    "group": "קבוצה",
    "The message was not sent: %1": "ההודעה לא נשלחה: %1",
    "key exchange failed: %1": "החלפת המפתחות נכשלה: %1",
    "no response from the server": "אין תגובה מהשרת",
    "connection closed": "החיבור נסגר",
    "connection timed out": "תם הזמן הקצוב לחיבור",
    "Symbigram: new message": "Symbigram: הודעה חדשה",
    "Symbigram: %1 new messages": "Symbigram: %1 הודעות חדשות",
    "App language": "שפת היישום",
    "System default": "ברירת המחדל של המערכת",
    "Notifications": "התראות",
    "Popup for new messages": "חלון קופץ להודעות חדשות",
    "Vibrate": "רטט",
    "Groups and channels": "קבוצות וערוצים",
    "For messages that arrive while another application is in front: the \"new messages\" dialog, the popup and the vibration. Chats muted in Telegram stay quiet. Symbigram stays connected in the background either way.":
        "עבור הודעות שמגיעות כאשר יישום אחר נמצא בחזית: חלון «הודעות חדשות», החלון הקופץ והרטט. צ'אטים שהושתקו בטלגרם נשארים שקטים. Symbigram נשאר מחובר ברקע בכל מקרה.",
    "Connect on start": "התחברות בעת ההפעלה",
    "Takes effect after the app is restarted.": "ייכנס לתוקף לאחר הפעלה מחדש של היישום.",
    "Signed out.": "התנתקתם.",
    "Enter a username, a phone number or a name.": "הזינו שם משתמש, מספר טלפון או שם.",
    "This account has no password set.": "לחשבון זה לא הוגדרה סיסמה.",
    "Unsupported password method.": "שיטת סיסמה לא נתמכת.",
    "Nobody found.": "לא נמצא אף אחד.",
    "The session was ended (%1). Please sign in again.": "ההפעלה הסתיימה (%1). אנא היכנסו שוב.",
    "Wrong password.": "סיסמה שגויה.",
    "Too many attempts. Wait %1 seconds.": "יותר מדי ניסיונות. המתינו %1 שניות.",
    "Could not load the chat list: %1": "לא ניתן היה לטעון את רשימת הצ'אטים: %1",
    "user %1": "משתמש %1",
    "chat %1": "צ'אט %1",
    "deleted account": "חשבון שנמחק",
    "video": "וידאו",
    "photo": "תמונה",
    "location %1, %2": "מיקום %1, %2",
    "location": "מיקום",
    "location: %1": "מיקום: %1",
    "contact: %1 %2 %3": "איש קשר: %1 %2 %3",
    "poll: %1": "סקר: %1",
    "dice: %1": "קובייה: %1",
    "game": "משחק",
    "invoice": "חשבונית",
    "story": "סטורי",
    "file": "קובץ",
    "sticker": "מדבקה",
    "sticker %1": "מדבקה %1",
    "voice message %1": "הודעה קולית %1",
    "voice message": "הודעה קולית",
    "video message %1": "הודעת וידאו %1",
    "video message": "הודעת וידאו",
    "GIF": "GIF",
    "video %1": "וידאו %1",
    "audio %1": "שמע %1",
    "audio": "שמע",
    "image": "תמונה",
    "%1 MB": "%1 MB",
    "%1 KB": "%1 KB",
    "%1 B": "%1 B",
    "file: %1 (%2)": "קובץ: %1 (%2)",
    "unsupported attachment": "קובץ מצורף לא נתמך",
    "attachment": "קובץ מצורף",
    "created the group \"%1\"": "יצר את הקבוצה «%1»",
    "created the channel \"%1\"": "יצר את הערוץ «%1»",
    "added %1": "הוסיף את %1",
    "removed %1": "הסיר את %1",
    "joined by invite link": "הצטרף באמצעות קישור הזמנה",
    "pinned a message": "נעץ הודעה",
    "joined Telegram": "הצטרף לטלגרם",
    "cleared the history": "ניקה את ההיסטוריה",
    "service message": "הודעת שירות",
    "empty message": "הודעה ריקה",
    "Folders": "תיקיות",
    "Folder": "תיקייה",
    "All chats": "כל הצ'אטים",
    "Archive": "ארכיון",
    "tap to switch folder": "הקישו כדי להחליף תיקייה",
    "The archive is empty.": "הארכיון ריק.",
    "No chats in this folder.": "אין צ'אטים בתיקייה זו.",
    "Keep a log": "שמירת יומן",
    "Off by default. Turn it on only to collect a diagnostic log (shown on the About page) when something goes wrong.": "כבוי כברירת מחדל. הפעילו רק כדי לאסוף יומן אבחון (מוצג בעמוד «אודות») כשמשהו משתבש.",
    "Logging is off. Turn on \"Keep a log\" in Settings to collect one.": "רישום היומן כבוי. הפעילו «שמירת יומן» בהגדרות כדי לאסוף אותו.",
    "Images (*.jpg *.jpeg *.png *.gif *.bmp)": "תמונות (*.jpg *.jpeg *.png *.gif *.bmp)",
    "All files (*)": "כל הקבצים (*)",
    "Choose an image": "בחירת תמונה",
    "Send image": "שליחת תמונה",
    "Send file": "שליחת קובץ",
    "Caption (optional)": "כיתוב (רשות)",
    "add a caption": "הוספת כיתוב",
    "Choose a file": "בחירת קובץ",
    "Sending the image...": "שולח את התמונה...",
    "Sending the file...": "שולח את הקובץ...",
    "Image": "תמונה",
    "File": "קובץ",
    "Save to phone": "שמירה בטלפון",
    "Open": "פתיחה",
    "Close": "סגירה",
    "Tap to load": "הקישו כדי לטעון",
    "Failed - tap to retry": "נכשל — הקישו כדי לנסות שוב",
    "Voice message": "הודעה קולית",
    "Video": "וידאו",
    "tap to open": "הקישו כדי לפתוח",
    "downloading %1%": "מוריד %1%",
    "tap to download": "הקישו כדי להוריד",
    "Saved to %1": "נשמר ב-%1",
    "Could not save the file.": "לא ניתן היה לשמור את הקובץ.",
    "the server rejected a part of the file": "השרת דחה חלק מהקובץ",
    "the file is served from a CDN, which is not supported": "הקובץ מוגש מ-CDN, שאינו נתמך",
    "unexpected reply": "תגובה בלתי צפויה",
    "could not write the file": "לא ניתן היה לכתוב את הקובץ",
    "could not create the file": "לא ניתן היה ליצור את הקובץ",
    "the file is empty": "הקובץ ריק",
    "could not read the file": "לא ניתן היה לקרוא את הקובץ",
    "the file is too large": "הקובץ גדול מדי",
    "Start secret chat": "התחלת צ'אט סודי",
    "Verify encryption key": "אימות מפתח ההצפנה",
    "Self-destruct timer": "טיימר השמדה עצמית",
    "Delete secret chat": "מחיקת צ'אט סודי",
    "End this secret chat? Its messages, which live only on this device, will be removed here.": "לסיים צ'אט סודי זה? הודעותיו, השמורות רק במכשיר זה, יוסרו כאן.",
    "Encryption key": "מפתח הצפנה",
    "If this key matches on both phones, no one is intercepting the chat. Compare it with %1 in person or over a trusted channel.": "אם מפתח זה תואם בשני הטלפונים, אף אחד אינו מיירט את הצ'אט. השוו אותו עם %1 באופן אישי או דרך ערוץ מהימן.",
    "%1 wants to start an end-to-end encrypted chat.": "%1 רוצה להתחיל צ'אט מוצפן מקצה לקצה.",
    "Waiting for the other side to come online and accept...": "ממתין שהצד השני יתחבר ויקבל...",
    "Decline": "דחייה",
    "Cancel request": "ביטול הבקשה",
    "encrypted message": "הודעה מוצפנת",
    "secret chat": "צ'אט סודי",
    "wants to start a secret chat": "רוצה להתחיל צ'אט סודי",
    "waiting to be accepted...": "ממתין לאישור...",
    "end-to-end encrypted": "מוצפן מקצה לקצה",
    "end-to-end encrypted, self-destruct %1s": "מוצפן מקצה לקצה, השמדה עצמית %1 שנ'",
    "Secret chats can only be opened with a person.": "ניתן לפתוח צ'אטים סודיים רק עם אדם.",
    "The secret chat is not ready.": "הצ'אט הסודי אינו מוכן.",
    "Secret chats can only be started with a person.": "ניתן להתחיל צ'אטים סודיים רק עם אדם.",
    "Starting a secret chat...": "מתחיל צ'אט סודי...",
    "Someone wants to start a secret chat.": "מישהו רוצה להתחיל צ'אט סודי.",
    "%1 wants to start a secret chat.": "%1 רוצה להתחיל צ'אט סודי.",
    "Secret chat is ready.": "הצ'אט הסודי מוכן.",
    "Secret chat": "צ'אט סודי",
    "Encrypted message": "הודעה מוצפנת",
    "Could not start the secret chat: %1": "לא ניתן היה להתחיל את הצ'אט הסודי: %1",
    "Could not accept the secret chat: %1": "לא ניתן היה לקבל את הצ'אט הסודי: %1",
    "Accept": "קבלה",
    "Off": "כבוי",
    "5 seconds": "5 שניות",
    "30 seconds": "30 שניות",
    "1 minute": "דקה אחת",
    "1 hour": "שעה אחת",
    "1 day": "יום אחד",
    "1 week": "שבוע אחד",
    "Saved": "נשמר",
    "File saved to: %1": "הקובץ נשמר ב-%1",
    "Could not save the file to %1": "לא ניתן היה לשמור את הקובץ ב-%1",
    "Could not open the file.": "לא ניתן היה לפתוח את הקובץ.",
    "Phone memory": "זיכרון הטלפון",
    "Mass memory": "אחסון המוני",
    "Memory card": "כרטיס זיכרון",
    "Save downloads to": "שמירת הורדות אל",
    "Clear cache": "ניקוי המטמון",
    "Clear": "נקה",
    "Downloaded media held on the phone: %1": "מדיה שהורדה ונשמרת בטלפון: %1",
    "The app's private store of downloaded photos, avatars and files (separate from the folder above). Clearing it just re-downloads on demand.": "האחסון הפרטי של היישום לתמונות, לתמונות פרופיל ולקבצים שהורדו (נפרד מהתיקייה שלמעלה). ניקויו רק גורם להורדה מחדש לפי הצורך.",
    "Delete the %1 of downloaded media held on the phone? It will be fetched again when needed.": "למחוק את %1 של המדיה שהורדה ונשמרת בטלפון? היא תורד שוב בעת הצורך.",
    "Cache cleared (%1 freed).": "המטמון נוקה (%1 פונו).",
    "Choose folder...": "בחירת תיקייה...",
    "Choose download folder": "בחירת תיקיית הורדות",
    "SOCKS5 proxy": "פרוקסי SOCKS5",
    "Proxy server": "שרת פרוקסי",
    "not set": "לא הוגדר",
    "Route the connection through a SOCKS5 proxy. Changing it reconnects.": "ניתוב החיבור דרך פרוקסי SOCKS5. שינוי גורם להתחברות מחדש.",
    "Server": "שרת",
    "host or IP": "מארח או IP",
    "Port": "יציאה",
    "Username (optional)": "שם משתמש (רשות)",
    "Password (optional)": "סיסמה (רשות)",
    "Reconnect": "התחברות מחדש",
    "Enable": "הפעלה",
    "Set up proxy": "הגדרת פרוקסי",
    "Cannot record a voice message here.": "לא ניתן להקליט כאן הודעה קולית.",
    "Sending the voice message...": "שולח את ההודעה הקולית...",
    "the microphone is unavailable (%1)": "המיקרופון אינו זמין (%1)",
    "could not open the microphone (%1)": "לא ניתן היה לפתוח את המיקרופון (%1)",
    "could not start recording (%1)": "לא ניתן היה להתחיל בהקלטה (%1)",
    "the recording was too short": "ההקלטה הייתה קצרה מדי",
    "could not encode the recording": "לא ניתן היה לקודד את ההקלטה",
    "could not save the recording": "לא ניתן היה לשמור את ההקלטה",
    "could not read the recording": "לא ניתן היה לקרוא את ההקלטה",
    "Archive chat": "העברת צ'אט לארכיון",
    "Unarchive chat": "הוצאת צ'אט מהארכיון",
    "Move to folder": "העברה לתיקייה",
    "All chats (no folder)": "כל הצ'אטים (ללא תיקייה)",
    "Sign in with QR code": "כניסה עם קוד QR",
    "Sign in with phone number": "כניסה עם מספר טלפון",
    "Use QR code instead": "שימוש בקוד QR במקום",
    "Phone number": "מספר טלפון",
    "Include the country code. Telegram will send a login code to this number.": "כללו את קידומת המדינה. טלגרם ישלח קוד כניסה למספר זה.",
    "requesting...": "מבקש...",
    "send code": "שליחת קוד",
    "Enter the code sent to %1": "הזינו את הקוד שנשלח אל %1",
    "code": "קוד",
    "signing in...": "מתחבר...",
    "Resend code": "שליחת קוד מחדש",
    "Change number": "שינוי מספר",
    "Enter your phone number.": "הזינו את מספר הטלפון שלכם.",
    "Enter the code.": "הזינו את הקוד.",
    "Enter the code Telegram sent to %1.": "הזינו את הקוד שטלגרם שלח אל %1.",
    "Requesting a code...": "מבקש קוד...",
    "Enter your phone number, with the country code, to get a code.": "הזינו את מספר הטלפון שלכם, עם קידומת המדינה, כדי לקבל קוד.",
    "Enter a valid phone number, with the country code.": "הזינו מספר טלפון תקין, עם קידומת המדינה.",
    "No Telegram account uses this number. Sign-up isn't supported here.": "אין חשבון טלגרם שמשתמש במספר זה. הרשמה אינה נתמכת כאן.",
    "That phone number is not valid.": "מספר הטלפון הזה אינו תקין.",
    "That phone number is banned from Telegram.": "מספר הטלפון הזה חסום בטלגרם.",
    "Too many codes requested for this number. Try again later.": "התבקשו יותר מדי קודים למספר זה. נסו שוב מאוחר יותר.",
    "Too many attempts. Try again later.": "יותר מדי ניסיונות. נסו שוב מאוחר יותר.",
    "This build's Telegram API key was rejected.": "מפתח ה-API של טלגרם בגרסה זו נדחה.",
    "Wrong code. Check it and try again.": "קוד שגוי. בדקו אותו ונסו שוב.",
    "The code expired. Request a new one.": "הקוד פג. בקשו קוד חדש.",
    "Delete chat": "מחיקת צ'אט",
    "Myself": "אצלי",
    "All": "אצל כולם",
    "Delete for all": "מחיקה אצל כולם",
    "Delete the chat \"%1\"? \"All\" also removes it for the other side.": "למחוק את הצ'אט «%1»? «אצל כולם» מוחק אותו גם אצל הצד השני.",
    "Could not change the folder: %1": "לא ניתן היה לשנות את התיקייה: %1",
    "That folder must keep at least one chat, so the chat stays in it too.": "בתיקייה זו חייב להישאר לפחות צ'אט אחד, ולכן הצ'אט נשאר גם בה.",
    "That folder no longer exists.": "התיקייה הזו כבר אינה קיימת.",
    "the proxy refused our authentication method": "הפרוקסי דחה את שיטת האימות שלנו",
    "proxy authentication failed - check the username and password": "אימות הפרוקסי נכשל — בדקו את שם המשתמש והסיסמה",
    "the proxy sent a malformed reply": "הפרוקסי שלח תגובה פגומה",
    "the proxy could not reach the server (%1)": "הפרוקסי לא הצליח להגיע לשרת (%1)",
    "playing... tap to stop": "מנגן... הקישו כדי לעצור",
    "loading %1%": "טוען %1%",
    "tap to play": "הקישו כדי לנגן",
    "tap to play in player": "הקישו כדי לנגן בנגן",
    "buffering %1%... opening player": "ממלא מאגר %1%... פותח את הנגן",
    "Could not play this audio: %1": "לא ניתן היה לנגן שמע זה: %1",
    "could not open the voice file": "לא ניתן היה לפתוח את קובץ השמע",
    "could not decode the voice message": "לא ניתן היה לפענח את ההודעה הקולית",
    "audio is unavailable (%1)": "השמע אינו זמין (%1)",
    "could not open audio (%1)": "לא ניתן היה לפתוח את השמע (%1)",
    "could not prepare playback": "לא ניתן היה להכין את הנגינה",
    "could not start playback (%1)": "לא ניתן היה להתחיל בנגינה (%1)",
    "could not play (%1)": "לא ניתן היה לנגן (%1)",
    "recording is only available on the phone": "הקלטה זמינה רק בטלפון",
    "Proxy: %1": "פרוקסי: %1",
    "on": "פועל",
    "No connection through the proxy. Check the proxy or tap Reconnect.": "אין חיבור דרך הפרוקסי. בדקו את הפרוקסי או הקישו על התחברות מחדש.",
    "No connection. Tap Reconnect, or set up a proxy if Telegram is blocked.": "אין חיבור. הקישו על התחברות מחדש, או הגדירו פרוקסי אם טלגרם חסום.",
    "Saved photos and files go here. Pick a drive, or \"Choose folder...\" for any folder.": "תמונות וקבצים שנשמרו יגיעו לכאן. בחרו כונן, או «בחירת תיקייה...» לכל תיקייה שהיא.",
    "Saved photos and files go to a \"Symbigram\" folder on this drive.": "תמונות וקבצים שנשמרו מגיעים לתיקיית «Symbigram» בכונן זה.",
    "End the secret chat with \"%1\"? Its messages live only on this device and will be removed here.": "לסיים את הצ'אט הסודי עם «%1»? הודעותיו שמורות רק במכשיר זה ויוסרו כאן.",
    "%1 wants to start a secret chat": "%1 רוצה להתחיל צ'אט סודי",
}


def fill(lang, table):
    path = os.path.join(ROOT, "translations", "symbigram_%s.ts" % lang)
    tree = ET.parse(path)
    root = tree.getroot()
    root.set("language", lang)
    missing = []
    for ctx in root.findall("context"):
        for msg in ctx.findall("message"):
            source = msg.find("source").text or ""
            tr = msg.find("translation")
            if tr is None:
                tr = ET.SubElement(msg, "translation")
            if source in table:
                tr.text = table[source]
                if "type" in tr.attrib:
                    del tr.attrib["type"]
            else:
                missing.append(source)
    tree.write(path, encoding="utf-8", xml_declaration=True)
    print("%s: %d untranslated" % (lang, len(missing)))
    for m in missing:
        print("   " + m)


fill("ru", RU)
fill("uk", UK)
fill("vi", VI)
fill("he", HE)
