#!/usr/bin/env python3
# Fills translations/symbigram_<lang>.ts from the tables below (source text -> translation).
# Strings not in a table stay untranslated (English) and are listed. Languages: ru, uk.
#
#   lupdate -extensions qml,cpp,h -no-obsolete src qml -ts translations/symbigram_ru.ts translations/symbigram_uk.ts
#   python tools/translate.py
#   lrelease translations/symbigram_ru.ts translations/symbigram_uk.ts
import os
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

RU = {
    "version %1": "версия %1",
    "A Telegram client for Symbian Anna/Belle, ported from Lumigram/LumigramPlus for Windows Phone 8.1. It speaks MTProto 2.0 directly to Telegram - no bridge, no proxy; the encryption key is made on the phone.":
        "Telegram-клиент для Symbian Anna/Belle, перенесённый с Lumigram/LumigramPlus для Windows Phone 8.1. Говорит с Telegram напрямую по MTProto 2.0 — без моста и прокси; ключ шифрования создаётся на телефоне.",
    "Sign-in is by QR code only (scan from a signed-in Telegram, plus the two-step password if set). Text messages, groups and channels; attachments are shown as notes, not downloaded.":
        "Вход только по QR-коду (сканируется из Telegram, где вы уже вошли; плюс пароль двухэтапной проверки, если он есть). Текстовые сообщения, группы и каналы; вложения показываются как пометки, не скачиваются.",
    "Log": "Журнал",
    "Copy log": "Скопировать журнал",
    "Not connected.": "Нет соединения.",
    "Connecting...": "Подключение...",
    "Connecting and creating the encryption key...": "Подключение и создание ключа шифрования...",
    "Checking the password (this takes a few seconds)...": "Проверка пароля (это займёт несколько секунд)...",
    "This account has two-step verification. Enter the password.": "У этого аккаунта включена двухэтапная проверка. Введите пароль.",
    "Requesting a sign-in code...": "Запрос кода для входа...",
    "Waiting for the code to be scanned...": "Ожидание сканирования кода...",
    "Signing in...": "Вход...",
    "Connection lost: %1. Reconnecting...": "Соединение потеряно: %1. Переподключение...",
    "Connection failed: %1. Retrying...": "Не удалось подключиться: %1. Повтор...",
    "Enter the password.": "Введите пароль.",
    "Copied.": "Скопировано.",
    "Load older messages": "Загрузить более старые сообщения",
    "Reload": "Обновить",
    "Unmute": "Включить уведомления",
    "Mute": "Отключить уведомления",
    "Mark as read": "Отметить прочитанным",
    "Copy text": "Скопировать текст",
    "Retry": "Повторить",
    "Delete for me": "Удалить у себя",
    "Delete for everyone": "Удалить у всех",
    "connecting...": "подключение...",
    "offline": "не в сети",
    "online": "в сети",
    "Older messages": "Более старые сообщения",
    "Could not load the messages: %1": "Не удалось загрузить сообщения: %1",
    "No messages yet.": "Сообщений пока нет.",
    "channel - only its admins can post": "канал — писать могут только его администраторы",
    "message": "сообщение",
    "Send": "Отправить",
    "Yesterday": "Вчера",
    "%1 is typing...": "%1 печатает...",
    "typing...": "печатает...",
    "You: %1": "Вы: %1",
    "Connect": "Подключиться",
    "Disconnect": "Отключиться",
    "Settings": "Настройки",
    "About": "О программе",
    "Sign out": "Выйти",
    "Sign out? The session will be ended on Telegram and removed from this phone.": "Выйти? Сеанс будет завершён в Telegram и удалён с этого телефона.",
    "Cancel": "Отмена",
    "New chat": "Новый чат",
    "Find": "Найти",
    "@username, phone number, t.me link, or a contact's name": "@username, номер телефона, ссылка t.me или имя контакта",
    "@username or +phone": "@username или +телефон",
    "Clear history": "Очистить историю",
    "Delete all messages of \"%1\" on Telegram (for you)?": "Удалить все сообщения чата «%1» в Telegram (у себя)?",
    "Delete": "Удалить",
    "loading...": "загрузка...",
    "Older chats": "Более старые чаты",
    "Loading chats...": "Загрузка чатов...",
    "No chats yet. Tap + to find someone.": "Чатов пока нет. Нажмите +, чтобы найти собеседника.",
    "Offline. Use the menu to connect.": "Не в сети. Подключитесь через меню.",
    "Telegram for Symbian": "Telegram для Symbian",
    "No connection. Tap the refresh button to try again.": "Нет соединения. Нажмите кнопку обновления, чтобы повторить.",
    "The code renews in %1 s": "Код обновится через %1 с",
    "Open Telegram on a phone or PC where you are signed in: Settings > Devices > Link Desktop Device, and scan this code.":
        "Откройте Telegram на телефоне или ПК, где вы уже вошли: Настройки > Устройства > Подключить устройство, и отсканируйте этот код.",
    "Two-step verification password": "Пароль двухэтапной проверки",
    "hint: %1": "подсказка: %1",
    "password": "пароль",
    "show password": "показать пароль",
    "checking...": "проверка...",
    "sign in": "войти",
    "Symbigram talks MTProto 2.0 straight to Telegram's servers: the encryption key is made on this phone and never leaves it. The session shows up under Devices in Telegram, where it can be ended at any time.":
        "Symbigram говорит с серверами Telegram напрямую по MTProto 2.0: ключ шифрования создаётся на этом телефоне и никогда его не покидает. Сеанс виден в разделе «Устройства» в Telegram, где его можно завершить в любой момент.",
    "Forwarded from %1": "Переслано от %1",
    "edited": "изменено",
    "Today": "Сегодня",
    "reply": "ответ",
    "You": "Вы",
    "last seen at %1": "был(а) в %1",
    "last seen yesterday at %1": "был(а) вчера в %1",
    "last seen %1": "был(а) %1",
    "last seen recently": "был(а) недавно",
    "last seen within a week": "был(а) на этой неделе",
    "last seen within a month": "был(а) в этом месяце",
    "last seen a long time ago": "был(а) давно",
    "bot": "бот",
    "Saved Messages": "Избранное",
    "channel, %1 subscribers": "канал, подписчиков: %1",
    "channel": "канал",
    "%1 members": "участников: %1",
    "group": "группа",
    "The message was not sent: %1": "Сообщение не отправлено: %1",
    "key exchange failed: %1": "обмен ключами не удался: %1",
    "no response from the server": "сервер не отвечает",
    "connection closed": "соединение закрыто",
    "connection timed out": "время ожидания соединения истекло",
    "Symbigram: new message": "Symbigram: новое сообщение",
    "Symbigram: %1 new messages": "Symbigram: новых сообщений: %1",
    "App language": "Язык приложения",
    "System default": "Как в системе",
    "Notifications": "Уведомления",
    "Popup for new messages": "Всплывающее окно о новых сообщениях",
    "Vibrate": "Вибрация",
    "Groups and channels": "Группы и каналы",
    "For messages that arrive while another application is in front: the \"new messages\" dialog, the popup and the vibration. Chats muted in Telegram stay quiet. Symbigram stays connected in the background either way.":
        "Для сообщений, пришедших, пока открыто другое приложение: диалог «новые сообщения», всплывающее окно и вибрация. Чаты, отключённые в Telegram, остаются беззвучными. Symbigram в любом случае остаётся на связи в фоне.",
    "Connect on start": "Подключаться при запуске",
    "Takes effect after the app is restarted.": "Вступает в силу после перезапуска приложения.",
    "Signed out.": "Выход выполнен.",
    "Enter a username, a phone number or a name.": "Введите имя пользователя, номер телефона или имя.",
    "This account has no password set.": "У этого аккаунта нет пароля.",
    "Unsupported password method.": "Неподдерживаемый способ проверки пароля.",
    "Nobody found.": "Никого не найдено.",
    "The session was ended (%1). Please sign in again.": "Сеанс завершён (%1). Войдите снова.",
    "Wrong password.": "Неверный пароль.",
    "Too many attempts. Wait %1 seconds.": "Слишком много попыток. Подождите %1 с.",
    "Could not load the chat list: %1": "Не удалось загрузить список чатов: %1",
    "user %1": "пользователь %1",
    "chat %1": "чат %1",
    "deleted account": "удалённый аккаунт",
    "video": "видео",
    "photo": "фото",
    "location %1, %2": "геопозиция %1, %2",
    "location": "геопозиция",
    "location: %1": "место: %1",
    "contact: %1 %2 %3": "контакт: %1 %2 %3",
    "poll: %1": "опрос: %1",
    "dice: %1": "кубик: %1",
    "game": "игра",
    "invoice": "счёт",
    "story": "история",
    "file": "файл",
    "sticker": "стикер",
    "sticker %1": "стикер %1",
    "voice message %1": "голосовое сообщение %1",
    "voice message": "голосовое сообщение",
    "video message %1": "видеосообщение %1",
    "video message": "видеосообщение",
    "GIF": "GIF",
    "video %1": "видео %1",
    "audio %1": "аудио %1",
    "audio": "аудио",
    "image": "изображение",
    "%1 MB": "%1 МБ",
    "%1 KB": "%1 КБ",
    "%1 B": "%1 Б",
    "file: %1 (%2)": "файл: %1 (%2)",
    "unsupported attachment": "неподдерживаемое вложение",
    "attachment": "вложение",
    "created the group \"%1\"": "создал(а) группу «%1»",
    "created the channel \"%1\"": "создал(а) канал «%1»",
    "added %1": "добавил(а) %1",
    "removed %1": "удалил(а) %1",
    "joined by invite link": "вступил(а) по ссылке-приглашению",
    "pinned a message": "закрепил(а) сообщение",
    "joined Telegram": "присоединился(-ась) к Telegram",
    "cleared the history": "очистил(а) историю",
    "service message": "служебное сообщение",
    "empty message": "пустое сообщение",
}

UK = {
    "version %1": "версія %1",
    "A Telegram client for Symbian Anna/Belle, ported from Lumigram/LumigramPlus for Windows Phone 8.1. It speaks MTProto 2.0 directly to Telegram - no bridge, no proxy; the encryption key is made on the phone.":
        "Telegram-клієнт для Symbian Anna/Belle, перенесений із Lumigram/LumigramPlus для Windows Phone 8.1. Спілкується з Telegram напряму по MTProto 2.0 — без мосту та проксі; ключ шифрування створюється на телефоні.",
    "Sign-in is by QR code only (scan from a signed-in Telegram, plus the two-step password if set). Text messages, groups and channels; attachments are shown as notes, not downloaded.":
        "Вхід лише за QR-кодом (сканується з Telegram, де ви вже увійшли; плюс пароль двоетапної перевірки, якщо він є). Текстові повідомлення, групи та канали; вкладення показуються як позначки, не завантажуються.",
    "Log": "Журнал",
    "Copy log": "Скопіювати журнал",
    "Not connected.": "Немає з'єднання.",
    "Connecting...": "Підключення...",
    "Connecting and creating the encryption key...": "Підключення та створення ключа шифрування...",
    "Checking the password (this takes a few seconds)...": "Перевірка пароля (це займе кілька секунд)...",
    "This account has two-step verification. Enter the password.": "У цього облікового запису ввімкнено двоетапну перевірку. Введіть пароль.",
    "Requesting a sign-in code...": "Запит коду для входу...",
    "Waiting for the code to be scanned...": "Очікування сканування коду...",
    "Signing in...": "Вхід...",
    "Connection lost: %1. Reconnecting...": "З'єднання втрачено: %1. Перепідключення...",
    "Connection failed: %1. Retrying...": "Не вдалося підключитися: %1. Повтор...",
    "Enter the password.": "Введіть пароль.",
    "Copied.": "Скопійовано.",
    "Load older messages": "Завантажити старіші повідомлення",
    "Reload": "Оновити",
    "Unmute": "Увімкнути сповіщення",
    "Mute": "Вимкнути сповіщення",
    "Mark as read": "Позначити прочитаним",
    "Copy text": "Скопіювати текст",
    "Retry": "Повторити",
    "Delete for me": "Видалити в себе",
    "Delete for everyone": "Видалити в усіх",
    "connecting...": "підключення...",
    "offline": "не в мережі",
    "online": "у мережі",
    "Older messages": "Старіші повідомлення",
    "Could not load the messages: %1": "Не вдалося завантажити повідомлення: %1",
    "No messages yet.": "Повідомлень поки немає.",
    "channel - only its admins can post": "канал — писати можуть лише його адміністратори",
    "message": "повідомлення",
    "Send": "Надіслати",
    "Yesterday": "Вчора",
    "%1 is typing...": "%1 друкує...",
    "typing...": "друкує...",
    "You: %1": "Ви: %1",
    "Connect": "Підключитися",
    "Disconnect": "Відключитися",
    "Settings": "Налаштування",
    "About": "Про програму",
    "Sign out": "Вийти",
    "Sign out? The session will be ended on Telegram and removed from this phone.": "Вийти? Сеанс буде завершено в Telegram і видалено з цього телефону.",
    "Cancel": "Скасувати",
    "New chat": "Новий чат",
    "Find": "Знайти",
    "@username, phone number, t.me link, or a contact's name": "@username, номер телефону, посилання t.me або ім'я контакту",
    "@username or +phone": "@username або +телефон",
    "Clear history": "Очистити історію",
    "Delete all messages of \"%1\" on Telegram (for you)?": "Видалити всі повідомлення чату «%1» у Telegram (у себе)?",
    "Delete": "Видалити",
    "loading...": "завантаження...",
    "Older chats": "Старіші чати",
    "Loading chats...": "Завантаження чатів...",
    "No chats yet. Tap + to find someone.": "Чатів поки немає. Натисніть +, щоб знайти співрозмовника.",
    "Offline. Use the menu to connect.": "Не в мережі. Підключіться через меню.",
    "Telegram for Symbian": "Telegram для Symbian",
    "No connection. Tap the refresh button to try again.": "Немає з'єднання. Натисніть кнопку оновлення, щоб повторити.",
    "The code renews in %1 s": "Код оновиться через %1 с",
    "Open Telegram on a phone or PC where you are signed in: Settings > Devices > Link Desktop Device, and scan this code.":
        "Відкрийте Telegram на телефоні або ПК, де ви вже увійшли: Налаштування > Пристрої > Підключити пристрій, і відскануйте цей код.",
    "Two-step verification password": "Пароль двоетапної перевірки",
    "hint: %1": "підказка: %1",
    "password": "пароль",
    "show password": "показати пароль",
    "checking...": "перевірка...",
    "sign in": "увійти",
    "Symbigram talks MTProto 2.0 straight to Telegram's servers: the encryption key is made on this phone and never leaves it. The session shows up under Devices in Telegram, where it can be ended at any time.":
        "Symbigram спілкується із серверами Telegram напряму по MTProto 2.0: ключ шифрування створюється на цьому телефоні й ніколи його не залишає. Сеанс видно в розділі «Пристрої» в Telegram, де його можна завершити будь-коли.",
    "Forwarded from %1": "Переслано від %1",
    "edited": "змінено",
    "Today": "Сьогодні",
    "reply": "відповідь",
    "You": "Ви",
    "last seen at %1": "був(ла) о %1",
    "last seen yesterday at %1": "був(ла) вчора о %1",
    "last seen %1": "був(ла) %1",
    "last seen recently": "був(ла) нещодавно",
    "last seen within a week": "був(ла) цього тижня",
    "last seen within a month": "був(ла) цього місяця",
    "last seen a long time ago": "був(ла) давно",
    "bot": "бот",
    "Saved Messages": "Збережене",
    "channel, %1 subscribers": "канал, підписників: %1",
    "channel": "канал",
    "%1 members": "учасників: %1",
    "group": "група",
    "The message was not sent: %1": "Повідомлення не надіслано: %1",
    "key exchange failed: %1": "обмін ключами не вдався: %1",
    "no response from the server": "сервер не відповідає",
    "connection closed": "з'єднання закрито",
    "connection timed out": "час очікування з'єднання минув",
    "Symbigram: new message": "Symbigram: нове повідомлення",
    "Symbigram: %1 new messages": "Symbigram: нових повідомлень: %1",
    "App language": "Мова програми",
    "System default": "Як у системі",
    "Notifications": "Сповіщення",
    "Popup for new messages": "Спливаюче вікно про нові повідомлення",
    "Vibrate": "Вібрація",
    "Groups and channels": "Групи та канали",
    "For messages that arrive while another application is in front: the \"new messages\" dialog, the popup and the vibration. Chats muted in Telegram stay quiet. Symbigram stays connected in the background either way.":
        "Для повідомлень, що надійшли, поки відкрито іншу програму: діалог «нові повідомлення», спливаюче вікно та вібрація. Чати, вимкнені в Telegram, лишаються беззвучними. Symbigram у будь-якому разі лишається на зв'язку у фоні.",
    "Connect on start": "Підключатися під час запуску",
    "Takes effect after the app is restarted.": "Набуде чинності після перезапуску програми.",
    "Signed out.": "Вихід виконано.",
    "Enter a username, a phone number or a name.": "Введіть ім'я користувача, номер телефону або ім'я.",
    "This account has no password set.": "У цього облікового запису немає пароля.",
    "Unsupported password method.": "Непідтримуваний спосіб перевірки пароля.",
    "Nobody found.": "Нікого не знайдено.",
    "The session was ended (%1). Please sign in again.": "Сеанс завершено (%1). Увійдіть знову.",
    "Wrong password.": "Неправильний пароль.",
    "Too many attempts. Wait %1 seconds.": "Забагато спроб. Зачекайте %1 с.",
    "Could not load the chat list: %1": "Не вдалося завантажити список чатів: %1",
    "user %1": "користувач %1",
    "chat %1": "чат %1",
    "deleted account": "видалений обліковий запис",
    "video": "відео",
    "photo": "фото",
    "location %1, %2": "геопозиція %1, %2",
    "location": "геопозиція",
    "location: %1": "місце: %1",
    "contact: %1 %2 %3": "контакт: %1 %2 %3",
    "poll: %1": "опитування: %1",
    "dice: %1": "кубик: %1",
    "game": "гра",
    "invoice": "рахунок",
    "story": "історія",
    "file": "файл",
    "sticker": "стікер",
    "sticker %1": "стікер %1",
    "voice message %1": "голосове повідомлення %1",
    "voice message": "голосове повідомлення",
    "video message %1": "відеоповідомлення %1",
    "video message": "відеоповідомлення",
    "GIF": "GIF",
    "video %1": "відео %1",
    "audio %1": "аудіо %1",
    "audio": "аудіо",
    "image": "зображення",
    "%1 MB": "%1 МБ",
    "%1 KB": "%1 КБ",
    "%1 B": "%1 Б",
    "file: %1 (%2)": "файл: %1 (%2)",
    "unsupported attachment": "непідтримуване вкладення",
    "attachment": "вкладення",
    "created the group \"%1\"": "створив(ла) групу «%1»",
    "created the channel \"%1\"": "створив(ла) канал «%1»",
    "added %1": "додав(ла) %1",
    "removed %1": "видалив(ла) %1",
    "joined by invite link": "приєднався(-лась) за посиланням-запрошенням",
    "pinned a message": "закріпив(ла) повідомлення",
    "joined Telegram": "приєднався(-лась) до Telegram",
    "cleared the history": "очистив(ла) історію",
    "service message": "службове повідомлення",
    "empty message": "порожнє повідомлення",
}


def fill(lang, table):
    path = os.path.join(ROOT, "translations", "symbigram_%s.ts" % lang)
    tree = ET.parse(path)
    root = tree.getroot()
    root.set("language", lang)
    missing = []
    for ctx in root.findall("context"):
        for msg in ctx.findall("message"):
            source = msg.find("source").text or ""
            tr = msg.find("translation")
            if tr is None:
                tr = ET.SubElement(msg, "translation")
            if source in table:
                tr.text = table[source]
                if "type" in tr.attrib:
                    del tr.attrib["type"]
            else:
                missing.append(source)
    tree.write(path, encoding="utf-8", xml_declaration=True)
    print("%s: %d untranslated" % (lang, len(missing)))
    for m in missing:
        print("   " + m)


fill("ru", RU)
fill("uk", UK)
